### ISSUE TITLE
Connection between Azure Opc UA Twin and Azure Digital Twin 

### ISSUE THREAD

**Issue by CaKlein93** [Azure/Industrial-IoT#10]
Hello Mr. Schier,

I'm currently working on a studentproject, where i want to generate an asset administration shell (AAS) on the azure-cloud by using the opc ua twin and map it to azure digital twin. Is there any connection interface available or are they just standalone services? If you have any idea to map these services, it would be very helpful. You also can contact me via e-mail. 
   
Many thanks in advance.

**Comment by MickeyMouseS** [comment]
Hi,

@marcschier mentioned "The idea is to be able to instruct the OPC Twin edge module to upload a device nodeset to blob and from there into cosmos db graph.". And you have marked this issue as completed. But I can not find documentation or how to make use of this feature. Is a feature of the platform? Could you shed some light on it?

Thank you
