### ISSUE TITLE
PublishedNodesJobConverter reads only the first subscription in publishednodes.json

### ISSUE THREAD

**Issue by Haeavar** [Azure/Industrial-IoT#1024]
**Describe the bug**
My publishednodes.json contains two subscriptions to two different OPC UA server. But only the first ony will be subscribed. Is something with my publishednodes.json misconfigured?

This is my publishednodes.json:
[publishednodes.zip](https://github.com/Azure/Industrial-IoT/files/5909695/publishednodes.zip)

This is the logfile:
[publisherlogs.zip](https://github.com/Azure/Industrial-IoT/files/5909696/publisherlogs.zip)

Both OPC UA server are reacheable. If I move the second subscription in the publishednodes.json to the top, than this subscription is applied but again not the second one.

**To Reproduce**
1. Start publisher module with attached publishednodes.json
2. Observe, that only the first subscription definition is applied (see attached logfile)

**Expected behavior**
Both subscription (all) of the publishednodes.json should be applied

**Additional context**
publisher version: 2.7.199

**Additions**
- It seems to work if each subscriptions contains only few (e.g. 2) nodes.

**Comment by dacolgit** [comment]
Tested with version 2.7.199. The issue does not depend on the number of nodes in each subscription.
Ii only happens when the publisher is executed in the IoT edge context.
the following change fix also this issue:
https://github.com/Azure/Industrial-IoT/commit/3d9d503d665c1171323f4cdff52505fb5cd71c81

**Comment by derSchtefan** [comment]
@dacolgit: Was this change already merged into master, and if so, when can we expect a new Docker container on the CR with these fixes?

**Comment by oliverchristen** [comment]
@Haeavar  Could it be the same problem? https://github.com/Azure/Industrial-IoT/issues/669
This is not released yet. Should be part of v2.8.x for which no ETA is defined yet.

**Comment by koepalex** [comment]
2.8.0 was released, that should solve this issue. Please open the Issue if error still occurs.
