### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by geebinge** [Azure/Industrial-IoT#1034]
the latest version mcr.microsoft.com/iotedge/opc-publisher:latest delivers "standard_init_linux.go:211: exec user process caused "exec format error" in Docker during startup. 

Version 2.7.199 runs without problems. 

Linux RevPi40645 4.19.95-rt38-v7+ Azure/iot-edge-opc-publisher#1 SMP PREEMPT RT Tue, 16 Jun 2020 13:25:43 +0200 armv7l GNU/Linux
Docker version 3.0.13+azure, build dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
iotedge 1.0.10.4

[docker.inspect.OPCPublisher.2.7.199.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5953847/docker.inspect.OPCPublisher.2.7.199.txt)
[docker.inspect.OPCPublisher.latest.txt](https://github.com/Azure/iot-edge-opc-publisher/files/5953848/docker.inspect.OPCPublisher.latest.txt)

**Comment by marcschier** [comment]
The edge container images had a wrong architecture for arm64.  The images were republished to MCR with the correct architecture.  This was verified using `docker run --rm mplatform/mquery mcr.microsoft.com/iotedge/opc-publisher:2.7.206`.  

Can you try again?  If this still does not work, please reopen this issue for further investigation.
