### ISSUE TITLE
New-ADApplications in aad-register.ps1 can return null 

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/Industrial-IoT#1048]
**Describe the bug**
In `aad-register.ps1` the `New-ADApplications` function can return null if if the `$creds` variable has not been set.  See [this line](https://github.com/Azure/Industrial-IoT/blob/b14ebd3aa3a7464477cfb1499cfa3fabd788310e/deploy/scripts/aad-register.ps1#L230).
This null value is not checked before being piped to `ConvertTo-Json` and the script exits without an insightful warning to the user.

**Expected behavior**
A useful error is returned to the user if the collection of credentials is unsuccessful. This is partially mitigated by PR #1046

**Comment by koepalex** [comment]
@WilliamBerryiii can you describe if something is open for your issue, or this issue can be closed?

**Comment by WilliamBerryiii** [comment]
@koepalex - I believe this can now be resolved. The PR looks to be merged.
