### ISSUE TITLE
is there a way I can get node id in ns index format like ns=1;s=CycleCounter using OPCTwin Browse API

### ISSUE THREAD

**Issue by rajendrayadavgit** [Azure/Industrial-IoT#1057]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marcschier** [comment]
In 2.9.0 we are introducing "NamespaceFormat" which you can set to Index, Expanded or Uri and which relate to the non-normative section that will be added to Part 6 soon. A default can be set using the command line, individual setting can be applied in the request's "header" object.
