### ISSUE TITLE
publishednodes.json: When OpcAuthenticationUsername is set but OpcAuthenticationPassword is erroneously not, a misleading error message appears

### ISSUE THREAD

**Issue by derSchtefan** [Azure/Industrial-IoT#1059]
**Describe the bug**
When OpcAuthenticationUsername is set for an Endpoint in publishednodes.json but OpcAuthenticationPassword is erroneously not (there was a mistake in the key name on our side), a misleading error message appears:

`User/passord token format is not supported`

The message originates in class StackModelsEx methods ToUserIdentityToken and ToStackModel. 

**To Reproduce**
1. Add a publishednodes.json with an endpoint pointing to a OpcServer requiring UsernamePasswort auth with a OpcAuthenticationUsername  entry, but no OpcAuthenticationPassword entry (we had a space extra)
2. Start OPC Publisher
```json
    "EndpointUrl": "opc.tcp://xxxxx:xxxx/xxxxxxx",
    "UseSecurity": true,
    "OpcAuthenticationMode": "UsernamePassword",
    "OpcAuthenticationUsername": "xxxxx",
    "OpcAuthenticationPassword ": "password",
```

**Expected behavior**
An error message like "OpcAuthenticationPassword missing".

**Additional context**
Tested with OPC Publisher version 2.7.206.36449

**Comment by marcschier** [comment]
An empty password is legal in the UserNameIdentityToken structure in OPC UA.  In 2.9.0 we now allow an empty string as user name also as there are servers where the empty string is a valid user (like an API key scheme).
