### ISSUE TITLE
OPCPublisher: is it possible to monitor items on DataChangeTriggerType.StatusValueTimestamp ?

### ISSUE THREAD

**Issue by apittier** [Azure/Industrial-IoT#1074]
Hi!

Is it possible to monitor items on DataChangeTriggerType.StatusValueTimestamp ?

From the OPC UA Specification we have that the default behavior is to ["Report a notification if either the StatusCode or the value change. "](https://reference.opcfoundation.org/v104/Core/docs/Part4/7.17.2/) (i.e., _Microsoft.Azure.IIoT.OpcUa.Publisher.Models.DataChangeTriggerType.StatusValue_).

I was wondering if there's any mechanism available when configuring the OPCPublisher to define that we want to be notified on _SourceTimestamp_ changes also (i.e., DataChangeTriggerType.StatusValueTimestamp).

Many thanks!
Amparo

**Comment by marcschier** [comment]
Hi @apittier, unfortunately this is not implemented.  We will evaluate it for our backlog.

**Comment by apittier** [comment]
Thanks for answering.

**Comment by marcschier** [comment]
Keeping on backlog
