### ISSUE TITLE
ModuleClientAdapter is lacking Methods to handle incoming Messages

### ISSUE THREAD

**Issue by mma-mm** [Azure/Industrial-IoT#11]
Hi,

I just noticed, that ModuleClientAdapter provides methods to send events/messages to other modules/IoTHub but lacks methods to receive messages. Do you plan to provide an interface to access this ModuleClient method? If so, where? Or did i miss a way to receive messages without creating a new ModuleClient?

Regards

Matthias

**Comment by marcschier** [comment]
Hi @mma-mm, sorry for the late response, we decided to not work on this this semester.   Feel free to provide a code contribution as a pull request.
