### ISSUE TITLE
Building on Mac OS doesn't work

### ISSUE THREAD

**Issue by toddysm** [Azure/Industrial-IoT#111]
**Describe the bug**
We are trying to build the Publisher module on a Mac but it fails with tons of error. Also, we are noticing missing files in the project (particularly Dockerfile) - assuming those are part of the build process. 

Feedback: Documentation can be clearer about how to do the build and create the Docker container.

**To Reproduce**
1. Clone the project
2. Open the Solution in VS for Mac
3. Rebuild All

**Expected behavior**
The solution to build and to have Dockerfile to create the IoT Edge module.

**Screenshots**
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1007103/65276476-a6f14200-dadc-11e9-968f-0444fd01950a.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6
 - Visual Studio for Mac Community 8.2.6 (build 26) [e.g. chrome, safari]
 - Dotnet Core Version 2.2.300

**Additional context**

**Comment by marcschier** [comment]
Thanks – Indeed we regressed when it comes to being able to build containers for our modules.   This shall be fixed.   

We however do build and test on macos as part of our CI pipeline, so the build issue might be a tool or setup issue.   Can you try building using "dotnet build Industrial-IoT.sln" in a terminal?

**Comment by toddysm** [comment]
@marcschier Building manually from the console works (sorry, forgot to mention that). Is there any particular documentation on how to set up VS on Mac to do the build from there? 

Also, any documentation about the Docker container creation will be appreciated.

**Comment by marcschier** [comment]
Hi @toddysm, there should not be anything special around setting up VS for Mac beyond the official documentation.  I would suggest trying the latest 8.3 build.   What looks iffy is the errors relating to mono, maybe this is a path issue.  Unfortunately I do not have a Mac on hand and would not be able to help troubleshoot.   

Regarding publisher, yes it does not require any micro services deployed.  Publisher.md shows how to configure the publishednodes.json manually.   It can also be run outside of Edge and thus directly from command line (also documented).   There will be a build script in the tree soon that allows building the module containers.   I will leave this open to also track that.

**Comment by vjrantal** [comment]
While this may not solve the original problem, I wanted to share that I was able to run "Build All" after the opening the solution on VS for Mac version 8.3.1 (build 18).
