### ISSUE TITLE
No Endpoints found in Windows Module

### ISSUE THREAD

**Issue by jzsnd** [Azure/Industrial-IoT#1128]
Hi Experts,

I tried to bulid an IIoT data live-visulation solution based on this architecture with Azure IIoT Platform (https://github.com/Azure/Industrial-IoT) Vesion 2.7.206. I have proceesed the deployment and we can see the ressources in Azure. I have found two Assets in the engineering tool.
![Assets](https://user-images.githubusercontent.com/83342925/116399994-cf4d3080-a829-11eb-8e68-4fc17531a87f.PNG)

In Linux module we can see 3 endpoints, however no endpoints can be found in windows module.
![Deployment Endpoints](https://user-images.githubusercontent.com/83342925/116400660-9b263f80-a82a-11eb-9e7a-6dae1c7f5395.PNG)
![win  Endpoints](https://user-images.githubusercontent.com/83342925/116400634-91044100-a82a-11eb-8d7c-ad3086be9ebc.PNG)

What could be the issueand how can i fix this?

**Comment by marcschier** [comment]
Please reopen if the directions do not address the issue.
