### ISSUE TITLE
Null values shown in TSI explorer

### ISSUE THREAD

**Issue by jzsnd** [Azure/Industrial-IoT#1129]
Hi, 

I followed this tutourial: https://azure.github.io/Industrial-IoT/tutorials/tut-timeseriesinsights.html to get some basic knowledge about time series insights explorer. I got to the point where "The TSI instances models are automatically detected and display in the explorer based on the telemetry data ingested from the IIoT platform telemetry processor’s event hub." I expected something that looks like what is shown on this screenshoot:
![tut-tsi-step0](https://user-images.githubusercontent.com/83342925/116401697-d37a4d80-a82b-11eb-81c1-9046e3dd3e47.png)

However, what i can see in my TSI Explorer are three Null values, where i expected a list of my endpoints.
![TSI null,null,null](https://user-images.githubusercontent.com/83342925/116401930-19cfac80-a82c-11eb-9933-16857849dc4d.PNG)

Can anyone tell me where the problem might be and how can i fix it?

**Comment by maalliet** [comment]
In addition to what @nelsonmorais mentiones what needs to be adapted in the azuredeploy.standard.json file (starting from line 450), also the timestamp property of the input eventhub of TSI needs to be changed on line 514 with lower 's':

"timestampPropertyName": "TimeStamp"   ->    "timestampPropertyName": "Timestamp"

Currently, TSI uses the IoT Hub timestamp as it cannot find the property 'TimeStamp', which might cause issues when IoT Hub is down for a few hours
