### ISSUE TITLE
 Error Azure Account in deployment script

### ISSUE THREAD

**Issue by Distil62** [Azure/Industrial-IoT#113]
**Describe the bug**
Add-AzureAccount throw error `No subscriptions are associated with the logged in account in Azure Service Management (RDFE)`

**To Reproduce**
1. clone the project
2. execute the commande `deploy.cmd` without any args
3. log-in
4. see error

**Expected behavior**
I guess the application have to detect my subscription

**Screenshots**
![error1](https://user-images.githubusercontent.com/17656761/65413891-c8ab3b80-ddf2-11e9-84a4-77ddec870800.PNG)
![error2](https://user-images.githubusercontent.com/17656761/65413896-cba62c00-ddf2-11e9-8737-c92fe5e101bc.png)

**Desktop (please complete the following information):**
 - Windows 10 build 18362
 - Google Chrome 76

**Additional context**
I promote this account recently.

**Comment by Distil62** [comment]
I read it's a comptability error between the old and new Azure portal but i don't know how can i fix it :/

**Comment by Distil62** [comment]
I don't understand what the are required more :/

**Comment by karok2m** [comment]
@Distil62, can you please verify that you have admin permissions in your Azure account ? Currently, `deploy.cmd` requires user to be an admin in Azure account.

**Comment by marcschier** [comment]
Hi @Distil62, unfortunately we do not support deployment as user at this point.  Please have an administrator deploy.  We are currently reworking the deployment experience and will include deploying as user as a future feature.

**Comment by marcschier** [comment]
We implemented a way for a aad admin to do the AAD application registration (aad-register.ps1) and provide the created output as file to the deployment script.   We removed Add-AzureAccount, so this should also not happen anymore.   Please try again and let us know if you still hit issues.
