### ISSUE TITLE
Readme Misinformation

### ISSUE THREAD

**Issue by suneetnangia** [Azure/Industrial-IoT#1132]
**Describe the bug**
Readme mentions "and run on managed Azure Kubernetes Services (currently in preview)", this could be misleading as AKS is in GA.

**Comment by hansgschossmann** [comment]
We see on this page (https://azure.github.io/Industrial-IoT/deploy/):
Azure Kubernetes Services should be used to host the cloud micro-services (this is currently in preview, please see our documentation).

@suneetnangia is this the location you are referring to? If not, pls post a link to the page you saw this.

**Comment by suneetnangia** [comment]
Hi Hans, I saw it here https://github.com/Azure/Industrial-IoT, I am not sure why we are suggesting it's in preview as AKS is not in preview. If a correction is needed, we should also fix it at the location you specified as well.

**Comment by hansgschossmann** [comment]
@suneetnangia this is a doc bug. we brought it to the attention of the team.

**Comment by marcschier** [comment]
Fixed in linked commit.
