### ISSUE TITLE
PubSub JSON DataSetWriterId should be a UInt16, not a String

### ISSUE THREAD

**Issue by mregen** [Azure/Industrial-IoT#1148]
**Describe the bug**
In this Mantis Issue: (errata 1.04.2)

4327 | DataSetWriterId field in JSON   DataSetMessage | Changed DataType of the   DataSetWriterId in a JSON DataSetMessage from String to UInt16 to be   consistent with other definitions.
-- | -- | --

the datatype was changed from string to UInt16.

**To Reproduce**
Send PubSub JSON encoded message to cloud, value is set to string like:
"DataSetWriterId": "uat46f9f8f82fd5c1b42a7de31b5dc2c11ef418a62f",

**Expected behavior**
DatasetWriterId is a UInt16

**Additional context**
see also https://github.com/Azure/Industrial-IoT/blob/master/docs/dev-guides/telemetry-messages-format.md

**Comment by hansgschossmann** [comment]
test

**Comment by marcschier** [comment]
In 2.9.0 with --strict, DataSetWriterId is int, DataSetWriterName is string.  Without --strict old behavior applies.
