### ISSUE TITLE
The portable console seems out of date

### ISSUE THREAD

**Issue by djwinter29** [Azure/Industrial-IoT#1179]
I am trying to run:
dotnet IoTEdgeInstallerConsoleApp.dll
on ubuntu 18.04, however it failed to install iotedge because of libssl 1.0.2, after some reading, I have noticed that since iothub 1.2, it has been renamed to aziot-hub.

so there is two issues with the installation now:
1.  it is out of date aziot-edge
2. not able to install even the old version because libssl1.0.2 is obsoleted.

**Comment by hansgschossmann** [comment]
@djwinter29 the IoTEdgeInstallerConsoleApp is not longer actively maintained. Can you please use the deploy.ps1 deployment method which is maintained and documented in this repositories documentation.

Sorry for the confusion, but we have missed to remove the links to the installer in our documentation.
