### ISSUE TITLE
User authentication via certificate

### ISSUE THREAD

**Issue by JohannesM24** [Azure/Industrial-IoT#1208]
Hi,

is there any plan to add user authentication via certificate ?

Currently there is only Anonymous and UsernamePassword supported in contrast to OPC UA specifications.

https://github.com/Azure/iot-edge-opc-publisher/blob/dc6b669bcd7c45437fb1b0aacf77bfb1e98482f5/opcpublisher/OpcAuthenticationMode.cs

**Comment by marcschier** [comment]
Will be tracked in #2005.
