### ISSUE TITLE
Support automatic re-evaluating subscriptions on DataModelChange events (Dynamic information model and OPC Publisher)

### ISSUE THREAD

**Issue by fijo1015** [Azure/Industrial-IoT#1209]
Hi everyone,

I am using a dynamic OPC UA information model. What I mean by dynamic is, that in the beginning the information model contains a few nodes and some methods. By calling these methods new nodes will be created. So the information model is growing while using it. 
I'd like to know, if the OPC Publisher Module can handle nodes that are not present in the beginning. In the configuration file (publishednodes.json) i want to list some nodes that are not present in the beginning. Is OPC Publisher able to register the appearing nodes and then publish it to the IoT Hub?

Regards
jo

**Comment by marcschier** [comment]
Whatever is configured will be attempted to be added to a subscription. If the monitored item does not exist this will be re-attempted periodically.  That is the expected behavior.  Please reopen if this is not what you are seeing.
