### ISSUE TITLE
Suggestion: be able to track the active publishednodes.json file version

### ISSUE THREAD

**Issue by fbeltrao** [Azure/Industrial-IoT#1213]
In a scenario where an external component is managing the subscription items by modifying the `publishednodes.json` file it would be great to be able to track the version current in use by OPC Publisher.

A possible solution would be to add metadata to the publishednodes.json file with a version number, for example:

```json
{ 
  "versionId": "myUniqueVersionId",
  "items": [
    {
        "EndpointUrl": "opc.tcp://host.docker.internal:49322/",
        "UseSecurity": false,
        "OpcNodes": []
     }
]
``` 

Ways to report the current configuration version (not mutual exclusive):
- Header in the monitored items telemetry
- Can be retrieved using a Direct Method
- Updating the module twin reported properties

**Comment by marcschier** [comment]
The version property is now part of 2.9.0-preview4. It is incremented on every change.
