### ISSUE TITLE
How to override to send values even they are not changed?

### ISSUE THREAD

**Issue by subbu-ai** [Azure/Industrial-IoT#1216]
My OPCPublisher version is 2.7.206.  I understand the default behaviour of the OPCPublisher is send only changed values.  How to send the values even if they are not changed.

**Comment by marcschier** [comment]
Heartbeat is working 2.8.  Tracking periodic reads (not required here, but related) in #1934.

**Comment by marcschier** [comment]
In 2.9.0-preview4 we support cyclic reads, which are periodically executing read requests that return values even if they do not change. This could be a good option to support your use case.
