### ISSUE TITLE
Show number of current monitored items as part of diagnostic information

### ISSUE THREAD

**Issue by martin-weber** [Azure/Industrial-IoT#1217]
It would be helpful to show in the diagnostic information output:

- The number of currently monitored items
- (Optional) The total number of configured items
- (Optional) The number of configured items that are not monitored due to failure

This would improve the diagnostic when deploying a new configuration. It would male it much easier to check if the new configuration added / removed monitored items and compare this number of items with the count items received after IoT Hub.

Currently after changing a bigger configuration, we need to search the log file for lines like the followings:
_Added <**X<sub>monitored</sub>**> monitored items to subscription_
_Set Monitoring to Reporting for <**X<sub>configured</sub>**> nodes in subscription_
and sum up the **X<sub>configured</sub>** and **X<sub>monitored</sub>** nodes to know how many nodes are configured and how many nodes are monitored.

It would be great to see this up to date over time in the diagnostic information.

**Comment by marcschier** [comment]
Already showing good and bad nodes count in --di output since 2.8.2.  Closing complete.
