### ISSUE TITLE
Feature Request: Option to load published node configuration from module twin

### ISSUE THREAD

**Issue by oliverchristen** [Azure/Industrial-IoT#1220]
This has been [requested](https://github.com/Azure/iot-edge-opc-publisher/issues/144) some years ago and I would like to bring it up again. I think it would be much better to be able to manage the pn.json from the cloud. And it would be much easier than using the OPC Twin cloud service.
The module twin size limit of [8kb](https://docs.microsoft.com/en-us/samples/azure-samples/azure-iot-hub-large-twin-example/extend-iot-twins/#:~:text=Azure%20IoT%20Hub%20device%20twins,that%20exceeds%20the%20size%20limit.) is not a problem in most cases, isn't it?

I'm able to cloud-manage almost all the edge modules except the OPC-Publisher.

**Comment by marcschier** [comment]
We are not planning to support module twin as configuration.  Please use direct method and persisted local volume.
