### ISSUE TITLE
Dependency on SeriLog: why not use Microsoft.Extensions.Logging.Abstractions?

### ISSUE THREAD

**Issue by bald123** [Azure/Industrial-IoT#1225]
**Is your feature request related to a problem? Please describe.**
When using the API's for the twin/publisher etc, I'm pretty much forced to use the SeriLog logging framework. I'm wondering why the Microsoft.Extensions.Logging.Abstractions is not used, as it seems to me this abstraction is a bit more neutral.

**Describe the solution you'd like**
Instead of being forced to use SeriLog, I would like to use the "neutral" Microsoft.Extensions.Logging.Abstractions definitions.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by hansgschossmann** [comment]
@bald123  are you using the REST API calls or are you referring to the edge modules? Can you describe the scenario/use case in a bit more detail?
