### ISSUE TITLE
Kepserver is returning a single node value that is not encapsulated in JSON array semantics ([]) so it cannot be parsed properly

### ISSUE THREAD

**Issue by marcschier** [Azure/Industrial-IoT#129]
Kepserver is returning a single node value that is not encapsulated in JSON array semantics ([]) so it cannot be parsed properly.  Repro steps and value definition to follow.

**Comment by chrisgclayton** [comment]
OPC Pulisher telemetry format when data is sourced from Kepserver it is different than when sourced from the Connected Factory simulated UA server. The payload is encased in a square brace (array) when coming from the simulated UA server and not when coming from the Kepserver.

**Comment by marcschier** [comment]
This is related to whether batching is enabled or not.  A batch is an array, but single samples --si=0 are simple objects.
