### ISSUE TITLE
CRash when Binding Volumes

### ISSUE THREAD

**Issue by lucarv** [Azure/Industrial-IoT#130]
**Describe the bug**
I have tried to deploy the module on iot edge, from marketplace, bu adding a volume binding to where my publishnodes.json is. Edge Agent fails to start the module. See error log at https://pastebin.com/nXYZDZ72

**To Reproduce**
1. create a folder on the edge device and add a valid publishnodes.json file
2. get the module from market place, edit container create options to bind the folder where publishnodes.json is
3. publish

**Comment by marcschier** [comment]
Hi, could you also provide the create options you specified during deployment?  Thanks!
