### ISSUE TITLE
PublishedNodes.Json Schema Validation

### ISSUE THREAD

**Issue by suneetnangia** [Azure/Industrial-IoT#1301]
An invalid publishednodes.json file cause LegacyJobOrchestrator in OPC Publisher to hang without surfacing appropriate exceptions, please see the existing issue here https://github.com/Azure/Industrial-IoT/issues/1032 for more details and repro steps. 

We have been working on two prong validation approach for publishednodes.json file for OPC Publisher. 
First one, initial code changes are made in the fork here https://github.com/suneetnangia/Industrial-IoT to validate and throw meaningful exception when schema validation fails. 
Secondly, we (@WilliamBerryiii did) have also developed an independent module (not edge module) to generate JSON schema for publishednodes.json programmatically and validate publishednodes.json file outside of publisher itself. This could be useful in multiple ways i.e. where we want to validate publishednodes.json in CICD pipeline as a task, in custom scripts/cli tools or validating UI/auto generated publishednodes.json files.

We'd be keen hear your views on it and next steps to merge it upstream potentially.

CC @WilliamBerryiii @hansgschossmann @koepalex

**Comment by WilliamBerryiii** [comment]
I have migrated the tool to GitHub (with backing AzDO build/test) and you can find the repository here: https://github.com/WilliamBerryiii/opcpublisherschemavalidator

Currently, we only support the `publishednodes.json` file, but are actively developing a schema generator for the `telemetryconfiguration.json` file as well.

**Comment by marcschier** [comment]
Hi @suneetnangia, @WilliamBerryiii, this is fantastic, we would love to take a contribution and PR.

**Comment by WilliamBerryiii** [comment]
Hey @marcschier - @suneetnangia and I will work on preparing a PR and we can discuss the tooling/schema generator in that context and/or in a new issue.  Thanks!

**Comment by marcschier** [comment]
Hi @WilliamBerryiii - I looked at the PR, which looks create, but newtonsoft schema library has an incompatible license, which is a show stopper as we cannot redistribute it as part of our containers, nor is it something we want to force customers to pay.  How easy is it to replace with something under MIT or even better coming from MSFT?

**Comment by WilliamBerryiii** [comment]
@marcschier - thank you for catching this. We will investigate alternate libraries, ensure their stability and will migrate to a more redistributable-friendly package for schema validation.

**Comment by hansgschossmann** [comment]
@WilliamBerryiii have you had a chance to look into the NewtonSoft replacement?

**Comment by WilliamBerryiii** [comment]
@hansgschossmann - Yup!  We've implemented JsonSchemaDotNet as a replacement and the [PR is under review](https://github.com/Azure/Industrial-IoT/pull/1305). Thanks again for the support!

**Comment by hansgschossmann** [comment]
Thanks. I will follow up to get this reviewed.
