### ISSUE TITLE
Incorrect documentation of supported --mq command line argument for OPC Publisher v2.7 and above

### ISSUE THREAD

**Issue by michielvanschaik** [Azure/Industrial-IoT#1330]
**Describe the bug**
The current documentation at [reference-command-line-arguments](https://docs.microsoft.com/en-us/azure/industrial-iot/reference-command-line-arguments) states that the --mq (or --monitoreditemqueuecapacity) option is only available for OPC Publisher versions 2.5 and below. However, from v2.7, this option is a supported feature of OPC Publisher.

**To Reproduce**
1. Start OPC Publisher v2.7 (or above) with the --mq option.
2. The option will be accepted (does not result in an error).
3. OPC Publisher start to queue values on Monitored Items (as expected)
4. The documentation does not state that this is supported.

**Expected behavior**
The current documentation does not state that this is supported on OPC Publisher after v2.5.

**Screenshots**
See documentation link.

**Additional context**
Alexander Koepke confirmed that this is supported in OPC Publisher from v2.7, however the documentation is not updated accordingly.

**Comment by koepalex** [comment]
Also this page need to be updated: https://github.com/Azure/Industrial-IoT/blob/main/docs/modules/publisher-commandline.md
