### ISSUE TITLE
How to set queue length for OPC MonitoredItem?

### ISSUE THREAD

**Issue by BjornO95** [Azure/Industrial-IoT#1341]
Hi, From a glance at the opc ua code in the Visual Studio solution, it seems that the queue parameter is provided.
How can this parameter be set using the orchestrated installation of the OPC UA Publisher?
By default the value 1 is used and I would like to have multiple samples being sent to the cloud after each publishing interval.
When currently having set a sampling interval several times lower than the publishing interval, it only sends the last value (as queue value is defaulted to 1)

Thanks for the feedback

**Comment by koepalex** [comment]
Hi @BjornO95 it is currently not possible to set the QueueSize in the orchestrated mode of OPC Publisher.
 
@jehona-m this would be a feature request

**Comment by marcschier** [comment]
We will only support queue length though the configuration file or OPC Publisher API endpoints, orchestrated mode will be removed in 2.9.0.
