### ISSUE TITLE
Deadband support

### ISSUE THREAD

**Issue by pratson20** [Azure/Industrial-IoT#1379]
Hi,
I am looking for two major feature for customer which is not available in IIoT solution-

1. Dead-band
2.  Synchronous communication through OPC Publisher.

Can you please guide if this available or not?

Regards,
Prateek

**Comment by hansgschossmann** [comment]
@pratson20 thanks for you request. Can you provide a few more specific details on "Synchronous communciation through OPC Publisher"

**Comment by pratson20** [comment]
@hansgschossmann  Need to read bulk of OPC UA tags data at every minute. There is one option to read asynchronously that   OPC Publisher supports .
e.g I need to read 1000 tags data every one minute.

**Comment by pratson20** [comment]
Can you please if can be achieve dead-band filter in Azure OPC, Absolute and percentage dead-band?

**Comment by hansgschossmann** [comment]
This is on our backlog, but I cannot yet give you a date when this will be in the product.

**Comment by marcschier** [comment]
Dead band will be in 2.9.0 community preview which is planned to release soon.

**Comment by marcschier** [comment]
Tracking as deadband support. Please open new feature request for polling.

**Comment by marcschier** [comment]
In 2.9.0 all of datachange filter can be configured in pn.json file.  Including DeadBand value and percent/absolute.  Behavior depends on server.
