### ISSUE TITLE
Discovery Service not working with Nested Edge

### ISSUE THREAD

**Issue by lucarv** [Azure/Industrial-IoT#1387]
I have a nested edge setup where the child edge is able to scan a network and find all OPC UA servers. I can see that the scanning works correctly and telemetry is sent to IoT Hub. However, no assets are registered and therefore I can't activate and subsequently browse the Assets.
If I have a non-nested edge concurrently installed in the same network, the discovery process is able to register assets.

**Comment by hansgschossmann** [comment]
@lucarv Thank you for reporting this issue.  We do not yet support Nested Edge deployments in Industrial-IoT platform and will fix this bug when we are going to support it.

**Comment by cristipogacean** [comment]
Closing since we cannot replicate the issue. The reason for this issue seem to be the upstream connectivity in the nested edge infrastructure.  Please reopen if necessary.
