### ISSUE TITLE
Add all node configuration settings to IPublishServices

### ISSUE THREAD

**Issue by mma-mm** [Azure/Industrial-IoT#14]
Hello,

The IPublishServices are really easy to use, but lack features.
Several Node settings that the Publisher supports are not provided from the IPublishServices, such as the HeartBeatInterval.
We need to heart beat interval but would also like to stick to the IPublishServices implementations that are available from the azure-iiot-opc-ua.

Best regards
Matthias

**Comment by marcschier** [comment]
This is scheduled for the first half of this year - we are tracking this internally.
