### ISSUE TITLE
Download latest release via script

### ISSUE THREAD

**Issue by logg-sar** [Azure/Industrial-IoT#1426]
**Feature request**
I have to install Industrial-IOT on a small devices without git.
So I´m downloading the latest release unzip it and call the deploy-script

**Describe the solution you'd like**
According to https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases the latest release should be available via https://github.com/USER/PROJECT/releases/latest/download/package.zip
In this case of course https://github.com/Azure/Industrial-IoT/releases/latest/download/package.zip
This redirects to https://github.com/Azure/Industrial-IoT/releases/download/2.5.5/package.zip and says "not found"

**Additional context**
This should be an easy config-change in github(?)
Could someone in charge change the config so that the newest Industrial-IOT-Release is reachabe as described in the docs?
And please - this is the Industrial-IoT-Repository. I do expect to download the latest Industrial-IoT-release and not the bugfix for an part of the solution.....

Thank you

**Comment by marcschier** [comment]
Hi @logg-sar, we release security fixes for older releases the same way as we release them for newer, so the history in the "releases" tab is not necessarily in order, and we also release helm charts, etc.  Therefore, today the last release is a patch release of OPC Publisher 2.5.5, it might be a helm chart update tomorrow.  I am not aware of a way to change this on GitHub.  

Unfortunately, we also do not support deploying Industrial IoT platform from a copy, but you can use the IAI installer tool (which you can download which is explained [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/deploy/howto-deploy-aks.md#download-microsoftazureiiotdeployment-binaries)).
