### ISSUE TITLE
Communicate with OPC Twin Module

### ISSUE THREAD

**Issue by ahe27** [Azure/Industrial-IoT#1428]
We have some issues integrating the OPC Twin Module (not available in Marketplace) on our Edge-Device in the Azure IOT-Hub.
We installed the OPC Twin with the following settings onto our Edge-Device in out network:
<img width="172" alt="1" src="https://user-images.githubusercontent.com/92585483/137490873-277a6eb4-b7a9-492b-ae00-58c0c6c3fb49.png">
<img width="215" alt="2" src="https://user-images.githubusercontent.com/92585483/137490879-860bcd8e-56fe-430c-a162-fd70c56d8a11.png">
<img width="520" alt="3" src="https://user-images.githubusercontent.com/92585483/137490884-db94029a-e729-4cfa-ae26-3df8d93b40c8.png">
<img width="521" alt="4" src="https://user-images.githubusercontent.com/92585483/137490888-6c0ebe8b-1aee-4998-8d83-61243e29b997.png">

As you can see in the screenshot the OPC Twin module is online and running.

Unfortunately we do not know how to communicate with the REST-API of the OPC Twin and the OPC Publisher:

- Do we need further services besides the IOT-Hub that the communication is possible? 
- Is the OPC Twin fully configured or are we missing something? 
- To which address do we have to send our API calls to communicate with our OPC UA device (Beckhoff 9160)?

**Comment by marcschier** [comment]
Hi @ahe27, to communicate with the OPC Twin you need to deploy the cloud services (incl. OPC Twin services), which then expose the REST API's allowing you to communicate with the devices behind the edge gateway (running OPC Twin module). This is documented here: https://github.com/Azure/Industrial-IoT/blob/main/docs/deploy/readme.md. The engineering tool provides a good sample application that is simple enough to understand the twin and publisher APIs, furthermore there is a postman tutorial that might provide additional help: https://github.com/Azure/Industrial-IoT/blob/main/docs/tutorials/tut-use-postman.md.

**Comment by hansgschossmann** [comment]
Since OPC Twin is not a standalone offering it is not recommended that customers are using it standalone. It is integrated part of the Industrial-IoT Platform. If you do not want to deploy the full platform, you need to wait till we offer a standalone “OPC Twin like” interface at the edge or do it at your own risk since this is not a supported scenario.

Closing this issue for now. Please reactivate if you have further inquiries.

**Comment by marcschier** [comment]
In OPC Publisher 2.9.0-preview4 we added OPC Twin into the OPC Publisher. The OPC Twin API is now accessible through documented direct methods (see ./docs/opc-publisher/readme.md for more information).
