### ISSUE TITLE
Update opcpublisher configuration without reconnect

### ISSUE THREAD

**Issue by JCrezelius** [Azure/Industrial-IoT#1438]
**Is your feature request related to a problem? Please describe.**
When updating the configuration of opcpublisher using either the configuration file or direct method opcpublisher is reconnecting all configured OPC nodes, even if only a subset of the configured nodes was changed.
This reconnect can cause unintended data loss of all OPC nodes, due to restart / reconnection time.

**Describe the solution you'd like**
Configuration of opcpublisher can be modified at runtime without restarting / reconnecting unchanged OPC nodes. Two scenarios are affected of the reconnect:
- *Adding* additional OPC nodes for the same endpoint or a different endpoint (in case 2+ servers are connected using the same opcpublisher). 
- *Modification* of nodes (SamplingInterval, PublishingInterval) which are already part of the current active configuration should be possible without reconnecting modified nodes.

**Describe alternatives you've considered**
Different configuration methods were considered, neither configuration via *configuration files* nor *direct methods* enable configuration updateds without a reconnect.
Investigation was supported by @vslepakov.

**Additional context**
opc-publisher:2.8 was used, while observing the described behavior.

**Comment by vslepakov** [comment]
@karok2m @marcschier

**Comment by hansgschossmann** [comment]
@JCrezelius we are planning to address this in the next version.

**Comment by cristipogacean** [comment]
fixed with https://github.com/Azure/Industrial-IoT/pull/1545
