### ISSUE TITLE
Missing info on JSON payload

### ISSUE THREAD

**Issue by lucarv** [Azure/Industrial-IoT#144]
https://github.com/Azure/Industrial-IoT/blob/master/docs/modules/publisher.md in the telemetry format section explains that **"ApplicationUri": "urn:myopcserver"** is sent as part of the default payload if no special config file is defined with --tc flag.
This is what I am getting:
 ```
[IoTHubMonitor] [11:00:42 AM] Message received from [edgeVM4opcua/OPCPublisher]:
{
  "NodeId": "ns=1;s=freemem",
  "DisplayName": "Available RAM",
  "Value": {
    "Value": 6306189312,
    "SourceTimestamp": "2019-11-03T10:00:39.5083379Z"
  }
}
```

**Comment by markusstuhler** [comment]
Hi @lucarv,

that's correct, the ApplicationUri is set as being sent with default settings. Can you share the command line parameters and the version of the publisher that you are running?

Thanks!
Markus

**Comment by lucarv** [comment]
I am using the default parameters that came with the version in the marketolace

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by markusstuhler** [comment]
I couldn't reproduce this on my end. Please try if the issue persists with the latest version and reopen if so.

Thanks!
Markus
