### ISSUE TITLE
Error setting modules when deploying Microsoft OPC Publisher - Standalone Mode

### ISSUE THREAD

**Issue by MarekLani** [Azure/Industrial-IoT#1446]
**Describe the bug**
I am trying to deploy OPC Publisher module from marketplace, while creating new edge device in the process and once I hit the step, where iot edge device modules settings should be prefilled I am getting following error: 
Unable to initialize form due to unexpected error. You can proceed with new deployment settings or close the form.

**To Reproduce**
See above

**Expected behavior**
IoT Edge device creation should proceed with prefilled module settings

**Screenshots**
![image](https://user-images.githubusercontent.com/5756053/139647410-bb64f553-a8ec-4386-8025-67663386472d.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by cristipogacean** [comment]
@MarekLani, I just unsuccessfully tried to replicate your issue. In my IoT Hub (deployed in West Europe) adding a new iotEdge device and attaching the opc publisher module in Azure Portal work just fine.

Can you check the health state of your IoT Hub (e.g. quotas not exceeded, if the user has sufficient access rights, etc).  

If this does not help, please provide us more details to be able to replicate the issue e.g. which region your IoTHub is, what pricing tier/sku are you using, are you using Azure Portal or something else to edit/deploy your iotedge's deployment manfest, etc.
