### ISSUE TITLE
Log Analytics location is  deployed to Southeast Asia when chosing North Europe

### ISSUE THREAD

**Issue by mmdfe** [Azure/Industrial-IoT#145]
**Describe the bug**
The Log analytics component is deployed to Southeast Asia even if north Europe is chosen as location.

**To Reproduce**
Deploy IIot components, choose north Europe as location.

**Expected behavior**
All components should be deployed to north Europe.

**Screenshots**
![image](https://user-images.githubusercontent.com/47781138/68189961-bfde8580-ffac-11e9-9e88-7dd8ebf87aa1.png)

**Comment by monikavar** [comment]
Issue has been fixed now. Closing it.
