### ISSUE TITLE
OPC Publisher and  REST API alone deployment

### ISSUE THREAD

**Issue by felixmondelo** [Azure/Industrial-IoT#1470]
**Describe the bug**

We want to deploy only the OPC Publisher edge module and the Publisher REST API, but we don't know how to deploy it alone without deploying all the infrastructure.

How to deploy and configure the edge module and the API Rest to connect each other.

Any documentation for deploying individual parts and configuring?

There is documentation about using the OPC Publisher module in standalone mode, but I don't see any about the orchestrated mode.

**Comment by cristipogacean** [comment]
OPC Publisher module in orchestrated mode requires the cloud based IIoT services infrastructure. It is dependent on the discovery and opc twin edge modules modules. You can find detailed documentation on the services and resources required in the [operations manual](https://github.com/Azure/Industrial-IoT/blob/main/docs/manual/readme.md)
