### ISSUE TITLE
Azure Industrial IoT Gateway Installer

### ISSUE THREAD

**Issue by ChenCheng368** [Azure/Industrial-IoT#1482]
**Describe the bug**
The issue observed: The installer execution will cause the azure edge VM network failure, and to fix it I will need to manually clean up the Ubuntu changelog file via $sudo truncate -s 0 /var/lib/ubuntu-release-upgrader/release-upgrade-available, and the modules will be deployed.
 
However the deployed edge runtime version is v1.1, not the latest v1.2. and the installer is using dotnet SDK version 3.1 only. Could the develop team help to upgrade the installer for the up-to-date module deployment?

**Desktop (please complete the following information):**
 - Azure VM as the edge gateway
 - OS: Linux Ubuntu 18.04LTS

**Comment by hansgschossmann** [comment]
I am sorry to inform you that the Azure Industrial IoT Gateway Installer is no longer supported by our team. We recommend instead using the [documentation](https://github.com/Azure/Industrial-IoT/blob/main/docs/deploy/howto-install-iot-edge.md) in this github repo.
