### ISSUE TITLE
Use existing iot-Hub for iiot deployment

### ISSUE THREAD

**Issue by Padu98** [Azure/Industrial-IoT#1503]
I recently deployed the Industrial-IoT Platform and its components with the deployment script. I now want to use a diffrent IoT-hub (free tier) and delete the autogenerated one. How can i connect the opc-cloud microservices and the engineering tool after those steps to my new IoT-hub. And if that is not possible, is there any way to use an existing IoT-Hub in the deployment script?

**Comment by cristipogacean** [comment]
The parameters for of the various Azure resources in the the iiot deployment are stored in the deployment's key-vault. If you want to use a different IoT Hub, you need to change a couple of secrets in this key-vault: pcs-iothub-connstring and pcs-iothub-eventhubendpoint to point to the new IoT Hub connection string respective endpoint. Also make sure the new IoTHub has the following consumer groups defined: 
![image](https://user-images.githubusercontent.com/14314727/146941478-569fdb37-4eb0-4e92-9a8d-5dfe69699809.png)

Unfortunately there is not much documentation, but I hope the info above will help.

**Comment by cristipogacean** [comment]
Closing for now. Please reopen if needed.
