### ISSUE TITLE
Publisher job canceled. 

### ISSUE THREAD

**Issue by mwiot** [Azure/Industrial-IoT#1517]
Hi,

We recently ran into a problem on an edge machine publishing data to azure. 
After moving the cloud services and engtool to a different app service plan, the publishers managed to connect to the new app services. But on one of the installations, the job status was set to canceled. 

Endpoint that is still working after change:

```
"DesiredActiveAgents": 1,
"DesiredPassiveAgents": 0,
"Status": "Active",
```
Endpoint that is not working after change:

```
"DesiredActiveAgents": 1,
"DesiredPassiveAgents": 0,
"Status": "Canceled",
```
I then used the rest api to restart the job for the endpoint that was canceled. That worked. 

What is causing jobs to be canceled in general?
I cannot find information regarding this. 

Best regards.

**Comment by marcschier** [comment]
Worker/orchestrator is going away, because of that we are not planning any fixes in this area.
