### ISSUE TITLE
deployment "killed" and bash does not response

### ISSUE THREAD

**Issue by linexc** [Azure/Industrial-IoT#1528]
**Describe the bug**
I am trying building a connection between OPC UA and Azure and thereofore use the tutorial from [Ingesting OPC UA data with Azure Digital Twins](https://docs.microsoft.com/en-us/azure/digital-twins/how-to-ingest-opcua-data?tabs=portal). When I followed the tutorial step by step until starting the deployment. Since it is on Ubuntu 18, I gave the command **./deploy.sh**. But after I specified the name for my application, the bash crashed automatically after several seconds. 
Of course I have already two virtual systems. 

![grafik](https://user-images.githubusercontent.com/37276446/150659446-402d45c3-184d-4592-a236-f884c1519aa6.png)
![grafik](https://user-images.githubusercontent.com/37276446/150659579-03a6b9a1-d37a-4872-bb1e-8f50e10b740a.png)
![grafik](https://user-images.githubusercontent.com/37276446/150659583-7409e5d4-7e26-4ed2-9971-1ed8c4bafc0c.png)

**To Reproduce**
1. cd Industrial-IoT
2. Input my actual existing resource group name
3. Inpout test as an application name 
4. Hit enter.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/37276446/150659311-093cbc1a-656d-46a2-8fcc-095a700c2ad8.png)

**Additional context**

**Comment by hansgschossmann** [comment]
@linexc using deploy.sh from this repository is most likely installing much more than you are expecting. this will install the full Industrial-IoT platform which includes a bunch of microservices and is not what is described [here](https://docs.microsoft.com/en-us/azure/digital-twins/how-to-ingest-opcua-data?tabs=portal).

The best description of how to deploy OPC Publisher in standalone mode can be found [here](https://docs.microsoft.com/en-us/azure/industrial-iot/tutorial-publisher-deploy-opc-publisher-standalone).

Please let us know if this solves your problem.

**Comment by hansgschossmann** [comment]
@linexc  were my comments above helpful in any way?

**Comment by hansgschossmann** [comment]
@linexc pls reactivate if you still have questions.
