### ISSUE TITLE
Support OPC UA Historical Access implemented?

### ISSUE THREAD

**Issue by mpaxh** [Azure/Industrial-IoT#1548]
Does OPC Publisher support part 11 (Historical Access) of the opc ua specification? The documentation does not detail which release / parts of the opc ua specification are implemented. If yes, an example would be great.

**Comment by cristipogacean** [comment]
OPC UA Historical Access is out of the scope of OPC Publisher. HA is integrated in the OPC Twin module and can only be used together with the IIoT platform microservices.

**Comment by Haeavar** [comment]
Hi @cristipogacean 
Since the IIoT platform microservices will be discontinued. Are there any plans to support HA in the future? Do you have any detailed information about HA and the IIoT platform microservices?

**Comment by hansgschossmann** [comment]
@Haeavar i am interested to understand your use case for HA in more detail. Can you share those here?

**Comment by mpaxh** [comment]
@hansgschossmann If the connection to the opc ua server is interrupted for whatever reason (e.g. network not available) a gap in the collected data by OPCPublisher results. However, typically the system on which the opc ua server runs stores the data for some period of time. HA could be a way to backfill the gaps in the data once the connection to the OPC UA server is restored.

**Comment by hansgschossmann** [comment]
@mpaxh thank you for your feedback. we are also discussing to support enabling queue size on MonitoredItems. Would this be enough for you? HA would definitely provide data for longer dropouts if the server supports it.

**Comment by mpaxh** [comment]
@hansgschossmann Not sure, what would the max queue size be? We would like to be able to backfill at least 5 days, for around 20k variables per server with the fastest variables sampling at 1 Hz. More than 5 days are welcome, that would make fixing the connection problem a bit more relaxed ;)
For reference, our servers provide the full history for 13 weeks.

**Comment by hansgschossmann** [comment]
@mpaxh Queuesize is most likely too small for 5 days. As @cristipogacean pointed out in his first answer this is a feature which would require to use the full Industial-IoT platform (including microservices) and using the OPC Twin REST API to access HA data.

**Comment by mpaxh** [comment]
@hansgschossmann @cristipogacean ok, since the iiot platform microservices will be discontinued, what is the solution for HA then?

**Comment by hansgschossmann** [comment]
@mpaxh i am tagging this as feature request for OPC Publisher and will follow-up internally with the team.

**Comment by Haeavar** [comment]
> @Haeavar i am interested to understand your use case for HA in more detail. Can you share those here?

@hansgschossmann To safe costs and bandwidth, we want to send historical opcua data via file transfer to the cloud and only a few most important nodes via OpcPublisher live stream.

**Comment by hansgschossmann** [comment]
@Haeavar then you would pull the HA data from the server in your custom module which is doing the file upload when you are missing some datapoints?

**Comment by marcschier** [comment]
OPC Publisher 2.9.0 preview 2 has HDA API in preview, documentation will be provided later but using the openapi.json file in the opc-publisher docs folder it one could piece it together.  This is preview mode and only supported though GitHub issues.
