### ISSUE TITLE
Script is not compatible with your computer

### ISSUE THREAD

**Issue by rploeg** [Azure/Industrial-IoT#1640]
I have installed Industrial IoT solution before, but on a new tenant I want to install the environment with the standard deployment script.  But when the registration of AAD begins, I get this error:

![2022-03-21_15-42-12](https://user-images.githubusercontent.com/49752333/159285619-496eee82-93f6-43cf-bfd1-41cce6084748.png)

The user is owner of the subscription and is global administrator of AAD. I am running on Windows 11, latest bits and running AZ CLI 2.34.1

**Comment by hansgschossmann** [comment]
@karok2m do you have an idea what can be the reason for this issue? @rploeg which version of the deployment script have you used or does "latest bits" mean HEAD of main?

**Comment by rploeg** [comment]
The version of two days ago --> main. I have tried it on another Windows 11 machine and there it was working. So it looks like a problem on one of my machines.
