### ISSUE TITLE
Azure Data Explorer - where is it used for? 

### ISSUE THREAD

**Issue by rploeg** [Azure/Industrial-IoT#1648]
I see that Azure Data Explorer is provisioned in the main deployment script. In the architecture sketches I don't see that back yet. Will you move the functions of TSI to Azure Data Explorer?

**Comment by hansgschossmann** [comment]
@marcschier can you pls answer this one?

**Comment by marcschier** [comment]
We recommend to move to Azure Data Explorer (ADX), but the work to move the platform to use ADX instead/in addition to TSI is not part of our plans for 2.8.  Therefore we are likely going to remove ADX and TSI from the sample deployment templates for in a future patch release.

**Comment by rploeg** [comment]
thanks!
