### ISSUE TITLE
Physical edge deployment with OPC UA server don't get data into the platform

### ISSUE THREAD

**Issue by rploeg** [Azure/Industrial-IoT#1649]
Hi,

I am running the main 2.81 build and deployed the environment. I have setup a own Azure IoT Edge device (physical) and a OPC UA server. I successfully discovered the server and turned on the nodes:

![image](https://user-images.githubusercontent.com/49752333/159707172-51ea8049-8fee-44b1-9ebc-ad009089c5f9.png)

The nodes are published:

![image](https://user-images.githubusercontent.com/49752333/159712960-f61317ea-d4ae-49d5-b9b8-7f621eadb753.png)

The data is flowing into the Azure IoT Hub:

![image](https://user-images.githubusercontent.com/49752333/159707276-1e8f7f88-8b47-4236-a60e-befd9645f1c2.png)

When I use Azure IoT Explorer to see the messages, I don't see any node information flowing in. 

When I see the logs of the publisher module I see this:

![image](https://user-images.githubusercontent.com/49752333/159713500-165bfead-ab0b-4c88-b38e-94e1a2b28803.png)

The strange thing is that the discovery works, but it looks like getting the data from the publisher module doesnt' work. Any idea what can be wrong? I am using the Prosys OPC UA Simulation server (firewall ets are off) and anonymous authentication is on.

**Comment by hansgschossmann** [comment]
@rploeg as you can see the issue is because of the following error:
"Endpöoint deos not support the user identity type provided"
So it is because the OPC UA server does not support the user auth which is configured.

@dacolgit can you pls describe which user auth is supported by the Engineering tool?

**Comment by dacolgit** [comment]
Engineering tool supports anonymous and username/password user authentication.
By default it uses anonymous authentication.
To use username/password you need to select 'Asset login' and add username and password.
![image](https://user-images.githubusercontent.com/7942439/159967915-637402e6-af71-496b-a1f4-4897368f4285.png)
Credentials are globally defined for all the assets (servers), currently is not possible to define a user per asset.

**Comment by rploeg** [comment]
My server is anonymous so that should work. The discovery is working, but the publisher not. What can be wrong ?

I am running also the simulator from the branch, that one is successfully working, so it's my OPv server
________________________________

**Comment by hansgschossmann** [comment]
Do you see any logs on the OPC UA server side? They might give you an idea what is wrong? You can also check if changing the security policy/mode has some impact.

**Comment by karok2m** [comment]
@rploeg, can you please restart the OPC Publisher and collect the logs from the beginning ? Having a bit more logs might give us a clearer picture. Having a [support bundle](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#gather-debug-information-with-support-bundle-command) from the IoT Edge device might be even better.

**Comment by hansgschossmann** [comment]
@rploeg  there was not response on this for quite a while. closing for now. please reactivate if the issue is still there.
