### ISSUE TITLE
Azure IoT Edge OPC publisher Module Not sending the defined parameters  

### ISSUE THREAD

**Issue by A-DavidJeyapaul** [Azure/Industrial-IoT#1654]
Hi Team,

We are using IoT Edge OPC publisher Module to publish the data from our OPC server to IoT hub. Initially it was sending the data with the below schema.
<img width="310" alt="image" src="https://user-images.githubusercontent.com/101577249/160072263-adb7226b-25ee-4593-91f8-78fca1f70f64.png">

And Now its not updated to as per the below one.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/101577249/160072104-af5322dd-1031-46c7-8387-71cfb81982d6.png">

The difference between both of the schema is **ApplicationUri**  and **EndpointUrl**

We have multiple OPC servers and we are segregating the data based on OPC servers in Azure Stream Analytics Jobs. Since this was updated, our data segregation is gets affected and none of the data is getting processed by our Job.

_Thanks in advance for your support_.

**Comment by cristipogacean** [comment]
@A-DavidJeyapaul, that's right, we fixed a regression in 2.8.2 related to the EdnpointUrl that leads to this behavior. If you need the ApplicationUri, you can get that adding a cli argument: --FullFeaturedMessage=true (--fm=true). This will add the application uri to the message as well. more details on the telemetry payload [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/dev-guides/telemetry-messages-format.md#standalone-publisher-mode---legacy).

**Comment by A-DavidJeyapaul** [comment]
Thanks for your support @cristipogacean and apologize for delayed response.
