### ISSUE TITLE
Data publish frequency

### ISSUE THREAD

**Issue by Ilheu** [Azure/Industrial-IoT#1657]
**I'm trying to publish data with the same frequency (every 1 second or every 100 milliseconds or every 200 milliseconds). I need to send data even it doesn't change. So I tried to use heartbeat feature it doe not work properly.**

I tried to set  "--hb=10" in Container Create Options, but it does not send the data every 10 seconds,
I tried to set  ""HeartbeatInterval": 10," in every node but also does not send every 10 seconds.

**I also want to ask what is the minimum value of heartbeat?**

**Comment by cristipogacean** [comment]
There is no minimum value for heartbeat.

Please note though the --hb/heartbeatinterval are expressed in seconds. if you want to use milliseconds, you need to use  --DefaultHeartbeatInterval instead (e.g. `--DefaultHeartbeatInterval=00:00:00.200`) 

We recommend that the HeartbeatInterval is a multiple of PublishingInterval. Please take in the consideration also proper configuration of the SamplingInterval respectively QueueSize for your application.

Could you please provide more details on your issue? I just tested heartbeat on 2.8.2 and everything works as expected.

**Comment by Ilheu** [comment]
I'm using version 2.8.2.1. 
If the HeartBeatInterval is a multiple of PublishingInterval, it will double a message right? (if heartbeat sends every 1 seconds and PublishingInterval sends every 500 milliseconds, I will receive the same data twice every second).

Another question, can I only use heartbeat without PublishingInterval and SamplingInterval?  I only want to get one value per timestamp...

**Comment by cristipogacean** [comment]
Yes, when HeartBeat is enabled, the most recent data-change will be resent with the HeartbeatInterval cycle if the value is static.

If you don't specify publishing or sampling intervals, the default value will be used (1000ms for both).

**Comment by hansgschossmann** [comment]
@Ilheu looks like @cristipogacean answered your questions. We close this one for now. Please reactivate or open an new issue.

**Comment by marcschier** [comment]
In 2.9.0-preview4 we added UseCyclicRead option to read at interval even if data is not changing. If you use OPC Publisher 2.9 please let us know your feedback on this requested feature.
