### ISSUE TITLE
Breaking Change in OPC Publisher 2.8.2 "An item with the same key has already been added"

### ISSUE THREAD

**Issue by felixmondelo** [Azure/Industrial-IoT#1658]
**Describe the bug**
If we have a duplicated node on publishednodes.json file, the OPCPublisher stops processing the rest of the nodes. In the previous version it doesn't happen, the OPCPublisher continues working.

**To Reproduce**
1. Add in publishednodes.json two nodes with the same ID and a third different node.
2. Launch the OPCPublisher, it doesn't subscribe to any node.

**Expected behavior**
Instead of stopping processing all the OPC nodes, ignore duplicate nodes and continue working.

**Desktop (please complete the following information):**
 - OS: Ubuntu/Windows

**Additional context**
The exact stacktrace:
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.DataFlowProcessingEngine -> Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Engine.WriterGroupMessageTrigger.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Azure.IIoT.OpcUa.Publisher.IWriterGroupConfig, Microsoft.Azure.IIoT.OpcUa.Protocol.ISubscriptionManager, Serilog.ILogger, Microsoft.Azure.IIoT.Serializers.IJsonSerializer)' on type 'WriterGroupMessageTrigger'.
 ---> System.ArgumentException: An item with the same key has already been added. Key: **DUPLICATED NODE ID**

**Comment by hansgschossmann** [comment]
@cristipogacean, @karok2m can you pls take a look at this issue?

**Comment by karok2m** [comment]
@felixmondelo, can you please add your sample `publishednodes.json` file here ?

**Comment by cristipogacean** [comment]
@felixmondelo, indeed, it seems to be a regression. I can replicate this.

**Comment by felixmondelo** [comment]
@karok2m here is a sample:

```json
[
    {
        "EndpointUrl": "opc.tcp://10.0.0.1:59412",
        "UseSecurity": false,
        "OpcAuthenticationMode": "UsernamePassword",
        "OpcAuthenticationUsername": "user",
        "OpcAuthenticationPassword": "passwd",
        "OpcNodes": [
            {
                "Id": "ns=2;s=Variable1.Line1.Power",
                "DisplayName": "Variable1_Power",
                "OpcSamplingInterval": 60000,
                "OpcPublishingInterval": 60000,
                "HeartbeatInterval": 3343,
                "SkipFirst": false
            },
            {
                "Id": "ns=2;s=Variable1.Line1.Speed",
                "DisplayName": "Variable1_Line1_Speed",
                "OpcSamplingInterval": 900000,
                "OpcPublishingInterval": 900000,
                "HeartbeatInterval": 3465,
                "SkipFirst": false
            },
            {
                "Id": "ns=2;s=Variable1.Line1.Power",
                "DisplayName": "Variable1_Line1_Power",
                "OpcSamplingInterval": 60000,
                "OpcPublishingInterval": 60000,
                "HeartbeatInterval": 3343,
                "SkipFirst": false
            }
        ]
    }
]
```

**Comment by karok2m** [comment]
@felixmondelo, the intent here is to get the value of the same node twice with different names, right ?

**Comment by cristipogacean** [comment]
@felixmondelo, indeed, as I mentioned above, this configuration file is causing an issue with the publisher. This is a bug and we will work on it. 

you can alternatively use the following configuration that will achieve the same result as per version 2,8,1

```json
[
    {
        "EndpointUrl": "opc.tcp://10.0.0.1:59412",
        "UseSecurity": false,
        "OpcAuthenticationMode": "UsernamePassword",
        "OpcAuthenticationUsername": "user",
        "OpcAuthenticationPassword": "passwd",
        "DataSetWriterId": "Variable1",
        "OpcNodes": [
            {
                "Id": "ns=2;s=Variable1.Line1.Power",
                "DisplayName": "Variable1_Power",
                "OpcSamplingInterval": 60000,
                "OpcPublishingInterval": 60000,
                "HeartbeatInterval": 3343,
                "SkipFirst": false
            }
        ]
    },
    {
        "EndpointUrl": "opc.tcp://10.0.0.1:59412",
        "UseSecurity": false,
        "OpcAuthenticationMode": "UsernamePassword",
        "OpcAuthenticationUsername": "user",
        "OpcAuthenticationPassword": "passwd",
        "DataSetWriterId": "Variable1_Line1",
        "OpcNodes": [
            {
                "Id": "ns=2;s=Variable1.Line1.Speed",
                "DisplayName": "Variable1_Line1_Speed",
                "OpcSamplingInterval": 900000,
                "OpcPublishingInterval": 900000,
                "HeartbeatInterval": 3465,
                "SkipFirst": false
            },
            {
                "Id": "ns=2;s=Variable1.Line1.Power",
                "DisplayName": "Variable1_Line1_Power",
                "OpcSamplingInterval": 60000,
                "OpcPublishingInterval": 60000,
                "HeartbeatInterval": 3343,
                "SkipFirst": false
            }
        ]
    }
]
```

Here we used the DataSetWriterId to group the nodes in a separate subscription on the OPC UA Server. This allows duplication of nodeId's.
For details on how the attributes in the pn.json create sessions and subscriptions in the OPC UA server please have a look [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/modules/publisher-directmethods.md#payload-schema).

**Comment by b-enigma-con** [comment]
Is it correct that this published nodes schema does not work anymore in v2.8.3? I'm not able to supply a json array as mentioned above using the direct methods "PublishNodes" and "PublishNodes_V1". I receive a HTTP 500. Sending a single endpoint works as intended. I did a test with copy pasting the exact JSON as mentioned above using the direct method but to no avail... (http 500).

The reason I tried is because the original problem is still present in v2.8.3 of the OPC Publisher. My solution for now is to call the direct method multiple times, one time for each "dataset". This seems to be working, but is not very elegant. Is there a better solution in v2.8.3?

**Comment by cristipogacean** [comment]
@b-enigma-con, PubishNodes_V1 only allows configuring a single endpoint per call. If you need to add more endpoints at the same time, check if [AddOrUpdateEndpoints_V1](https://github.com/Azure/Industrial-IoT/blob/main/docs/modules/publisher-directmethods.md#addorupdateendpoints_v1) is a better fit.

**Comment by marcschier** [comment]
I added a test for the first input json and it works in 2.8.4.
