### ISSUE TITLE
Full Precision Float/Double Serializer

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/Industrial-IoT#1709]
**Is your feature request related to a problem? Please describe.**
If opc server has float value of higher precision e.g. 47.446998596191406f, the current opc publisher writes 47.447 as json result. I assume this is for JamesNK/Newtonsoft.Json#2540. This makes it _appear_ like this opc publisher is losing precision.

**Describe the solution you'd like**
Either of option 1 or 2. A fiddle for the [example](https://dotnetfiddle.net/LVV1we) serializer. 
1. An environmental variable named FULLPRECISIONFLOATDOUBLE, which adds full precision functionality to existing json serializer used in this project. 
2. In [pn.json](https://github.com/Azure/Industrial-IoT/blob/main/docs/modules/publisher-migrationpath.md#configuration-file-pnjson), add a new boolean parameter as below, which add full precision functionality to existing json serializer used in this project. 

```json
[
  {
    "EndpointUrl": "string",
    "fullprecisionfloatdouble": true
  }
] 
```

**Describe alternatives you've considered**
Fix in NewtonSoft.Json. But that will break compatability of existing Newtonsoft.Json clients.

**Additional context**
This ofcourse has the consequence that 1.9 in opc server will be serialised as 1.8999999, but that is exactly the need of the user providing _fullprecisionfloatdouble_ parameter.

**Comment by marcschier** [comment]
#1670

**Comment by kiran-pradeep-palakkappilil** [comment]
@cristipogacean is the pr #1711 abandoned ?

**Comment by cristipogacean** [comment]
@kiran-pradeep-palakkappilil, yes, we decided to put this on-hold for the moment. The attempt I started here, to fix the encoding of floats and doubles throughout all the IIoT platform, is very likely to cause too much trouble through breaking changes so we need to take a step back and look for an alternative.

**Comment by marcschier** [comment]
Thanks to the simplification in 2.9 of the entire codebase we will now use G9 and G17 to roundtrip double/float from OPC UA (JsonEncoderEx).  Please note that in JSON we use the official 64bit double and 32 bit float string encoding then.  This does not mean you get mathematical string representation, but that if you parse the double/float in the JSON you get the original value back.  If your server has values with precision beyond IEEE754 double then the server should expose the value as string or "decimal" variant (the latter is something that almost no OPC UA clients support though).
