### ISSUE TITLE
listKeys(variables('storageResourceId') inside ARM template is throwing exception

### ISSUE THREAD

**Issue by VikasJaiswal** [Azure/Industrial-IoT#1720]
I am trying to deploy the solution but my organisation has set a policy named "deny-storage-allowall" on creation of storage account  due to which deployment failed. To overcome, I have modified the "deploy.minimum.json" ARM template to meet the organisation policy and enabled public network access of the storage account only from selected virtual networks and IP addresses. Then I have kept all the ARM templates inside another storage account container and pointed my deployment to the templates kept in this container instead of default github location. 
Now the storage account is getting created but IoTHub is not getting created because the required storage account connection is not getting resolved for the storageEndpoints. Mainly the method listKeys(variables('storageResourceId') is getting failed. 
Ple let me know how I can access the keys of storage account with limited network access from the ARM.

 - Tool : windows powershell

**Comment by karok2m** [comment]
@VikasJaiswal, can you please share the error message that you are getting ? `listKeys(variables('storageResourceId'), ...)` function in question here is trying to get Access Keys of a storage account to build a connection string based on that. That is then used for setting `storageEndpoints` details of IoT Hub. Please make sure that the service principal (I am guessing that this will be your user if you started the deployment locally using your credentials) that is used for the deployment of the platform is actually allowed to fetch Access Keys of the storage account that you've pointed it to.

**Comment by hansgschossmann** [comment]
There was no further discussion on this topic for quite a while. Closing for now. @VikasJaiswal please reactivate if you need further help.
