### ISSUE TITLE
OPC Twin Module in IoT Edge StandAlone

### ISSUE THREAD

**Issue by albandrod** [Azure/Industrial-IoT#1726]
Hi, I'm just developed an IoT Solution where I have deployed the IoT Edge with OPC Publisher module in standalone mode. Now, what I need is to write some information back to the OPC Server, I now I can do this with the OPC Twin module, I already deployed it in the Edge:

![image](https://user-images.githubusercontent.com/39189511/171020196-8e50a6bd-b977-44c1-a4a4-6ffb971ffdb1.png)

But now, i do not know how I can write information to the OPC node, I tried with Direct Methods, I have been reviewing the information from POSTMAN, but I do not know which information do I need to provide

https://github.com/Azure/Industrial-IoT/blob/main/docs/services/twin.md
https://github.com/Azure/Industrial-IoT/blob/main/docs/api/twin/readme.md

Can someone assist me? or do i need to deploy the industrial IoT solution to this purpose, because the rest of the system has already been deployed and working, if it's possible i do not want to undone the work that has already been done.

Thanks!

**Comment by karok2m** [comment]
@albandrod, OPC Twin module is generally supposed to be deployed together with the full IIoT platform. That includes several microservices that run in Azure and communicate with OPC Publisher and OPC Twin modules. The Postman that you are referring to is actually APIs of the OPC Twin Microservice running in cloud. The REST calls against it are then communicated down to OPC Twin module. Please have a look at our [deployment](https://github.com/Azure/Industrial-IoT/blob/main/docs/deploy/readme.md) docs to see which of full platform deployment options would work best for you. The Direct Method APIs of OPC Twin are unfortunately not documented anywhere. At the moment you can only have a look at the code to get them.

**Comment by hansgschossmann** [comment]
@albandrod as our documentation states: https://docs.microsoft.com/en-us/azure/industrial-iot/overview-what-is-industrial-iot the OPC Twin module running standalone is an unsupported scenario.

**Comment by hansgschossmann** [comment]
Closing this issue.

**Comment by marcschier** [comment]
OPC Publisher 2.9.0-preview4 contains OPC Twin and supports writing back to the OPC UA server using direct method API. This is documented under ./docs/opc-publisher/readme.md. Please let us know if this worked for you.
