### ISSUE TITLE
OPC publisher failures with IoT edge streaming service 

### ISSUE THREAD

**Issue by daelsala** [Azure/Industrial-IoT#1737]
**Describe the bug**
We have a customer who has data flowing from OPC Publisher to AzureSQLEdge, and the data stopped flowing on Fri, May 27, 2022, 12:00 AM (UTC-06:00) Central Time (US & Canada). After digging for a while we found that the streaming status got stuck in starting.

Looking through the support bundle logs with the iot edge team we were unable to find any issues with the edgeHub, however the OPC publisher module keeps complaining with an error (seems like a sequence number skew, something got out of sync)
**attached logs

Can you please help with finding root cause or any possible fix or workaround.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
[support_bundle (1).zip](https://github.com/Azure/Industrial-IoT/files/8854665/support_bundle.1.zip)

**Additional context**

**Comment by hansgschossmann** [comment]
From looking at the support bundle it seems the customer is using:
mcr.microsoft.com/iotedge/opc-publisher:latest
This is not recommended. The customer should pin to a specific version. 2.8.2 is the most current one. 2.8.3 will be released in the next few days.

OPC Publisher does send some messages as you can see in the logs. The value of  "Outgress IoT message count" is increasing, but maybe not as much as expected.

Further it looks like an issue in the OPC UA stack which is indicated by those messages, which needs more investigation:
[03:22:25 ERR Microsoft.Azure.IIoT.OpcUa.Protocol.Services.StackLogger] (Error) PUBLISH #7847 - Unhandled error during Publish.
 BadRequestTimeout 'BadRequestTimeout'
 
Opc.Ua.ServiceResultException: BadRequestTimeout
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.SessionClient.EndPublish(IAsyncResult result, UInt32& subscriptionId, UInt32Collection& availableSequenceNumbers, Boolean& moreNotifications, NotificationMessage& notificationMessage, StatusCodeCollection& results, DiagnosticInfoCollection& diagnosticInfos)
   at Opc.Ua.Client.Session.OnPublishComplete(IAsyncResult result)

**Comment by hansgschossmann** [comment]
@daelsala the BadRequestTimeout does happen when the OPC UA server does not respond to a request from the client (OPC Publisher) polling for data value changes. Most likely the system running the OPC UA server is too busy with other tasks with higher priorities (for example: if the OPC UA server runs on a PLC it is busy with controlling the system it is connected to, which has higher priority than responding to OPC UA client requests)

**Comment by daelsala** [comment]
> @daelsala the BadRequestTimeout does happen when the OPC UA server does not respond to a request from the client (OPC Publisher) polling for data value changes. Most likely the system running the OPC UA server is too busy with other tasks with higher priorities (for example: if the OPC UA server runs on a PLC it is busy with controlling the system it is connected to, which has higher priority than responding to OPC UA client requests)


cx provided the following information, please let me know if this helps or you need further info:
The Pi is updating the server every second or so, maybe faster. So perhaps the server is reading and updating too fast you believe? Then how does that explain that the data is still getting to our datalake in the cloud? This must mean the data is being read from the connector, and just not routed to the SQL right? Secondly, the AWS sitewise OPC connector has no issue reading the servers generated by the library here, so why would yours be having issues?
![image](https://user-images.githubusercontent.com/57229540/173657097-69fa1d58-51fe-4eee-a469-646b0a361d33.png)

**Comment by daelsala** [comment]
@hansgschossmann can you please assist
