### ISSUE TITLE
Missing Dockerfiles

### ISSUE THREAD

**Issue by MarekLani** [Azure/Industrial-IoT#183]
**Describe the bug**
Previously repo contained docker files for each module, so it was possible to build module docker image easily, without having to write own Dockerfile. Please why are dockerfiles gone now?

**Comment by marcschier** [comment]
Hi @MarekLani, managing docker files for all platforms became a lot of overhead and also managing versioning from git commits would not work inside of container builds.  You can use the tools/scripts/build.ps1 script to build images on your machine, or acrbuild.ps1 to build multi platform images for all platforms via a Azure container registry.
