### ISSUE TITLE
Not possible to configure the messaging mode with OPC Publisher working in orchestrated mode

### ISSUE THREAD

**Issue by MickeyMouseS** [Azure/Industrial-IoT#1839]
**Describe the bug**
It is not possible to configure the PubSub messaging mode with the environment variables for the Publisher microservice (PCS_DEFAULT_PUBLISH_MESSAGING_MODE, reference: https://github.com/Azure/Industrial-IoT/blob/main/docs/services/publisher.md) or the environment variables of the Publisher module (https://learn.microsoft.com/en-us/azure/industrial-iot/reference-command-line-arguments#command-line-arguments-for-version-282-and-later). It is neither possible when configuring via command-line.

**To Reproduce**
1. Set the environment variable PCS_DEFAULT_PUBLISH_MESSAGING_MODE with value PubSub for Publisher microservice and/or environment variable MessagingMode  for Publisher module.
2. Check the messages received in IoT Hub, the format it is not PubSub
3. Also you can check job configuration through the API and the messaging mode is set to Samples

**Expected behavior**
Configuration of the jobs according to the set up.

**Additional context**
Using helm chart 0.4.2 for microservices deployment.

**Comment by cristipogacean** [comment]
Indeed, this is a limitation in functionality for orchestrated mode. For now, the only way to enable PubSub in orchestrated mode is to manually change the configuration in the job configuration in job definition json object in CosmosDB.

**Comment by MickeyMouseS** [comment]
If so, when do you plan to include this functionality?

The default message in orchestrated mode can be a bit verbose, is it possible to reduce the size of this message? For example configuring a reduced format version, like in standalone mode by means of "FullFeaturedMessage=false" environment variable.

In addition, the Samples format in standalone mode does not look consistent with the orchestrated mode, as standalone mode does not include "status" attribute in the messages. Is it possible to make them consistent?

Thank you!

**Comment by hansgschossmann** [comment]
@MickeyMouseS we do nto have any plans to add any features to the orchestrated mode. Feel free to add it yourself and raise a PR if it is ready for production use.
If the "status" is bad, then it should be included in the message in standalone mode as well. We had discussions internally already if we should enable this functionality via a global command line switch in the standalone mode. @cristipogacean pls correct me if needed.

**Comment by MickeyMouseS** [comment]
Understood. Thank you for your clear answers!
