### ISSUE TITLE
 OPC Publisher Exception using CRL: Failed to decode the X509 signature

### ISSUE THREAD

**Issue by CONeal** [Azure/Industrial-IoT#1886]
**Describe the bug**
We are running the OPC Publisher as an IoT Edge Module. The connection against to Server uses Username+Password and is protected with an Certificate Handshake.
We added die Root CA, the Client Certificate and die CRL to the pki.  Adding the CRL breaks the publisher with an exception:

System.Security.Cryptography.CryptographicException: Failed to decode the X509 signature.
---> System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Universal' class value '13', but it should have been 'Universal' class value '16'.

**Expected behavior**
Authentication against OPC Server should be successful.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Publisher Container-Version: Latest 

**Additional context**
I search for this error Message and found some information. Is this maybe related to the .net runtime, for example https://github.com/dotnet/runtime/issues/47005 describes the general problem.

**Comment by mregen** [comment]
Hi @CONeal, could you check if your CRL has PEM format?

The certificate validator supports only CRL in the ASN.1 encoding.

This issue contains instruction how to generate a CRL in ASN.1: 
https://github.com/Azure-Samples/iot-edge-opc-plc/issues/174

**Comment by CONeal** [comment]
Hi @mregen,
yeah you were right, it was in the PEM format and I converted it into ASN.1. It is now possible to load the CRL, but I got  a Certificate Validation failed error. 

Certificate Validation failed. Reason=BadCertificateChainIncomplete. [CN=xx] [yy]
[2022-10-25 07:53:30.967 WRN OpcUa]  -- BadCertificateChainIncomplete 'Certificate chain validation failed. PartialChain: unable to get local issuer certificate'

Is it possible to check which Certificate is missing? I've added die Root CA, the Intermediate Certificate and also the CRL.

**Comment by mregen** [comment]
Hi @CONeal, at first, every CA certificate needs a matching CRL. If the chain is incomplete the easiest way to check were to import the chain into a tool like [XCA](http://hohnstaedt.de/xca). The cert validator in the UA stack needs at minimum KeyId extension ,binary matching Issuer/Subject and a valid signature. Hope this helps..

**Comment by CONeal** [comment]
Hi @mregen 
Thank you very much, I will have a deeper look in it.
The main question / problem is solved. I'll close this issue.
