### ISSUE TITLE
OPC Publisher: Increase BatchTriggerInterval granularity to milliseconds

### ISSUE THREAD

**Issue by NoTuxNoBux** [Azure/Industrial-IoT#1891]
**Is your feature request related to a problem? Please describe.**
We have some OPC UA properties in our server that we'd like to sample and publish more often than once per second (positions of a robot that change as it moves); `BatchTriggerInterval` doesn't allow going below one second.

**Describe the solution you'd like**
Support millisecond granularity in `BatchTriggerInterval`.

**Describe alternatives you've considered**
We first tried to lower the batch size to 1 or a low size, but this results in a very large amount of requests being sent, even if they are virtually at the same time. Ideally we would still like to batch as much as possible to keep the amount of requests low, but lower the interval to a sub-second value so we can get batched updates sooner. 

**Additional context**
We can configure the sample rate and publish interval up to millisecond granularity for the desired properties in the configuration, but it seems the OPC Publisher still batches it because of the batch size and interval.

**Comment by marcschier** [comment]
#1893

**Comment by cristipogacean** [comment]
@NoTuxNoBux, can you try adding `BatchTriggerInterval` as environment variable for the publisher module having the value in `TimeSpan` format e.g. 00:00:00.100.
![image](https://user-images.githubusercontent.com/14314727/200806572-ed35e9c4-ef59-46c1-a039-3f583752f2c1.png)

**Comment by NoTuxNoBux** [comment]
@cristipogacean From an initial look, this seems to have no effect from my end.

EDIT: I see a command line fix has been merged, which looks to be what I hoped for. Now I just have to wait for the next stable release :slightly_smiling_face: .
