### ISSUE TITLE
Documentation for use of 1.1 LTS modules missing

### ISSUE THREAD

**Issue by hansgschossmann** [Azure/Industrial-IoT#1935]
As pointed out in #1775 there is an .md missing in the doc. Tracking as separate issue here.

@marcschier, I just checked the doc of the new release (2.8.4) and the following MD file seems missing:
To continue deploying the 1.1 LTS modules to your environment follow [these instructions](https://github.com/Azure/Industrial-IoT/blob/2.8.4/deploy/howto-install-iot-edge.md).

**Comment by marcschier** [comment]
This pertains to the release notes. The /docs path was missing from the markdown and that has now been addressed
