### ISSUE TITLE
Ability to configure metadata queue name through commandline

### ISSUE THREAD

**Issue by marcschier** [Azure/Industrial-IoT#1943]
**Is your feature request related to a problem? Please describe.**
Customers want to send metadata to a dedicated topic if connecting to an MQTT broker.  Today it goes to the telemetry path.  The suggestion in Part 14 is to use a subtopic, by default $metadata.  

**Describe the solution you'd like**
We want to be able to specify the name of the subtopic to use using a command line argument like --mdo --metadataoutput.  On MQTT the metadata should be send with RETAIN and ttl as described in the spec to a subtopic of the telemetry topic with the provided name.  With EdgeHub the output name should be used, or if --ri/--enableroutinginfo is enabled, <output>/<metdataoutput>.

**Describe alternatives you've considered**
A full topic path could be used, but it would apply to all telemetry paths, unless we also make it templated.  It would only apply to MQTT, while we have seen customers leveraging routing for custom handling of messages, which might be useful to do just for metadata.  We could also provide the topic/output in pn.json, but this would be difficult to configure, and likely always the same subtopic anyway, command line is far simpler.

Open questions: Should we add outputname support to mqtt adapter templating support and by default remove the [outputname} and remove "duplicate path separators" if no output name is provided?   Separate feature request?

**Comment by barnstee** [comment]
A subtopic for the metadata off the main telemetry topic should be fine.
