### ISSUE TITLE
OPC Publisher 2.8.4: --messagingmode flag not working as expected.

### ISSUE THREAD

**Issue by Koooooooooooooooooooooooo** [Azure/Industrial-IoT#1945]
**Describe the bug**
Running the OPC Publisher version 2.8.4 with commandline argument "--messagingmode=PubSub" does not actually give PubSub messages. Instead it sends messages in the Samples format. When using the flags "--MessagingMode=PubSub" or "--mm=PubSub" the OPC Publisher sends messages in the expected PubSub format.

**To Reproduce**
1. Deploy OPC Publisher with cli flag "--messagingmode=PubSub"
3. Inspect messages sent to IoT Hub / other modules
4. See they are in the Samples format

**Expected behavior**
Messages should be in PubSub format

**Screenshots**
OPC Publisher container create options:  
![image](https://user-images.githubusercontent.com/10416706/216632657-ad119083-f79f-4ce5-9425-5016e21ec952.png)  
![image](https://user-images.githubusercontent.com/10416706/216632730-2b55f015-0ebb-4026-b226-e31fca87d8e1.png)  
Messsage:  
![image](https://user-images.githubusercontent.com/10416706/216634180-ea476c6e-167b-4e40-9626-4d540aa65b92.png)

**Edge machine:**
 - OS: Red Hat Enterprise Linux
 - Version 8.6

**Additional context**
Issue is specific to OPC Publisher 2.8.4, the issue does not happen on version 2.8.3

**Comment by marcschier** [comment]
Command line options are case sensitive and need to be specified like on command line.  We will regress this in 2.9 and revert back to the case sensitive behavior in 2.9 preview 2.
