### ISSUE TITLE
Dockerfile for OPC Publisher

### ISSUE THREAD

**Issue by simith** [Azure/Industrial-IoT#1949]
**Is your feature request related to a problem? Please describe.**
Where can i find the Docerfile for building the OPC Publisher, i want to add the configuration file so that i can run it in standalone mode

**Describe the solution you'd like**
Please provide the Dockerfile

**Describe alternatives you've considered**

**Additional context**

**Comment by marcschier** [comment]
You can use the official image as base image and add the file to it to create a derivative image.  In 2.9 we will support the new dotnet capability to publish containers using dotnet publish

**Comment by marcschier** [comment]
Now supporting dotnet publish to publish the OPC publisher application as docker container.  Support is in main branch
