### ISSUE TITLE
Request opc server's nodes information

### ISSUE THREAD

**Issue by Ilheu** [Azure/Industrial-IoT#1960]
I would like to know if there is a way to request all nodes from an opc endpoint without using the entire Industrial IoT Edge architecture. I only have the following modules in my solution: **opc-publisher, twin and discovery** modules. 
I've already discovered an endpoint in discovery module and I'd like to have access to that server's nodes. How can I access this information without integrating any other services or solutions?

I read the documentation and I know that you can use a web interface or a rest-api, but for that I need other services, right? Is there no way to request this information by direct methods or any other solution?

**Comment by marcschier** [comment]
Will be possible in 2.9 preview 2.  ETA April or May.

**Comment by marcschier** [comment]
Release 2.9.0 preview 2 of OPC Publisher was just released. It supports the OPC Twin API without cloud services.  Documentation will be provided soon.
