### ISSUE TITLE
Writing back to SCADA using OPC Publisher?

### ISSUE THREAD

**Issue by sa1sen** [Azure/Industrial-IoT#1973]
Hello,

Can you give more info on writing back upstream (SCADA) using the OPC Publisher module? I see a bi-directional arrow. I am able to read data but was wondering on the write back.

Thanks

**Comment by marcschier** [comment]
In 2.8 we have what is called OPC Twin IoT Edge module, and the cloud services required to operate it.  These cloud services expose a REST API that allow you to read/write variables or call methods in an OPC UA server. The API documentation can be found in the docs folder of the latest 2.8 branch (e.g., release/2.8.6).

In 2.9 preview 2 release out soon this will be moved into the OPC Publisher and will not require the cloud services anymore (you can call a direct method directly through IoT Hub, call the API through MQTT5, or even call a REST API.  The latter 2 options will remain in preview until end of year.
