### ISSUE TITLE
.deploy.sh fails (use Microsoft Graph PS module in aad-register.ps1)

### ISSUE THREAD

**Issue by tervoju** [Azure/Industrial-IoT#1980]
**Describe the bug**

https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md states that you can download repo and run it with command 

```./deploy.sh.``` 

cannot: it will end with result
```
Register-PackageSource: The specified Uri 'https://www.poshtestgallery.com/api/v2/' for parameter 'Location' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
```

**To Reproduce**
1. git clone repo
2. run .deploy.sh
3. run fails

**Expected behavior**
deploy success / local run 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04 WSL2

**Comment by JaivyDaam** [comment]
Hi @tervoju ,

I would like to recommend to use the 2.8.6 tag release of the repository. If feel that main is the base for the 2.9.0 preview branch and has many changes compared to the 2.8.x releases.

Myself would still need to test out the 2.9.0/main branch and I have not seen this error in any prior releases.

**Comment by marcschier** [comment]
It appears that the poshtestgallery server is down.

**Comment by marcschier** [comment]
Deployment scripts upgraded to msgraph powershell module.
