### ISSUE TITLE
deploy.ps1 fails upon deploying "platform" resource

### ISSUE THREAD

**Issue by JaivyDaam** [Azure/Industrial-IoT#1981]
**Describe the bug**
Using the Azure Cloud Shell I get the following error:
`7:59:47 AM - The deployment 'azuredeploy' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment template validation failed: 'The template parameter 'deployFromSource' is not found. Please see https://aka.ms/arm-syntax-parameters for usage details.'. (Code:InvalidTemplate)`

Looking in the resource group, it did deploy the following:
- AppInsights
- DPS+IoTHub
- Keyvault+MSI
- Storage

**To Reproduce**
1. Go to Azure, Create a resource group
2. Open Azure Cloud Shell with PowerShell and pull the Repo, change directory into `deploy/scripts`
3. run `./deploy.ps1 -type app -resourceGroupName IndustrialIot-2-9 -subscriptionID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -tenantID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -applicationName industrial-iot-29`

**Expected behavior**
I expected the powershell script to deploy the resources

**Additional context**
- Looking at the resource groups deployment, it failed at the 'platform' resource with status "BadRequest"
- I am using the "main" branch
- Upon researching the breaking changes and the platform deployment, this seems to be specifically for the App Service (all-in-one maybe?) and the parameter has been removed from the main branch.

**Comment by JaivyDaam** [comment]
After trying to use the `-type app` parameter I left it default and it comes to the same conclusion :-)

**Comment by marcschier** [comment]
Thanks for reporting, this will be fixed by next week.
