### ISSUE TITLE
Consistent CMD/Env Vars with iotedge

### ISSUE THREAD

**Issue by JaivyDaam** [Azure/Industrial-IoT#1983]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, rather a matter of consistency. 
As the publisher environment variable for Upstream transport protocol is defined as `Transport` where the `iotedge` modules of `edgeHub` and `edgeAgent` use `UpstreamProtocol`. I would like to see consistency in this regard, this makes it easier to configure in automations and deployments

**Comment by marcschier** [comment]
In 2.9.0 release 2 it should now be possible to use the requested environment variable name as alternative.
