### ISSUE TITLE
OPCPublisher:2.9.0-preview2 - REST API call with API Key

### ISSUE THREAD

**Issue by sa1sen** [Azure/Industrial-IoT#1991]
Just read the document update:

"_The corresponding REST API of OPC Publisher 2.9 (with same operation names and [type definitions](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/definitions.md)) is documented [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/api.md). In addition to calling the API through HTTP REST calls (Preview) you can call the configuration API through MQTT v5 (Preview) in OPC Publisher 2.9._"

I can find the API Key in the OPC Publisher module twin. As part of a REST API, what URL will I use to send a POST request?

E.g. **POST /v2/browse** - do I need to add the OPC Publisher module URL and port during the call. Any headers that includes the API Key?

I know documentation is being worked on as we speak.

**Comment by marcschier** [comment]
Added some information to the readme. Please ask specific questions in issues and we will upate the documentation as we go.
