### ISSUE TITLE
BadGateway error in publisher

### ISSUE THREAD

**Issue by Mikael159** [Azure/Industrial-IoT#1992]
Hello,

Last week an expiration certificate on the AKS Cluster and so we had to install new certificate.
After that action, the pods aiiot in the AKS was in error because he had a bad secret (the one in the AppRegistration “Service”).
We find how to solve this issue and the pods are running green.
But now we had an error on the publisher on our iotedge:
POST to https://XXXXXXXXXXXX.XXXXXXXXXXXXXX.cloudapp.azure.com/edge/publisher/v2/heartbeat returned BadGateway

Iotedges that are running are still sending telemetry but if one of the iotedges has to restart for any reason, we will lost this connection and lost data.
One of our iotedge is down and is not able to find back the connection to the publisher.

We can share logs but in private.
Thanks

**Comment by marcschier** [comment]
Diacussed offline. Restarting edge-jobs solved the issue.
