### ISSUE TITLE
standalone OPC-Publisher in Edge Simulator doesn't work

### ISSUE THREAD

**Issue by delema98** [Azure/Industrial-IoT#1999]
**Describe the bug**
When starting the opc-publisher in standalone mode in the edge simulator, I get a certificate error (see trace below). The same configuration works on a  regular deployed Azure IoT Edge server. Other modules can be simulated. 

I tried the latest version as well as the preview 3 version. While the latest version is constantly restarting the opc-publisher module the preview 3 version can connect as a client to an existing opc-server. Outgoing messages (from opc-publisher --> edge runtime) fail.
The following traces are from using the preview version:

![screenshot1](https://github.com/Azure/Industrial-IoT/assets/38961389/abf6c30d-d8d3-4226-a774-7780037ef3a0)
![screenshot2](https://github.com/Azure/Industrial-IoT/assets/38961389/e38f02ec-3d1e-4c52-8cae-5959ebd49f3d)
![screenshot3](https://github.com/Azure/Industrial-IoT/assets/38961389/b8d7ae81-8e4b-48d0-a26e-6691a775c409)

**Comment by marcschier** [comment]
See #1708

**Comment by marcschier** [comment]
Could you post the command line you used to start publisher in the iotedgehubdev context?

**Comment by delema98** [comment]
I tried it with different command line arguments. The most basic configuration was the following:
"modules": {
          "OPCPublisher": {
            "env": {},
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/iotedge/opc-publisher:2.9.0-preview3",
              "createOptions": {
                "Hostname": "publisher",
                "Cmd": [
                  "--aa",
                  "--di=60"
                ]
              }
            },
            "status": "running",
            "type": "docker"
          }
        }

The whole EdgeSolution is based on the default deployment.json and opcpublisher is the only module running

**Comment by marcschier** [comment]
Fixed in preview 4.
