### ISSUE TITLE
Documentation - MQTT output for opc publisher

### ISSUE THREAD

**Issue by pesetskyps** [Azure/Industrial-IoT#2012]
Could you please point to the docs where I can find the configurataion sample of publisher.json file that I can use to publish the opc-ua nodes to MQTT broker and specify different topics for different monitored items?

**Comment by marcschier** [comment]
Check out the [deploy/docker](https://github.com/Azure/Industrial-IoT/tree/feature/observability/deploy/docker) example.  Also documentation of [configuration schema](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/readme.md#configuration-schema) and [command line options](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/commandline.md)
