### ISSUE TITLE
AAD-Register fails on converting System.String to type "System.Security.SecureString"

### ISSUE THREAD

**Issue by JaivyDaam** [Azure/Industrial-IoT#2015]
**Describe the bug**
Wanting to deploy the new 2.9-preview4, I went and tried to register the Service Principals. Running the `./aad-register.ps1 -Name industrial-iot29 -TenantId xxxxxxxx-xxxx-xxxx-xxxxxxxx -Output aad.json` which produces the following error for me: 
`WARNING: Failed to sign into Microsoft Graph for industrial-iot29: Cannot bind parameter 'AccessToken'. Cannot convert the "<Very long string>" value of type "System.String" to type "System.Security.SecureString".`

**To Reproduce**
1. clone repository and go to `./deploy/scripts`
2. Run the `aad-register.ps1` with parameters mentioned above.
3. See error

**Expected behavior**
I expected my service principals to be created in AAD and return me the object information

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX 13.4.1 
 - IDE: VScode 1.18.0

**Additional context**
I used mac's `brew` to install Powershell

**Comment by marcschier** [comment]
Reason is a backwards compatibility breaking change introduced by Microsoft.Graph 2.0 PS module which was released 5 days ago. Said module was installed and used and requires a securestring instead of a string.  Fix in main.
