### ISSUE TITLE
DirectMethod "SetConfiguredEndpoints" failed

### ISSUE THREAD

**Issue by kenrena** [Azure/Industrial-IoT#2016]
**Describe the bug**
OPC Publisher Version 2.8.4 : when invoking the direct method "SetConfiguredEndpoints" or "AddOrUpdateEndpoints", get 500 as return. Other direct methods from previous versions like PublishNodes GetDiagnosticInfo etc are working. No logs for the request even.

**To Reproduce**
1.  Script to reproduce
`$file = Get-Content(".\pn.json") `
`$jsonObject = $file | ConvertFrom-Json `
`$json = ConvertTo-Json -Compress -Depth 6 -InputObject $jsonObject.psobject.BaseObject  `
`$put_Json = '{ "methodName": "SetConfiguredEndpoints", "responseTimeoutInSeconds": 200,"payload": { "endpoints": ' + json  '}}'`    
`$put_Json | Set-Content(".\payload.json")  `
`curl.exe 'https://iothubname.azure-devices.net/twins/device/modules/opcpublisher/methods?api-version=2021-04-12'   `
`  -H 'Authorization: xxxx'   `
`  -H 'Content-Type: application/json'   `
`  -d "@.\payload.json" `

**Expected behavior**
Nodes get changed or at least Badrequest for empty payload

**Screenshots**
![image](https://github.com/Azure/Industrial-IoT/assets/35649346/f8784fed-6735-4ccc-ae99-13bdc92d1a37)

**Comment by marcschier** [comment]
SetConfiguredEndpoints is only supported in 2.9.  Can you try the same on OPC Publisher 2.9 and see if this works for you?

AddOrUpdateEndpoint is supported in 2.8 ([2.8.7](https://github.com/Azure/Industrial-IoT/blob/release/2.8.7/docs/modules/publisher-directmethods.md)).  Can you open a seperate issue with repro information?
