### ISSUE TITLE
OPC Publisher Endpoint connectivity functions as a browse only

### ISSUE THREAD

**Issue by NooraKubati** [Azure/Industrial-IoT#2017]
**Describe the bug**
We have noticed in our deployments  when we specify an endpoint such as "opc.tcp://[ip]:[port]/[specific sever path]" it has become clear that opc publisher will only connect up to the point opc.tcp://[ip]:[port] and then browse for the first available path it finds. 
However, in our current server set up we have several different entities under one endpoint so for example considering server A with folders 1 and 2 within, where folder 1 was the first entity created chronologically: 

When connecting to opc.tcp://[ip]:[port]/folder_2, we find errors are returned due to nodes expected in the subspace of 2 not being found. Upon further inspection of the logs it is clear that the module in fact connected to opc.tcp://[ip]:[port]/folder_1 and therefore is unable to find the node set defined in the pn file which is expected in folder 2 only.  

**To Reproduce**
1. Have a sever with different logical paths under the endpoint 
2. Connect to a folder that was not created first in the endpoint 
3. Try to read from nodes in your expected folder 
4. You will find the module did not connect to the fully qualified endpoint you provided and cannot connect to your desired nodes

**Expected behavior**
We would expect that the module would connect to the FULL endpoint provided, not only up to the port number and then browse.  

**Screenshots**

**Desktop:**
 - OS: Windows 2019 Server

**Comment by marcschier** [comment]
This has been addressed in 2.9 Release, can you test with 2.9 and if not working provide logs of the connect sequence.
