### ISSUE TITLE
Deployment documentation regarding UI (engineering tool) is wrong for 2.9

### ISSUE THREAD

**Issue by emulic** [Azure/Industrial-IoT#2022]
**Describe the bug**
Documentation chapter [Deploy the Industrial IoT Platform](https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md#deploy-the-industrial-iot-platform) for 2.9 is mentioning engineering tool and UI. However, when executing the deployment script with `-type all` for `main `branch, the engineering tool appservice is not deployed.

**To Reproduce**
Follow deployment instructions Deploy the Industrial IoT Platform](https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md#deploy-the-industrial-iot-platform) and use `-type all` from `main `branch (defualt).

**Expected behavior**
Engineering tool appservice would be deployed.

**Additional context**
Also deploying from `engineeringtool `branch by using deployment script parameter `-branchName engineeringtool`  doesn'T solve the issue since deployment from `engineeringtool ` branch by using deployment scripts is failing with the following error:
`Deployment 'latest' succeeded.
Cannot process argument transformation on parameter 'ApplicationId'. Cannot convert null to type "System.Guid".
Deployment failed.
Try again? [y/n]:`

**Comment by marcschier** [comment]
Engineering tool sample has been removed for now.  If you are interested to bring it back to main, we would love a PR contrib.  I retained it in the engineering tool branch but it does not work.  I fixed the docs where I found remnants.
