### ISSUE TITLE
Replace DataSetWriterId by DataSetWriterName in pn.json and in the payload of direct methods

### ISSUE THREAD

**Issue by dimtix** [Azure/Industrial-IoT#2023]
Since for publisher 2.9.x in pubsub json messages the `DataSetWriterId `property from pubsub json messages has according the spec the type UInt16 and will be generated (automatically), and the configuration property `DataSetWriterId `with the type String from pn.json configuration or payload of the direct methods ends up in the property `DataSetWriterName` of pubsub json messages, this configuration property should be renamed to `DataSetWriterName` too.

**Comment by marcschier** [comment]
Agreed wholeheartedly, but our goal with 2.9 is drop-in replacement and if we blankly rename we will break backwards compatibility to 2.8 in a major way.  Of course, we can have these as "alternative" properties in the schema and both resolve to data set writer name, and any such code contribution is welcome if it comes with tests and ensures backcompat.  I am closing this as won't fix, but if you feel like pushing a PR, then we can re-open.
