### ISSUE TITLE
Documentation - Ability to run as standalone service outside of iotedge

### ISSUE THREAD

**Issue by pesetskyps** [Azure/Industrial-IoT#2024]
Thank you for recent updates recently! I am looking for some docs that could explain how to run the publisher and twin services (as I understans they are now one service) as independent service and for example publish messages to MQTT.
Is there any binaries or docker images we can use to deploy it outside of Iot Edge?

**Comment by marcschier** [comment]
Note that the officially Microsoft supported hosting model is IoT Edge (1.4).  

However, if you are looking for examples of running outside of IoT Edge, please take a look at /deploy/docker folder which shows running in docker-compose with MQTT or other northbound connectors.  You can build the container using dotnet publish using the new dotnet SDK docker container publishing support, documentation can be found online.

If you encounter issues, please log them here and we would be happy to take contributions.
