### ISSUE TITLE
MQTT connection issues are neither logged nor reported as metric

### ISSUE THREAD

**Issue by dimtix** [Azure/Industrial-IoT#2025]
**Is your feature request related to a problem? Please describe.**
MQTT connection issues are neither logged nor reported as metric. So it is quite difficult to understand where the problem is if no data is coming.

**Describe the solution you'd like**
MQTT connection related errors / problems / issues should be logged or reported as metric. The best would be both.

**Comment by marcschier** [comment]
Enabled logging of MQTT connectivity state
