### ISSUE TITLE
2.9 A&E Published_Nodes.json Example

### ISSUE THREAD

**Issue by Amber-Rigg** [Azure/Industrial-IoT#2027]
### Issue
I am wanting to use the OPC AE feature but cannot find documentation on the pn.json structure to ingest A&E data for release 2.9.

### Solution
If this is available please could you direct me to where I can find this.

If this is not available please could you add this to the repo.

**Comment by marcschier** [comment]
Hi @Amber-Rigg, is this what you were looking for? 

https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/readme.md#configuring-event-subscriptions.
