### ISSUE TITLE
Invoke direct Method and configure OPC Publisher through MQTT topic

### ISSUE THREAD

**Issue by SaifAlmaliki** [Azure/Industrial-IoT#2039]
I am publishing my telemetry successsfully from opcpublisher to MQTT broker using --ttt (telemetrytopictemplate). 

Since MQTT v5 supports RPC which allows a client to call the OPC Publisher over MQTT. I want to Invoke and configure OPC Publisher through MQTT topic.

As mentioned in the doc [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/directmethods.md#:~:text=In%20addition%20to%20calling%20the%20API%20through%20HTTP%20REST%20calls%20(Preview)%20you%20can%20call%20the%20configuration%20API%20through%20MQTT%20v5%20(Preview)%20in%20OPC%20Publisher%202.9.): ` In addition to calling the API through HTTP REST calls (Preview) you can call the configuration API through MQTT v5 (Preview) in OPC Publisher 2.9.`

Following [commandline.md](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/commandline.md#:~:text=%2D%2Dttt%2C%20%2D%2Dtelemetrytopictemplate%2C%20%2D%2DTelemetryTopicTemplate%5B%3DVALUE%5D) , I configured my opcpublisher by adding --mtt(method topic tempelate) flag and append the method name after the topic template: xx/xxxx/methods/GetConfiguredEndpoints_V2.

However I wasn't able to invoke/Configure the opcpublisher

I need a demo or simple example showing end-to-end how to invoke and configure opcpublisher module using mqtt topic

thanks

**Comment by marcschier** [comment]
This is correct. Can you provide me with the --mtt value you used so I can repro this?  Did you make sure you provide a response topic in the MQTT v5 message sent to the topic?

Samples are on the list of most requested feature. I hope I can get around to it after 2.9.1 is out.

**Comment by SaifAlmaliki** [comment]
Thanks marcshier for your response.
In my case --mtt =“fi/publisher/methods/GetConfiguredEndpoints_V2”
But not sure how to provide the response topic in the MQTT message, I assumed the response will be on the same above topic. is in it?

**Comment by marcschier** [comment]
The mtt option allows setting the root path for all methods.  Using a templating model.  When you use it though the actual topic to call for a method is the configured path, plus the method name.  So if you use --mtt x/y/z to call the method a, you send the payload to /x/y/z/a. If using mqtt 5 the payload needs to also specify the response topic. That can be any tpoc you have already subscribed to on the broker. Although I recommend to use a unique one per call. Your client library will allow you to specify that topic during publish, typically on the message object you publish. In mqttnet you do this as a property of the applocationmessage object you pass to Publish method.

**Comment by SaifAlmaliki** [comment]
Thanks marcschier, I'm sharing my snippet for better understanding.

Iam running the sample project from [Industrial-IoT Repo](https://github.com/Azure/Industrial-IoT/blob/main/deploy/docker/with-mosquitto.yaml) and play with it to fits my needs.
The telemetry flow to the mqtt broker works perfectly but I am struggling with the DirectMethod

Below snippet of my opcpublisher with `--mtt=fi/publisher/methods` representing the method topic template

![image](https://github.com/Azure/Industrial-IoT/assets/21336828/129f7478-c74d-4b05-8af7-5cf744b10541)

I simple tried to invoke `GetConfiguredEndpoints_V1` [here](https://azure.github.io/Industrial-IoT/opc-publisher/directmethods.html#getconfiguredendpoints_v1)
 
below  my simple python mqttclient using paho with that publish payload `{}` to the topic `fi/publisher/methods/GetConfiguredEndpoints_V1` and and I ve added the response topic as property to the public message and subscribed to the response topic so I should expect to receive the list of configured endpoints.

```
import paho.mqtt.client as mqtt
import paho.mqtt.properties as props
from paho.mqtt.packettypes import PacketTypes
import time

# MQTT broker settings
broker_address = "localhost"
broker_port = 1883
client_id = "mypython_client"
request_topic = "fi/publisher/methods/GetConfiguredEndpoints_V1"
response_topic = "fi/publisher/methods/response"

# Callback function for when a connection is established with the MQTT broker
def on_connect(client, userdata, flags, rc, properties=None):
    print("Connected to MQTT broker with result code: " + str(rc))
    if rc == 0:
        print("Connected to MQTT Broker")
        client.subscribe(response_topic)  # Subscribe to the response topic

    else:
        print("Connection failed")

# Callback when a message is received
def on_message(client, userdata, message):
    print(f"Received response: '{message.payload.decode()}' on topic '{message.topic}'")


# Create a MQTT client instance
client = mqtt.Client()

# Set the callback
client.on_connect = on_connect

# Connect to the broker
client.connect(broker_address, broker_port)

# Start the loop to handle incoming messages
client.loop_start()

try:
    while True:
        payload = "{}"

        # Create properties for the PUBLISH message
        properties= mqtt.Properties(PacketTypes.PUBLISH)
        properties.ResponseTopic = response_topic
        client.publish(request_topic, payload, qos=1, properties=properties)
        print(f"Published message to '{request_topic}' with response topic '{response_topic}'")
        time.sleep(5)

except KeyboardInterrupt:
    print("Disconnecting...")
    client.disconnect()
    client.loop_stop()

```

But the terminal not showing any response on the response topic
![image](https://github.com/Azure/Industrial-IoT/assets/21336828/b874ec5f-8b39-4b36-92a2-54d197ab47f9)

Also I implemented the same mqtt client using dotnet mqttnet library but still getting the same results.
Not sure what I part I missing so far
Many thanks

**Comment by marcschier** [comment]
I have tried the same and found a hole in our testing.  I also wrote a quick sample using mqttnet while at it.

**Comment by marcschier** [comment]
Samples showing several calls via mqtt are now in the samples folder (in main). They only work with 2.9.1 which will be released soon.

**Comment by SaifAlmaliki** [comment]
Thanks marcshier
