### ISSUE TITLE
data value changes from multiple variables unordered

### ISSUE THREAD

**Issue by delema98** [Azure/Industrial-IoT#2044]
I currently have the following setup:
PLC (OPC-UA enabled) --> Broker (Zenon) --> OPC Publisher --> Custom Event Aggregator (C#).
(I know that the broker is not necessary, but it exists for legacy reasons).

The PLC provides several variables that change periodically.
In the “Custom Event Aggregator” component, whenever a particular trigger variable arrives, I want to aggregate the last values of all variables and create a new event from them. 

However, I have the problem that the value changes of the different variables related to the timestamps do not arrive in the correct order.

Example of a simplified logged order:

[
    {
        "Id": "Variable1",
        "SourceTimestamp": "2023-01-11T10:00:01",
        "Value": 123
    },
    {
        "Id": "Variable2",
        "SourceTimestamp": "2023-01-11T10:00:02",
        "Value": 123
    },
    {
        "Id": "Variable3",
        "SourceTimestamp": "2023-01-11T10:00:03",
        "Value": 123
    },
    {
        "Id": "Trigger",
        "SourceTimestamp": "2023-01-11T10:00:00",
        "Value": 123
    }
]

As you can see, the Trigger variable is logged after the other events, despite the SourceTimestamp is earlier.

Is it possible to specify with OPC-UA that multiple Data Value Change events of a namespace are transmitted in the correct order?

**Comment by marcschier** [comment]
The value changes (and events) are received in a "Subscription notification", A subscription notification as the name says originates from the subscription, which in our case is mapped 1:1 to a data set writer inside a group (see docs).  The value changes in the subscription notification are not ordered by any server or source timestamp, they just represent what is picked up from the monitored item queues when the "nodes" are sampled.  What is more, the source timestamp is the timestamp of the value in the underlying source system, so technically these could be vastly different across multiple subscription notifications for the contained values.    

The samples nodes defined by the monitored items are unrelated in OPC UA, and thus the order of sampled values is only technically valid within the same node/monitored item (not even sure if the spec mandates servers to behave this way with regards to the source timestamp, but certainly the server timestamp should be increasing).  

If you need to have an atomic read of a bunch of "related" variables, then an OPC UA server someimes exposes a variable with a complex data type (struct of all variable values) and then has HasComponent Variables off of that root, with the individual values of the complex type.  Then you can choose to only sample the individual values, or the entire structure with all values in a somewhat atomic fashion.  Not sure if this is possible in your case though, it is up to the address space.  

If you need to have strict order, you must use a post processor, e.g., stream analytics.  If you just need a full data set of LKG values, then you can use the key frame feature (must use Pub/Sub encoding) or cyclic reads feature.
