### ISSUE TITLE
Requesting info about long term strategy for Iot Edge. AKS EE + Windows IoT alternative?

### ISSUE THREAD

**Issue by mwiot** [Azure/Industrial-IoT#2050]
Hi, 

I have seen the new blog entry describing using Windows IoT and AKS Edge Essentials. [Powering the next generation of Digital Operations with Windows IoT and Azure Kubernetes Service](https://techcommunity.microsoft.com/t5/internet-of-things-blog/powering-the-next-generation-of-digital-operations-with-windows/ba-p/3915439).

1. What kind of investment can we expect for IoT Edge in the future? Does this mean that IoT edge is in a stand still, and that major future investment will be towards AKS Edge essentials instead?
2. The new AKS EE solution seems to bypass the IoT hub entirely, using OPC UA PubSub over MQTT. Correct?
3. If AKS Edge Essentials is where we are headed, what are the current recommendation when it comes to solving customer needs today for connecting OPC UA servers with  bidirectional communication, using the PubSub format?
4.  Will this project be turned into kubernetes containers/pods, so that we can use a hybrid solution when it comes to edge?
5. Can you comment a bit on the architecture drawing in the bottom of this post?

Best regards

![image](https://github.com/Azure/Industrial-IoT/assets/82022527/b5fd1f86-09fd-4c84-b0eb-8ecfa347464f)

![image](https://github.com/Azure/Industrial-IoT/assets/82022527/2a7c7342-e720-494d-8e13-a56650706554)

It seems like this is the new route of the "roadmap" when it comes to connecting OPC UA on the edge to the cloud.  

![image](https://github.com/Azure/Industrial-IoT/assets/82022527/6d82d92e-f6ef-418b-a415-94dfe68c88f9)

https://github.com/digitaltwinconsortium/ManufacturingOntologies/blob/main/Docs/architecture.png

**Comment by simonaarsene22** [comment]
Hi there,

IoT Edge continues to be fully supported. Our portfolio is growing and includes now multiple customers' demands for AKS EE.  The referenced solution and diagram refer to a set of samples published in the context of the DTC to showcase standardization work the DTC is championing and they don't aim to highlight any implication for any future product plans.

In addition, we are of course open to community feedback on how to evolve this project, please let us know what you would like to see going forward.

For further questions, feel free to contact me or the Microsoft account team. 

Best regards
