### ISSUE TITLE
Need to Know the latest version of Industrial IoT & OPC Publisher

### ISSUE THREAD

**Issue by vikas-azureiot** [Azure/Industrial-IoT#2052]
**Is your feature request related to a problem? Please describe.** Yes.
Need to Know the latest version of Industrial IoT & OPC Publisher 

Industrial IoT 2.8 | 2.8.6 | 
OPC Publisher 2.8 | 2.8.7 | 
OPC Publisher 2.9 | 2.9.1 | 

Please provide the latest version for both Industrial IoT & OPC Publisher

**Comment by marcschier** [comment]
Hi, please find this information on the readme: https://github.com/Azure/Industrial-IoT#supported-releases-and-support-policy.
