### ISSUE TITLE
Getting error when try to use option 2 to deploy Azure IIoT Deployment from the https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md

### ISSUE THREAD

**Issue by vikas-azureiot** [Azure/Industrial-IoT#2063]
**Describe the bug**
Tried to deploy Azure IIoT with help of Getting error when try to use option 2 to deploy Azure IIoT Deployment from the "https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md" where it suggest if we dont have admin access then we can execute the script as per below- 

Code has been cloned from https://github.com/Azure/Industrial-IoT.git

-- Start --
Option 2 (recommended for production): An AAD admin can create the AAD applications for you. The deploy/scripts folder contains the aad-register.ps1 script to perform the AAD registration separately from the deployment. The output of the script is a file containing the relevant information to be used as part of deployment and must be passed to the deploy.ps1 script in the same folder using the -aadConfig argument.

cd deploy/scripts
./aad-register.ps1 -Name <application-name> -ReplyUrl https://<application-name>.azurewebsites.net/ -Output aad.json
./deploy.ps1 -aadConfig aad.json

-- End --
**To Reproduce**
1. Go to powershell and open it as admin
2. Take the clone of Github repos-  https://github.com/Azure/Industrial-IoT.git
3. And then copy the path of the script folder i.e. D:\Industrial-IoT\deploy\scripts and change the directory into PowerShell and run the below command-  ./aad-register.ps1 -Name iotmfgdev -ReplyUrl https://iotmfgdev.azurewebsites.net/ -Output aad.json
4. And you will get error as below mentioned
5. See error- 
<img width="907" alt="image" src="https://github.com/Azure/Industrial-IoT/assets/137897927/35c0c893-3db5-48b1-8f0e-a6ba8dea8370">

**Expected behavior**
It should execute he below script by admin without any error.

D:\Industrial-IoT-main\deploy\scripts> ./aad-register.ps1 -Name iotmfgdev -ReplyUrl https://iotmfgdev.azurewebsites.net/ -Output aad.json

**Comment by marcschier** [comment]
Fixed in main
