### ISSUE TITLE
./aad-register.ps1 errors with "A parameter cannot be found that matches the parameter name 'ReplyUrl'."

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2064]
**Describe the bug**
"I tried to deploy the Azure Industrial IoT platform version 2.9.1 using the instructions from the link 'https://azure.github.io/Industrial-IoT/web-api/#deployment-script-options'. However, I encountered an error when running the PowerShell command ./aad-register.ps1 -Name <application-name> -ReplyUrl https://<application-name>.azurewebsites.net/ -Output aad.json, and the error message stated, 'A parameter cannot be found that matches the parameter name 'ReplyUrl'."

**To Reproduce**
"Steps to reproduce the behavior:

1 Open Windows PowerShell and run it as an administrator in Windows 11.
2 Run the following command in PowerShell:
 Install-Module -Name Az -AllowClobber
 Install-Module -Name Microsoft.Graph -AllowClobber
3 Run the PowerShell command: ./aad-register.ps1 -Name <application-name> -ReplyUrl https://<application-name>.azurewebsites.net/ -Output aad.json.
4 After running the command in step 3, an error message appeared stating, 'A parameter cannot be found that matches the parameter name 'ReplyUrl'."

Exact error message is given below
PS D:\Industrial-IoT-main\deploy\scripts> ./aad-register.ps1 -Name test -ReplyUrl https://test.azurewebsites.net/ -Output aad.json
D:\Industrial-IoT-main\deploy\scripts\aad-register.ps1 : A parameter cannot be found that matches parameter name 
'ReplyUrl'.
At line:1 char:49
+ ./aad-register.ps1 -Name -ReplyUrl https://iot/ ...
+                                                 ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [aad-register.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,aad-register.ps1

**Comment by marcschier** [comment]
Fixed in main
