### ISSUE TITLE
New-Guid and "Invalid value specified for property 'resourceAppId' of resource 'RequiredResourceAccess'" Workaround

### ISSUE THREAD

**Issue by msha1026** [Azure/Industrial-IoT#207]
While working through the local deployment, the deployment scripts threw two errors that I was able to find a workaround for:

Error: `New-Guid : The term 'New-Guid' is not recognized as the name of a cmdlet, function, script file, or operable program.`
Workaround: In `New-AppRole` function, change `$appRole.Id = New-Guid` to `$appRole.Id = [guid]::newguid()`

Error: `Error occurred while executing SetApplication
Code: Request_BadRequest
Message: Invalid value specified for property 'resourceAppId' of resource 'RequiredResourceAccess'.`
Workaround: In `Get-RequiredPermissions` function, change `$requiredAccess.ResourceAppId = $sp.AppId` to `$requiredAccess.ResourceAppId = $sp.AppId.Trim().Split(" ")[0]` in order to handle when there are multiple appIds

Not sure if the deployment script was supposed to work as is, but wanted to put these out there in case anyone runs into the same errors and needs a workaround in the short term.

**Comment by marcschier** [comment]
@msha1026 --  Thank you soo much for the support and help.  I created a PR #209 based on your suggestions.
