### ISSUE TITLE
Unable to get deployed application url https://deployedtest.azurewebsites.net after successful deployment of Azure IIOT 2.9.2

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2070]
**Describe the bug**
Unable to get deployed application url https://deployedtest.azurewebsites.net after successful deployment of Azure IIOT 2.9.2

**To Reproduce**
1. Followed url https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md#running-the-industrial-iot-platform-opc-publisher-web-service-locally to deploy the azure IIOT 2.9.2
2. Download the code in local machine using git clone https://github.com/Azure/Industrial-IoT
cd Industrial-IoT
3. Run the poweshell ./aad-register.ps1 -Name testapp -ReplyUrl https://testapp.azurewebsites.net/ -TenantId ************************* -Output aad.json
4. After that run the powershell ./deploy.ps1 -version 2.9.2-aadConfig aad.json-applicationName testapp
5. Error : Got message Deployment '2.9.2' succeeded. but did not receieve message "the deployed application can be found at https://testapp.azurewebsites.net" as per msdn docs. Although receieved message "Save environment as C:\Code\Industrial-IoT\.env for local development? [y/n]: n" we choose 'n', also got below urls 
PCS_RESOURCE_GROUP=rg-tfp-prod
PCS_KEYVAULT_URL=https://keyvault-test.vault.azure.net/
PCS_AUTH_PUBLIC_CLIENT_APPID=****************************
PCS_AUTH_TENANT=*******************************************
PCS_IMAGES_TAG=2.9.2
PCS_SERVICE_URL=https://testapp.azurewebsites.net 

Tried to access the https://testapp.azurewebsites.net  which is PCS_SERVICE_URL, got error message "This testapp.azurewebsites.net  page can’t be found"

**Comment by marcschier** [comment]
The service url is the endpoint of the rest api.  You can use swagger UI to exercise the API as described in the referenced documentation.  The engineering tool has been removed, but we would take contribution to make what we saved in the engineeringtool branch working again and check it into the samples folder.
