### ISSUE TITLE
UI is not accessible after deployment of Azure IIOT 2.9.2

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2073]
**Describe the bug**
UI is not accessible after deployment of Azure IIOT 2.9.2. After deployment of azure IIoT 2.9.2, script will return the ui URL and using that url we can access the UI. 

**To Reproduce**
1. Download the code in local machine using git clone https://github.com/Azure/Industrial-IoT
cd Industrial-IoT
2. Run the poweshell ./aad-register.ps1 -Name testapp -ReplyUrl https://sampleapp.azurewebsites.net/ -TenantId ************************* -Output aad.json
3. After that run the powershell ./deploy.ps1 -version 2.9.2 -type all -aadConfig aad.json-applicationName sampleapp
4. Error : UI is not accessible after deployment of Azure IIOT 2.9.2.

**Expected behavior**
UI should be accessible after deployment of Azure IIOT 2.9.2. Please refer below screenshot given on msdn link

**Screenshots**
<img width="441" alt="image" src="https://github.com/Azure/Industrial-IoT/assets/16925233/b756f112-d1bc-4623-89e3-3e5d024ede83">

**Comment by Freshchris01** [comment]
The engineering tool isn't available since 2.9.X, see [this comment](https://github.com/Azure/Industrial-IoT/issues/2022#issuecomment-1656568178).

**Comment by marcschier** [comment]
This is correct. The engineering tool is in the engineeringtool branch.  If there is interest in making it work, it would be a great addition to the "samples" folder.
