### ISSUE TITLE
Time Series Insights are not deployed after deploying the Azure IIOT 2.9.2

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2074]
**Describe the bug**
**Time Series Insights** is not deployed after deploying the Azure IIOT 2.9.2. Gone through the link https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/migrationpath.md#breaking-changes but did not receieve the much information about time series insights  why it is not deployed

**To Reproduce**
1. Download the code in local machine using git clone https://github.com/Azure/Industrial-IoT
cd Industrial-IoT
2. Run the poweshell ./aad-register.ps1 -Name testapp -ReplyUrl https://sampleapp.azurewebsites.net/ -TenantId ************************* -Output aad.json
3. After that run the powershell ./deploy.ps1 -version 2.9.2 -type all -aadConfig aad.json-applicationName sampleapp
4. See error:  **Time Series Insights** is not deployed after deplying the Azure IIOT 2.9.2

**Expected behavior**
**Time Series Insights** should be deployed when run the powershell command
./deploy.ps1 -version 2.9.2 -type all -aadConfig aad.json-applicationName sampleapp
deplying the Azure IIOT 2.9.2.

**Screenshots**
<img width="410" alt="image" src="https://github.com/Azure/Industrial-IoT/assets/16925233/e039e891-8ef6-478b-8a05-fb4207ff0474">

**Comment by marcschier** [comment]
Time Series Insights is not deployed by the deployment script/templates.
