### ISSUE TITLE
Update documentation on https://learn.microsoft.com/en-us/azure/industrial-iot to be aligned with 2.9.

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2075]
**Describe the bug**
**SignalR Service** is not deployed after deploying the Azure IIOT 2.9.2. Gone through the link https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/migrationpath.md#breaking-changes but did not get the much information about **SignalR Service** why it is not deployed

**To Reproduce**
1. Download the code in local machine using git clone https://github.com/Azure/Industrial-IoT
cd Industrial-IoT
2. Run the poweshell ./aad-register.ps1 -Name testapp -ReplyUrl https://sampleapp.azurewebsites.net/ -TenantId ************************* -Output aad.json
3. Run the poweshell ./aad-register.ps1 -Name testapp -ReplyUrl https://sampleapp.azurewebsites.net/ -TenantId ************************* -Output aad.json
4. See error: **SignalR Service** is not deployed after deplying the Azure IIOT 2.9.2

**Expected behavior**
**SignalR Service** should be deployed when run the powershell command
./deploy.ps1 -version 2.9.2 -type all -aadConfig aad.json-applicationName sampleapp
deplying the Azure IIOT 2.9.2.

**Screenshots**
<img width="407" alt="image" src="https://github.com/Azure/Industrial-IoT/assets/16925233/1296ee2e-24a5-46db-bcf0-a96cdef2833c">

**Comment by marcschier** [comment]
SignalR is not deployed by the script.  @gauravsep1, I am not sure where you found it documented in this repo that signal r (and time series insights, etc.) are deployed.  Could you point me to the information, please?  Then I can ensure it is updated rather than you are opening issue after issue based off the wrong documentation you are using.

**Comment by gauravsep1** [comment]
@marcschier  Following msdn link https://learn.microsoft.com/en-us/azure/industrial-iot/tutorial-deploy-industrial-iot-platform to deploy the Azure IIOT. Please correct me how can i deploy azure signalR service in the azure IIOT 2.9.2

**Comment by gauravsep1** [comment]
> SignalR is not deployed by the script. @gauravsep1, I am not sure where you found it documented in this repo that signal r (and time series insights, etc.) are deployed. Could you point me to the information, please? Then I can ensure it is updated rather than you are opening issue after issue based off the wrong documentation you are using.

@marcschier Following **msdn** link https://learn.microsoft.com/en-us/azure/industrial-iot/tutorial-deploy-industrial-iot-platform to deploy the Azure IIOT. Please let me know how can i deploy azure signalR service in the azure IIOT 2.9.2 ??

**Comment by marcschier** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/265564
