### ISSUE TITLE
Event subscription using the REST Api fails with: "The request field is required."

### ISSUE THREAD

**Issue by Haeavar** [Azure/Industrial-IoT#2078]
**Describe the bug**
Event subscription using the REST Api fails. It seems to be the case sensitivity. But as documented, Upper CamelCase should work as well - https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/readme.md#advanced-event-filter-configuration

**To Reproduce**

PATCH http://localhost:8083/v2/configuration
`[

    {
        "EndpointUrl": "opc.tcp://opc-simulator:4840",
        "UseSecurity": false,
        "DataSetWriterGroup": "dswg",
        "DataSetWriterId": "dswid",
        "OpcNodes": [
            {
                "Id": "i=2253",
                "DisplayName": "myEvents",
                "EventFilter": {
			"TypeDefinitionId": "ns=2;i=235"
                }
            }
        ]
    }
]`

RESPONSE
`{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
	"title": "One or more validation errors occurred.",
	"status": 400,
	"traceId": "00-022ffc4d9b3fcd95ea3b648aa09bc64c-85bb69d46ed4ef90-01",
	"errors": {
		"$": [
			"No reader for TypeDefinitionId"
		],
		"request": [
			"The request field is required."
		]
	}
}`

**Expected behavior**
The OpcPublisher subscribes to the event.

**Additional context**
OpcPublisher 2.9.2.1

**Comment by marcschier** [comment]
Great find. This should be fixed now. Can you try tag "2.9.3-preview1"?
