### ISSUE TITLE
Getting issue when try to access the VMs - used option 2 to deploy Azure IIoT Deployment from the https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md

### ISSUE THREAD

**Issue by vikas-azureiot** [Azure/Industrial-IoT#2079]
**Describe the bug**
Tried to deploy Azure IIoT using option 2  and able to deployed the Azure IIoT from the "https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md" where it suggest if we dont have admin access then we can execute the script as per below-

Code has been cloned from https://github.com/Azure/Industrial-IoT.git

-- Start --
Option 2 (recommended for production): An AAD admin can create the AAD applications for you. The deploy/scripts folder contains the aad-register.ps1 script to perform the AAD registration separately from the deployment. The output of the script is a file containing the relevant information to be used as part of deployment and must be passed to the deploy.ps1 script in the same folder using the -aadConfig argument.

cd deploy/scripts
./aad-register.ps1 -Name -ReplyUrl https://.azurewebsites.net/ -Output aad.json
./deploy.ps1 -aadConfig aad.json

-- End --
**To Reproduce**
1. Go to powershell and open it as admin
2. Take the clone of Github repos- https://github.com/Azure/Industrial-IoT.git
3. And then copy the path of the script folder i.e. D:\Industrial-IoT\deploy\scripts and change the directory into PowerShell and run the below command- ./deploy.ps1 -aadConfig aad.json
And It will successfully executed the deployment script and generated the .env file. However, script created 4 vms and there is no any public ips is created for the VMs and hostname is also not showing so how we can access the VMs even no there is no any inbound port is enabled under networking. So, do we need to add public ips explicity or is there any workaround to access the VMs. If this is bug then please fix it.
See error-

<img width="899" alt="image" src="https://github.com/Azure/Industrial-IoT/assets/137897927/a5a2335c-41e5-42f0-bc82-10a8993c9872">

**Expected behavior**
All the VMs should be accessed by end user if they have user id and password.

**Comment by marcschier** [comment]
For security reasons no VM is exposed to the public internet.  If you need to access, you can use Bastion, or the other means suggested in the portal.
