### ISSUE TITLE
MqttClientConnectionString does not use 'Port' definition

### ISSUE THREAD

**Issue by Haeavar** [Azure/Industrial-IoT#2082]
**Describe the bug**
The Port can not be set using MqttClientConnectionString. The OpcPublisher will always use 1883 to connect to. Even if I define "MqttClientConnectionString=HostName=mosquitto;Port=1884;Protocol='v5'"

**To Reproduce**
Start OpcPublisher using at least following env variables:

    - DefaultTransport=Mqtt
    - MqttClientConnectionString=HostName=mosquitto;Port=1884;Protocol='v5'

**Expected behavior**
The OpcPublisher should connect to the MQTT broker at defined port.

**Additional context**
We are using the OpcPublisher from mcr.microsoft.com/iotedge/opc-publisher:2.9.2

**Comment by marcschier** [comment]
I tested this with "--mqc=HostName=mosquitto;Port=1884;Protocol=v5" and it parsed the port correctly into the Port option property.  The quotes around v5 need to be removed.

**Comment by marcschier** [comment]
I have also tested this with the docker compose sample. the changes are in the `port1884test` branch.  This should work correctly at least from my testing with 2.9.2.
