### ISSUE TITLE
Add Azure Storage, Azure Key Vault services, and Application Insights to arch diagram

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2083]
**Is your feature request related to a problem? Please describe.**
I would like to view the architecture diagram of the Azure IIoT 2.9.2 platform. Could someone please guide me on where I can find it?

**Describe the solution you'd like**
I would like to view the architecture diagram of the Azure IIoT 2.9.2 platform. Could someone please guide me on where I can find it?

**Comment by marcschier** [comment]
Thanks for pointing out that this is missing. You can find the architecture diagram under https://github.com/Azure/Industrial-IoT/tree/main/docs.

**Comment by gauravsep1** [comment]
> Thanks for pointing out that this is missing. You can find the architecture diagram under https://github.com/Azure/Industrial-IoT/tree/main/docs.

@marcschier In the provided architecture, using the link https://github.com/Azure/Industrial-IoT/tree/main/docs, I cannot find the Azure Storage, Azure Key Vault services, and Application Insights. However, when I deployed the Azure IIOT 2.9.2 platform in services mode, these services were also deployed. Please provide me with an updated architecture.
