### ISSUE TITLE
How to authenticate with CLI container image

### ISSUE THREAD

**Issue by Freshchris01** [Azure/Industrial-IoT#2088]
I try to use the `mcr.microsoft.com/iot/industrial-cli:latest` container image to interact with my industrial IoT 2.9 deployment.
I found out that I can add my commands when running the image to execute them, e.g. `docker run mcr.microsoft.com/iot/industrial-cli:latest apps list`.
To get the authentication right, I need to pass 2 things, the `.env` file and Azure credentials/auth information.
I tried passing the env file to the container by mounting the file, but how can I pass the Azure login information?
Or am I using the container in a wrong way?

Mounting the `.env`file:
`docker run --mount type=bind,source=<path_to_repo>/Industrial-IoT/.env,target=/.env mcr.microsoft.com/iot/industrial-cli:latest  apps list
`

**Comment by marcschier** [comment]
Aren't you prompted for your credentials when you run the command?  Can you try using the 'console' run mode and enter 'apps list'? What error do you see?

**Comment by Freshchris01** [comment]
What exactly do you mean with the console run mode?
Running `dotnet run console` from within the repo? That works as expected.

When running the command with docker run, I get an error that I don't have access to the KeyVault and should log in using the Azure CLI.
```
Unhandled exception. System.AggregateException: One or more errors occurred. (A keyvault uri was provided could not access keyvault at the address. If you want to read configuration from keyvault, make sure the keyvault is reachable, the required permissions are configured on keyvault and authentication provider information is available. Sign into Visual Studio or Azure CLI on this machine and try again.)
 ---> Furly.Exceptions.InvalidConfigurationException: A keyvault uri was provided could not access keyvault at the address. If you want to read configuration from keyvault, make sure the keyvault is reachable, the required permissions are configured on keyvault and authentication provider information is available. Sign into Visual Studio or Azure CLI on this machine and try again.
```

So I assume from inside the container, I am not authenticated/logged into the Azure CLI.

My plan would be to use the container to have an easier interface than `dotnet run console`  and to create an application around it.

**Comment by marcschier** [comment]
Thanks for the additional information!  The key vault contains the aad info to set up the confidential client to access the rest API.  Azure identity is used to access key vault. This can be an MSI, or the credential in the credential cache of az CLI or ps. If run inside the container you have 2 options.  You can export the content of the key vault into the .env file.  There is a sample script here: . https://github.com/Azure/Industrial-IoT/blob/main/tools/e2etesting/GetSecrets.ps1. Then you can mount the .env file like you did.  Drawback, now you have secrets in .env file.  Or, you can provide the Azure identity credential to access key vault as environment variable (https://learn.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet).  This is a bit better, but I recommend to run the container in production with access to the MSI endpoint (like the REST API web app container which runs in app service with access to the MSI) Caveat: I have not tested it.
