### ISSUE TITLE
Configuring event subscriptions for multiple events

### ISSUE THREAD

**Issue by meshell** [Azure/Industrial-IoT#2098]
I tried to use the OPC publisher to subscribe to multiple events using the [Simple event filter](https://azure.github.io/Industrial-IoT/opc-publisher/#simple-event-filter). However it is not clear from the documentation how the configuration has to look like for multiple events.
I tried different ways, for example using multiple OPCNodes:
```json
[
    {
        "EndpointUrl": "opc.tcp://testserver:62563/Quickstarts/SimpleEventsServer",
        "OpcNodes": [
            {
                "Id": "i=2253",
                "DisplayName": " Event1 ",
                "EventFilter": {
                    "TypeDefinitionId": " ns=2;i=1000"
                }
            },
            {
                "Id": "i=2253",
                "DisplayName": " Event2",
                "EventFilter": {
                    "TypeDefinitionId": " ns=2;i=1001"
                }
            }

        ]
    }
]
```
However none worked. With the example above, I always only got the last defined event.
Please update the documentation with an example for multiple event subscription and/or if the config above should work investigate further, why it doesn't.

**Comment by marcschier** [comment]
It looks like a bug where the monitored item is overridden due to the same node ID being the source.

**Comment by marcschier** [comment]
The issue is fixed in the latest preview release.  The image is available at mcr.microsoft.com/iotedge/opc-publisher:2.9.3-preview2.  Please let me know whether this does not fix your issue.
