### ISSUE TITLE
Dapr Config Document

### ISSUE THREAD

**Issue by xky0007** [Azure/Industrial-IoT#2102]
**Is your feature request related to a problem? Please describe.**

There is no document nor example for how to use dapr with OPC-Publisher. 

For example, if I have a customized daprd binary, how do I set the daprd path and config path with publisher? 

**Describe the solution you'd like**

Add examples and docs for dapr support.

**Comment by marcschier** [comment]
Hi,  docs are at https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/transports.md#dapr.    

Please start with the compose sample configuration: https://github.com/Azure/Industrial-IoT/blob/main/deploy/docker/with-dapr.yaml.

**Comment by xky0007** [comment]
> Hi, docs are at https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/transports.md#dapr.
> 
> Please start with the compose sample configuration: https://github.com/Azure/Industrial-IoT/blob/main/deploy/docker/with-dapr.yaml.

https://github.com/Azure/Industrial-IoT/blob/main/deploy/docker/readme.md

The readme.md doesn't include the dapr example.

In addition, the with-dapr.yml is a bit old. It cannot be runned.

For following problem, should I open a new issue? Thanks.
![image](https://github.com/Azure/Industrial-IoT/assets/30423949/d5bfb3bc-6c13-47d9-8a12-b11f0db7bb93)

**Comment by marcschier** [comment]
Cannot reproduce the error mentioned using main branch.  To use the main branch you must first run the build.cmd and then -f with-localimage.yaml.  Until 2.9.3 has been released to the 2.9 tag.
