### ISSUE TITLE
endpointState / notSeenSince missing (EndpointInfoModel)

### ISSUE THREAD

**Issue by krkappa** [Azure/Industrial-IoT#2116]
**Describe the bug**
I have deployed the current version (2.9.2) with option "-type all". When testing the Web API (with Postman), I never get the information about endpointState / notSeenSince by calling 

![image](https://github.com/Azure/Industrial-IoT/assets/151452278/2c01e642-19ea-4b88-9d59-0a0fb270f99f)

At the time of the call, I am already connected to the OPC server and, for example, can browse the root node.

**To Reproduce**
1. Deploy current version 2.9.2
2. Configure Postman to retrieve access token + get a new access token
3. Add application
![image](https://github.com/Azure/Industrial-IoT/assets/151452278/03069182-127a-46b8-88b3-59b2695576b2)
4. Get available endpoints
![image](https://github.com/Azure/Industrial-IoT/assets/151452278/a2685e83-6a3a-412b-8e4c-ad18a21943eb)
5. Connect endpoint
![image](https://github.com/Azure/Industrial-IoT/assets/151452278/e1a34d13-8de2-4ee1-acb1-10a136cc6c6c)
6. Browse target node, browse nodes or read a value to test that the connection to the OPC server is established
7. Get detail information of the selected endpoint
![image](https://github.com/Azure/Industrial-IoT/assets/151452278/6d06d97f-d17a-4a34-b666-c5f42501bffa)
--> No "endpointState" and "notSeenSince" in the response

**Expected behavior**
If the connection to the OPC server is successfully established, the respone of 
![image](https://github.com/Azure/Industrial-IoT/assets/151452278/2c01e642-19ea-4b88-9d59-0a0fb270f99f)
includes the current information for "endpointState" and "notSeenSince".

**Comment by marcschier** [comment]
Endpoint state API remained for backwards compatibility, but not supported anymore in 2.9.  Is there a particular scenario you need it for, or is this just for testing?

**Comment by krkappa** [comment]
Thanks for the fast reply. Did I understand the point correctly that the EndpointInfo model remains unchanged, but the information (endpointState, notSeenSince) is no longer output or supported? Which query can I use to get the status of the endpoint (ready, disconnected, ...)? Or can this information be obtained from the execution of other queries (browse node)?

**Comment by marcschier** [comment]
If you need it, then we can change this to a feature request to have an API (or a way to add it back to the endpoint model through signaling).  This was easy in 2.8 because each endpoint was a OPC Twin device identity in IoT Hub, so the twin had the endpoint state.  While easy, it was also not very reliable, but since we moved away from channeling device identities for endpoints to the edge, we need to replace the old way.

**Comment by krkappa** [comment]
Thanks for the replies. We currently only need the feature for testing purposes. It would be helpful to adapt the API documentation to determine which functions are supported in version 2.9 and which are still available due to backwards compatibility. The issue ticket can be closed. Thanks.
