### ISSUE TITLE
Replace Furly dapr related library

### ISSUE THREAD

**Issue by xky0007** [Azure/Industrial-IoT#2117]
**Is your feature request related to a problem? Please describe.**
After trying to run the publisher in local debug mode, I found the Furly related library is not open source. I cannot check the source code for dapr related code and it's hard for community to integrate more functions.

**Describe the solution you'd like**
We should found open source dapr related libs to implement dapr support. For example, the dapr sdk from Dapr or [DaprSideKick](https://github.com/man-group/dapr-sidekick-dotnet)

Just curious why choose [furlysoft](https://github.com/furlysoft)?

**Comment by HeikoS-Trumpf** [comment]
Or open source the furly library. The nuget-packages have MIT license.

**Comment by marcschier** [comment]
Yep, the microsoft/project-furly repo will be public with the release of 2.9.3 next week.
