### ISSUE TITLE
Dapr should work in http instead of https

### ISSUE THREAD

**Issue by xky0007** [Azure/Industrial-IoT#2119]
**Describe the bug**

In the source code `internal sealed class Dapr : ConfigureOptionBase<DaprOptions>`

```
 // Permit the port to be set if provided, otherwise use defaults.
 if (properties.TryGetValue(GrpcPortKey, out var value) &&
     int.TryParse(value, CultureInfo.InvariantCulture, out var port))
 {
     options.GrpcEndpoint = "https://localhost:" + port;
 }

 if (properties.TryGetValue(HttpPortKey, out value) &&
     int.TryParse(value, CultureInfo.InvariantCulture, out port))
 {
     options.HttpEndpoint = "https://localhost:" + port;
 }
```

From the dapr API [doc](https://docs.dapr.io/reference/api/pubsub_api/), it should use http instead of https. And after I changed https to http, #2109 is also solved. (Also need to change to GRPC protocol #2118 )

Thanks.

**Comment by marcschier** [comment]
Many thanks for the contributions, more are certainly welcome in this area in particular. I added a "Scheme" key to the connection string to select http or https, the default is now "http".  preview4 container image will be available later today.  Keep it coming :-)
