### ISSUE TITLE
New publisher 2.9.3-preview4 does not start if runing as standalone container via docker-compose

### ISSUE THREAD

**Issue by dimtix** [Azure/Industrial-IoT#2130]
**Describe the bug**
New publisher 2.9.3-preview4 if starts as a standalone container via docker-compose/docker-desktop seems not to be able to create pki folder structure => does not find the pki folder and then retry infinitely. Corresponding log is attached: [publisher-error-log.txt](https://github.com/Azure/Industrial-IoT/files/13614395/publisher-error-log.txt). Corresponding test docker-compose.yml (as txt) is attached too: [docker-compose.txt](https://github.com/Azure/Industrial-IoT/files/13614402/docker-compose.txt).

**To Reproduce**
1. Start attached docker-compose.yml
2. Look at the container logs.

**Expected behavior**
Publisher creates pki folder structure and starts (as version 2.9.2 done).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by marcschier** [comment]
This is "fixed" in main, to work around this with preview4, please use "User": "root" in the compose file.  This work around will not be needed in 2.9.3 final.
