### ISSUE TITLE
Question - Is there any queueing mechanism to MQTT output interface

### ISSUE THREAD

**Issue by pesetskyps** [Azure/Industrial-IoT#2142]
Is there any mechanism that prevents the data loss of telemetry that was read from OPC-UA servers when MQTT broker that is set for telemetry to be published to is not available? If there is can you point to the place where I can configure Queue size?

Thank you

**Comment by marcschier** [comment]
Right now the network sink class tries to send a message for "forever".  The queue size for all messages queued for sending can be configured using `--om`. It already has a pretty large default of 4000 (legacy), which might not be reasonable for constraint setups.  Queue eviction is LIFO.
