### ISSUE TITLE
aarch64/ARM64 error

### ISSUE THREAD

**Issue by TruthSeekerX** [Azure/Industrial-IoT#2145]
**Describe the bug**
The latest update broke the OpcPublisher on rPi400. Tried both ubuntu 22.04 server LTS and Raspbian OS (bookworm) the same error: "_exec /usr/bin/dotnet: exec format error_"

**To Reproduce**
sudo iotedge list

**Expected behavior**
It worked before.

**Screenshots**
![image](https://github.com/Azure/Industrial-IoT/assets/78495830/a235608c-2d35-417e-b4a4-e4e790713b4e)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 Server LTS 64bit, Raspbian OS(bookworm) 64bit

**Hardware""
RaspberryPi 400 (ARM Cortex A72)

**Additional context**
As a side project. I was working on opcPublisher only 1day/week. It worked 10 days ago when setup. But from yesterday 19.Dec.2023, OpcPublisher stoped working.

**Comment by marcschier** [comment]
Build system is selecting the wrong Mariner image as base, change to use 8.0.0-cbl-mariner2.0-arm64v8 explicitly.

**Comment by TruthSeekerX** [comment]
Thanks for quick reply. 👍

**Comment by marcschier** [comment]
Should be fixed in mcr.microsoft.com/iotedge/opc-publisher:2.9.4-preview1.
