### ISSUE TITLE
Unable to Connect to OPC Publisher 2.9.3  Rest End Points (Connection refused)

### ISSUE THREAD

**Issue by vishutyagi000** [Azure/Industrial-IoT#2146]
**Describe the bug**
Unable to Connect to OPC Publisher Rest End Points 
Used below commands 
curl http://localhost:8080/swagger/v2/openapi.json
curl http://{opcpublisherModuleName}:8080/swagger/v2/openapi.json in my case curl http://OPCPublisher:8080/swagger/v2/openapi.json

**To Reproduce**

1. Add OPC publisher module 2.9.3  using image  mcr.microsoft.com/iotedge/opc-publisher:2.9.3 in edge deployment.
2. Go to the VM(ubuntu 20.0)  Used as edge device using ssh
3. Use curl http://localhost:8080/swagger/v2/openapi.json
4. Got error Connection refused.

**Expected behavior**
The End point should get called  as 8080 is exposed .
Refer -https://github.com/Azure/Industrial-IoT/blob/246ff6e4b4105baa562c2c01870895432d21ea73/docs/opc-publisher/readme.md#calling-the-api-over-http

**Screenshots**

![image](https://github.com/Azure/Industrial-IoT/assets/55187637/18b1a985-6faf-484c-9d3c-52eeb84b9763)
![image](https://github.com/Azure/Industrial-IoT/assets/55187637/e5c255ef-b3ea-4d83-bb5e-50f87c1b5096)

**Desktop (please complete the following information):**
 - Ubuntu (20.0) as edge device
 -OPC Publisher version 2.9.3

**Additional context**

**Comment by marcschier** [comment]
The 443/80 ports must be routed to 8080/8081. It looks like this is not the case in your setup.  If you want to use 8080: `{\"PortBindings\":{\"80/tcp\":[{\"HostPort\":\"8080\"}],\"443/tcp\":[{\"HostPort\":\"8081\"}]}`. see [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/deployment.json).

If this did not work, please provide the full "CreateOptions" you used in your deployment manifest.

**Comment by vishutyagi000** [comment]
@marcschier  Thanks its working ,Yeah  PortBindings were wrong  ,instead of \"80/tcp\":[{\"HostPort\":\"8080\"}  i was using 

\"8080/tcp\":[{\"HostPort\":\"8080\"} and In OPCPublisher log i can see  8080 was being overridden.


![image](https://github.com/Azure/Industrial-IoT/assets/55187637/1df48d3b-fd64-4dcb-8bb8-50a3be20a670)
