### ISSUE TITLE
Credentials types and authentication API needs to be better documented and available in openapi swagger

### ISSUE THREAD

**Issue by vishutyagi000** [Azure/Industrial-IoT#2152]
Unable to Authenticate to Matrikon  OPC Server Simulation Server while calling Browse rest API endpoint.
Calling http://opcpublisher:80/v2/browse/first or http://localhost:80/v2/browse/first.
Successfully hitting the rest API endpoint however got error of invalid user/password.

**To Reproduce**

1. On an Edge Device(VM) ,Use OPCPublisher version 2.9.3
2. Call  http://opcpublisher:80/v2/browse/first or  **http://localhost:80/v2/browse/first**
3. Body Content to pass this post method 

```
{
  "Connection": {
    "Endpoint": {
      "Url": "opc.tcp://OPCSERVERIP:21381/MatrikonOpcUaWrapper",
      "securityMode": "Best",
      "securityPolicy": "http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15"
    },
    "user": {
      "type": "UserName",
      "value": {
        "UserName": "testuser",
        "Password": "password"
      }
    }
  },
  "Request": {
    "view": {
      "viewId": "ns=2;s=0:Random.Int1"
    },
    "nodeId": "ns=2;s=0:Random.Int1",
    "direction": "Forward",
    "header": {
      "namespaceFormat": "Uri"
    }
  }
} 
```
Getting error Username password invalid.
![image](https://github.com/Azure/Industrial-IoT/assets/55187637/66a276bc-0743-4269-8641-53992c92e9de)

we want to use **/v2/browse/first** or **/v2/browse** as per openapi document
https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/openapi.json

![image](https://github.com/Azure/Industrial-IoT/assets/55187637/ec33ffaf-02cb-428d-85a3-b7f53e19f019)

As per documentation  https://github.com/Azure/Industrial-IoT/blob/release/2.9.3/docs/opc-publisher/definitions.md#credentialmodel

CredentailModel is like 
![image](https://github.com/Azure/Industrial-IoT/assets/55187637/5d507ab7-45e9-4042-96b6-21d20154116b)
But in Source code it is like
![image](https://github.com/Azure/Industrial-IoT/assets/55187637/1a3a3f2d-bc4c-46ae-a907-379ca355a623)

Here "value" property in user object is not defined in documentation
"user": {
      "type": "UserName",
      "value": {
        "UserName": "testuser",
        "Password": "password"
      }
    }

Not sure how to pass credentials  of opc server as this is not described in documentation.

![image](https://github.com/Azure/Industrial-IoT/assets/55187637/6705cbda-db7b-4c17-9acd-7ef431387316)

**Expected behavior**
It should browse the OPC Simulation server.

**Screenshots**
![image](https://github.com/Azure/Industrial-IoT/assets/55187637/1aa94561-eaf6-4995-927a-f741e864194a)
![image](https://github.com/Azure/Industrial-IoT/assets/55187637/15210a9c-0667-4a31-a435-697137b8ef39)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [20.04]
 - OPCpublisher version -2.9.3

**Additional context**
Please share the example request to call http://localhost:80/v2/browse/first or http://localhost:80/v2/browse  or any historical data related API.
In continuation with previous clarification  needed ,more info can be found on below issue
https://github.com/Azure/Industrial-IoT/issues/2146

**Comment by marcschier** [comment]
Yes, it is not documented well.  Use "user" and "password" instead of "UserName" and "Password" as property strings.

**Comment by vishutyagi000** [comment]
@marcschier  Thank you its working ,is there any way where we can generate these json input for rest endpoints ,will be very helpful.
However thanks for you quick response, should i close this issue?

**Comment by marcschier** [comment]
I am thinking we want a typed credential model that is reflected in the open API definition plus some documentation , so let's keep this open for now
