### ISSUE TITLE
Swagger UI "try it out" API calls not authorized

### ISSUE THREAD

**Issue by greg-mcnamara** [Azure/Industrial-IoT#2155]
**Describe the bug**
Hi, Azure/Industrial-IoT newbie here. I just installed the services on Azure following the instructions. I can access [appname].azurewebsites.net/swagger but when I use the "Try it out" function it fails with a 401 error. I expect this is because I haven't authenticated via the Swagger UI. There doesn't appear to be an option to authenticate via the API even though I have set the PCS_AUTH_REQUIRED environment variable to true. Does this functionality still work via the Swagger UI? Is there any documentation on how to authenticate API calls (e.g. via CLI) with the latest version?

**To Reproduce**
1. Install the web API on Azure following the instructions [https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md](https://github.com/Azure/Industrial-IoT/blob/main/docs/web-api/readme.md)
2. Open [appname].azurewebsites.net/swagger
3. Click on "Try it out" on any method e.g. GET registry/v2/applications
4. Response is code 401. 

**Expected behavior**
Swagger UI would request authentication and use the token in "Try it out" API calls.

**Desktop (please complete the following information):**
- Edge browser on Win10

**Comment by marcschier** [comment]
Unfortunately we need to remove swagger UI due to security issues (2.9.4 - change is already in main) and cannot ship any more containers with it.  Therefore closing wont fix.
