### ISSUE TITLE
SiteId placeholder is not working in TelemetryTopicTemplate using Dapr transport

### ISSUE THREAD

**Issue by Haeavar** [Azure/Industrial-IoT#2161]
**Describe the bug**
If I set the --SiteId commandline parameter to "xyz" and use it in the --TelemetryTopicTemplate commandline parameter like "events.{SiteId}.{PublisherId}" it does not get replaced. Its still SiteId. PublisherId works as expected.

**To Reproduce**
1. Set commandline parameters to
 --SiteId=xyz
 --PublisherId=0815
 --TelemetryTopicTemplate=events.{SiteId}.{PublisherId}
--DefaultTransport=Dapr
2. Run OpcPublisher

**Expected behavior**
The message topic should be "events.xyz.0815" but is "events.SiteId.0815"

**Additional context**
Using mcr.microsoft.com/iotedge/opc-publisher:2.9.4-preview3

**Comment by marcschier** [comment]
Fix will be in preview4.
