### ISSUE TITLE
Potential data loss on publisher restart

### ISSUE THREAD

**Issue by filipzanpwccom** [Azure/Industrial-IoT#2168]
I'm using publisher that publishes messages to MQTT broker.

Scenario I'm testing:
0. Setup communication between OPC Publisher and MQTT broker.
1. Stop MQTT Broker.
2. Wait some time and allow some messages to be collected by publisher.
3. Stop OPC publisher.
4. Start OPC publisher.
5. Start MQTT Broker.

What happens is that all messages collected between steps 1. and 3. are lost.
When steps 3. and 4. are removed - no publisher restart - all messages that were collected during MQTT broker inavailability are delivered as soon as connection is established. 

I would like to know how, if possible, setup configuration of publisher to persist buffered messages for restart, so these can be delivered.

System information:
OPC Publisher: 2.9.2.1
OS: Ubuntu 22.04

**Comment by marcschier** [comment]
There is no persistence of messages in the internal data pipeline at the moment, anything in the pipeline at publisher crash is lost.  With IoT Edge you get persistence as long as EdgeHub is reachable.

We will put this in for a future version of OPC Publisher.
