### ISSUE TITLE
$$RoutingInfo property is added even when DataSetWriterGroup is not configured

### ISSUE THREAD

**Issue by jacqueskang** [Azure/Industrial-IoT#2177]
**Describe the bug**

In the [documentation](https://github.com/Azure/Industrial-IoT/blob/release/2.9.3/docs/opc-publisher/commandline.md) of `--EnableRoutingInfo` command line argument, it states:

> When the `DataSetWriterGroup` is not configured, the `$$RoutingInfo` property will not be added to the message even if this argument is set.

But actually if routing info is enabled without DataSetWriterGroup configured, `$$RoutingInfo` property is still added with value ` <<UnknownWriterGroup>>`

**To Reproduce**
1. Execute opc publisher with environment variable EnableRoutingInfo=true
2. Configure OPC nodes without DataSetWriterGroup
3. Capture message sent to IoT Hub

```json
{
  "body": [
    {
      "NodeId": "ns=2;s=RandomSignedInt32",
      "EndpointUrl": "opc.tcp://opc-plc-sim:50000/",
      "DisplayName": "ns=2;s=RandomSignedInt32",
      "Value": {
        "Value": 404002529,
        "SourceTimestamp": "2024-02-02T17:08:34.2213036Z"
      }
    },
    ...
  ],
  "enqueuedTime": "Fri Feb 02 2024 17:08:43 GMT+0000 (Coordinated Universal Time)",
  "properties": {
    "$$MessageSchema": "application/x-monitored-item-json-v1",
    "$$ContentType": "application/json",
    "$$ContentEncoding": "utf-8",
    "$$RoutingInfo": "<<UnknownWriterGroup>>"
  }
}
```

**Expected behavior**
Either "$$RoutingInfo" is not set as documentation states, or update the documentation.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: N/A
 - Version: 2.9.3

**Comment by marcschier** [comment]
Docs and help updated.
