### ISSUE TITLE
Docs mention HTTP API must use Bearer authentication whilst it is actually ApiKey

### ISSUE THREAD

**Issue by NoTuxNoBux** [Azure/Industrial-IoT#2187]
**Describe the bug**
[The documentation](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/readme.md#calling-the-api-over-http) mentions you must use `Bearer` authentication, but I keep getting 401 errors, even with the appropriate `__apikey__`.

**To Reproduce**
1. Execute `curl -k -i -X 'GET'  -H "Authorization: Bearer Test" 'https://publisher-ip:1234/v2/configuration'` where `Test` is your generated or set `__apikey__` and `publisher-ip:1234` is set to the HTTPS endpoint of your publisher.

**Expected behavior**
Documentation either informs you to use `ApiKey` instead:

```
curl -k -i -X 'GET'  -H "Authorization: ApiKey Test" 'https://publisher-ip:1234/v2/configuration'
```

... or `Bearer` authentication works.

**Versions**
OPC Publisher 2.9.4.

**Additional context**
`Security.ApiKeyScheme` seems to imply `ApiKey` is needed instead, and indeed this works.

**Comment by marcschier** [comment]
Docs fixed.
