### ISSUE TITLE
TopicTemplate and "Sub-Topics"

### ISSUE THREAD

**Issue by quality-leftovers** [Azure/Industrial-IoT#2190]
**Is your feature request related to a problem? Please describe.**
We would like to route some DataSetWriterGroup to a different nested topic path.

**Describe the solution you'd like**
We'd like to be able to define or override attributes that can be used in TopicTemplate in the configuration for each WriterGroup.

**Describe alternatives you've considered**
Using the {DataSetWriterGroup} in the topic template and setting it to something like "mytopicA/mySubTopicB" and "myTopicC/mySubTopicD" (in our case actually mytopicA.mySubTopicB since we are using DAPR + NATS) . This works but we are wondering whether this is officially supported or might "break" in future publisher versions.

=> Are there any restrictions that might be applied for DataSetWriterGroup in future versions of the publisher?

**Additional context**
-

**Comment by marcschier** [comment]
There should probably be a better way to do this.  Especially because part 14 permits mqtt topic path and query chars in names.

**Comment by Haeavar** [comment]
Hi @marcschier. I created a PR #2193  which address this issue. This PR will enable us to define different topics für each datasetwriter. Please let me know whether are you ok with the changes or if there some things missing. Thanks.

**Comment by marcschier** [comment]
In 2.9.5 (main branch) it is possible to set the topic per group, writer (and even at node level., but this is experimental). That way you should be able to accomplish what you want here.  Please be aware that support on this feature is only via GitHub.
