### ISSUE TITLE
Is this project licensed correctly?

### ISSUE THREAD

**Issue by mode777** [Azure/Industrial-IoT#2191]
This project states that is licensed under MIT license, while some of it's dependencies (e.g. [OPCFoundation.NetStandard.Opc.Ua.Core](https://www.nuget.org/packages/OPCFoundation.NetStandard.Opc.Ua.Core/1.5.373.121/License) ) might fall under GPL v2. 

I'm not an expert on software licenses but this seems to be disputed, at least according to [this stackexchange post](https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l). 

I think at least a disclaimer would be helpful here!

**Comment by marcschier** [comment]
It is correct.  We license the .net UA stavk to you under MIT.  As part of this project.
