### ISSUE TITLE
Return or log exception if publishednodes.json file is not writable

### ISSUE THREAD

**Issue by ivangajicc** [Azure/Industrial-IoT#2195]
**Is your feature request related to a problem? Please describe.**
The logs are not providing any warning nor error when json containing published nodes from opc publisher is not writable and only indicator is response 500 with null payload. This could lead in long debugging time to find source of problem.

**Describe the solution you'd like**
Logs should raise that published nodes file is not writable or at least 500 return payload should clearly state the problem.

**Additional context**
![image](https://github.com/Azure/Industrial-IoT/assets/33852380/55875f8b-15ce-498e-b481-3a6ec504a08c)
-> Additionally no warning and errors inside logs of OPC publisher module. Logs were stating that everything went fine. Log level of OPC publisher was **debug**.

In our case the file was owned by Root (read and write for root but readable for all users) while module was running asp app user.

Thank you for developing this great tool.

**Comment by marcschier** [comment]
Thanks 👍.  Surprising that file write errors are not logged.  I will make sure that errors are logged.  What we can do about response code I need to see since the service is decoupled from persisting.

**Comment by marcschier** [comment]
This is now fixed. The exception message is now the payload returned plus a status code.
