### ISSUE TITLE
The 'v2/configuration/diagnostics' contains negative monitoredOpcNodesSucceededCount

### ISSUE THREAD

**Issue by Haeavar** [Azure/Industrial-IoT#2202]
**Describe the bug**
The property `monitoredOpcNodesSucceededCount` contains a negative number if no node could be subscribed.

**To Reproduce**
1. Configure multiple subscriptions (DataSetWriters) with available endpoint but not available nodes
1.1. `condition-s179` with 1 event condition, 
1.2. `event-s179` with 1 event
1.3. `data-default` with 27 nodes
1.4. `data-opcgateway`  with 2 nodes

2. POST {{ _.BaseUrl }}/v2/configuration/diagnostics

See following response (relevant part of the model). Its the same for each of the 4 dataSetWriters
		"opcEndpointConnected": true,
		"monitoredOpcNodesSucceededCount": -29,
		"monitoredOpcNodesFailedCount": 31,

**Expected behavior**
I would expect separate values for each dataSetwriter with following values (relevant part of the model) 

"DataSetWriterId": "condition-s179"
		"opcEndpointConnected": true,
		"monitoredOpcNodesSucceededCount": 0,
		"monitoredOpcNodesFailedCount": 1,

"DataSetWriterId": "event-s179"
		"opcEndpointConnected": true,
		"monitoredOpcNodesSucceededCount": 0,
		"monitoredOpcNodesFailedCount": 1,

"DataSetWriterId": "data-default"
		"opcEndpointConnected": true,
		"monitoredOpcNodesSucceededCount": 0,
		"monitoredOpcNodesFailedCount": 27,

"DataSetWriterId": "data-opcgateway"
		"opcEndpointConnected": true,
		"monitoredOpcNodesSucceededCount": 0,
		"monitoredOpcNodesFailedCount": 2,

For the `/metrics` there are some wrong information as well

`iiot_edge_publisher_bad_nodes`

0 for the event-s179 (I would exepect 1)
0 for the condition-s179 (I would exepect 1)
27 for the data-default - thats okay
2 for the data-opcgateway - thats okay

`iiot_edge_publisher_good_nodes`

1 for the event-s179 (I would exepect 0)
1 for the condition-s179 (I would exepect 0)
0 for the data-default - thats okay
0 for the data-opcgateway - thats okay

**Additional context**
image: mcr.microsoft.com/iotedge/opc-publisher:2.9.4

**Comment by marcschier** [comment]
Diagnostics is at the writer group level (for historical reasons and because most other info only makes sense for writer group (e.g. messages sent)).  The numbers for the writers are an aggregate or average across all writers in the group.

**Comment by marcschier** [comment]
This should be fixed already in 2.9.8, there was some miscalculation in the bad count, but for double safety I am at least ensure it is positive. (#2255)
