### ISSUE TITLE
Make TransferSubscriptionsOnReconnect configurable (via publishednodes.json)

### ISSUE THREAD

**Issue by steffenbeermann** [Azure/Industrial-IoT#2205]
**Is your feature request related to a problem? Please describe.**
We recently changed to 2.9 version of the opc publisher and since than we had a problem with one of our connection to one OPC UA Server. After some investigation we found that the OPC UA Server does not support the TransferSubscriptionsRequest and crashes when the OPC Publisher sends this request. In the OPC UA Publisher 2.9 you introduces the transfer subscription on reconnect feature. 

**Describe the solution you'd like**
Be able to configure the TransferSubscriptionsOnReconnect for each endpoint in the publishednodes.json. E.G:
`    "UseTransferSubscriptionsOnReconnect": true,
`
**Describe alternatives you've considered**
For now we need to deploy the OPC Publisher in Version 2.8 for this one OPC UA Server.

**Additional context**

**Comment by marcschier** [comment]
That should be easy to add. We would opt for "DisableTransferSubscriptions": true, if that is ok.  We would like to keep this on by default.  Either it should be failing and then we fall back, or it works.  It should not crash the server, so best to also talk to the server vendor in the meantime.

**Comment by steffenbeermann** [comment]
Thank you for your reply! "DisableTransferSubscriptions" would be completely fine for us. We are in contact with the supplier of the OPC Server but atm they only offer a small subset of OPC Services in their client and we could troubleshoot it down to the TransferSubscriptionRequest. But we are not sure if they can or will implement it.

**Comment by marcschier** [comment]
New option "dtr|disabletransferonreconnect" or "DisableSubscriptionTransfer": true in published nodes configuration.

**Comment by steffenbeermann** [comment]
Thank you very much for the quick implementation. We already rolled it out and it seems to have solved our problem!

**Comment by marcschier** [comment]
Also in 2.9.8, just released to MCR.
