### ISSUE TITLE
Deadband in OPC Publisher

### ISSUE THREAD

**Issue by FMauroy** [Azure/Industrial-IoT#221]
Hello, are there plans to allow setting deadband values for each monitored OPC node in OPC Publisher? Our customer would like to avoid sending values that do not change more than a fixed/relative range of values...
I see in the UA API that deadband settings exist, but they are not used in OPC Publisher.
Thanks a lot!

**Comment by marcschier** [comment]
Hi @FMauroy  - preview (i.e. master) supports deadband and other filter settings, however, there is no API yet to control this - either through REST or the legacy publishednodes.json file.   This is on our backlog.   Keeping this as feature item to track

**Comment by FMauroy** [comment]
Thanks for your quick reply. We'll wait then, no problem.
Keep up the good work :-)

**Comment by pratson20** [comment]
Hi @marcschier , i am also looking for dead-band functionality as well. is that support available now?

Also OPC publisher to support synchronous communication?

Regards,
Prateek
