### ISSUE TITLE
How to include NodeId in PUBSUB message

### ISSUE THREAD

**Issue by RollsChris** [Azure/Industrial-IoT#2211]
Hi, I'm trying to understand how to add extra info to the returned messages using the PUBSUB format, I  know there is a concept of DataSetFieldContentMask but i cant see how to use it?

Currently its only returning the DisplayName but we also want the NodeId.. this was included in the SAMPLES format.

Any suggestions thanks

**Comment by marcschier** [comment]
If you don't set a display name for the node it should use the node Id as key of the dataset.  Provided the fetch display name option is not configured either in the config json' or command line.

**Comment by RollsChris** [comment]
If thats the case I feel pretty stupid. Thanks for the reply.

**Comment by marcschier** [comment]
No no, try it out let me know it works as expected.  It is not entirely obvious.
