### ISSUE TITLE
Wrong template names shown in docs

### ISSUE THREAD

**Issue by RollsChris** [Azure/Industrial-IoT#2224]
**Describe the bug**
Wrong template variables names used in documentation:

For example these do not work:
`{DataSetWriter}` 
`{WriterGroup}`

But these do:
{DataSetWriterGroup}
DataSetWriterId

**To Reproduce**
Look at docs and try for yourself

**Expected behavior**
To be correct

**Screenshots**
![image](https://github.com/Azure/Industrial-IoT/assets/6059035/1a524a73-3aba-4218-8615-89bff494ab9c)

**Comment by marcschier** [comment]
You were using an older version of OPC Publisher, but the help reflects current main line state, these are the new names in the doc corresponding to the latest version of OPC Publisher, but the older template names also work in newer versions of OPC Publisher.

**Comment by RollsChris** [comment]
Hey we are using 2.9.6.4+978a207cf9 which also appears to be the latest? but yes i can see in the docs is using 2.9.8 has that bee released yet?

**Comment by marcschier** [comment]
Mmmmh.  Surprisingly, the end to end tests pass with the new and old variable names.  2.9.8 just released, let's re-open if the issue persists.
