### ISSUE TITLE
Security mode "Best" not persisting after Opc Publisher is restarted

### ISSUE THREAD

**Issue by ivangajicc** [Azure/Industrial-IoT#2228]
**Describe the bug**
Selecting "Best" Endpoint Security Mode does not persist with restarts or after publising new nodes for endpoints that have None as highest security level.

What I observed is for different Endpoint security modes we decide to persist or not them in publishednodes.json.
Combinations (publish payload vs publishednodes.json):
"EndpointSecurityMode": "Best" -> No SecurityMode persisted in json and UseSecurity: true
"EndpointSecurityMode": "SignAndEncrypt" -> No SecurityMode persisted in json and UseSecurity: true
"EndpointSecurityMode": "Sign" -> EndpointSecurityMode : “Sign” and UseSecurity: true
"EndpointSecurityMode": "None" -> No SecurityMode persisted and UseSecurity: false

That leads to initial publish being correct (when we want to use "best available mode") and deciding that the best mode is "None" and connection gets established but when Opc Publisher is restarted it tries to connect to that endpoint not by using "Best" available mode but "SignAndEncrypt".

**To Reproduce**
1. Go to Azure Portal and invoke PublishNodes_V1 against OPC Publisher for node that has only None security endpoint, but set in payload EndpointSecurityMode as Best. E.G.:
![image](https://github.com/Azure/Industrial-IoT/assets/33852380/f43f1760-4005-4030-be3d-3fb7e7d23d88)
2. Go to Opc Publisher logs and check them. We can clearly see that opc publisher decided to use None security as higher level is not available and got connection established.
![image](https://github.com/Azure/Industrial-IoT/assets/33852380/eb49b788-9a25-4b4d-8293-8d5ce33810b5)
3. Now restart Opc Publisher or publish again different node for same endpoint (make Opc Publisher to read from publishednodes.json)
4. We can clearly see that now even if configuration was not changed Opc Publisher is trying to connect by using SignAndEncrypt which is not available and leads to data flow stoppage.
![image](https://github.com/Azure/Industrial-IoT/assets/33852380/5f4bf7e4-1d9b-4dec-87b9-a27c41b7f6c7)

**Expected behavior**
Opc Publisher after restart or when publishing new nodes for same endpoint should again try to use Best available security mode and not sign and encrypt.

Opc Publisher version is 2.9.6

Thank you for developing this great tool.

**Comment by marcschier** [comment]
UseSecurity now correctly reflected by "SecurityMode.NotNone" (Sign|SignAndEncrypt) while Best is still "any". There Best should now be persisted and used correctly.  But it is not advisable, better use a OPC UA defined mode.
