### ISSUE TITLE
Feature to have Status code of monitored item value in message show the server is disconnected/subscription down.

### ISSUE THREAD

**Issue by marcschier** [Azure/Industrial-IoT#2232]

**Comment by florianbader** [comment]
The need for this feature came up when discussing a heartbeat. We want to have a regular heartbeat but also want to know not just the last known value that OPC publisher received from the OPC UA server but additionally the current server, subscription and node state to know if we can trust the last received value.

Use case 1 for this feature is that if we configure a heartbeat interval there is no way to know if the value, we received from the heartbeat is just the last cached one and the OPC UA server or subscription went down in the meantime. It would be nice to know from the heartbeat message the current server status so we can make a decision if we want to use the value or not.

Use case 2 for this feature is when using cyclic reads and the OPC UA server or subscription went down we are not getting any update. It would be nice to get at least a "keep alive" cyclic read with no value and an error code.

**Comment by marcschier** [comment]
In 2.9.8 we will send UncertainNoCommunicationLastUsableValue or BadNoCommunication errors while we handle reconnection of session. The first good value received after - or a recovered session will produce values with a new or the original status codes (respectively) again.  

Changing cyclic reads to report an error code will come later.

**Comment by marcschier** [comment]
@florianbader - I checked the code and a session disconnect (and all other read errors) are forwarded as messages with status value set to the status code.  Since heartbeat now also signals a disconnect status, I would close this as fixed in 2.9.8.  If you cannot get the desired functionality out of the 2.9.8 release, please let me know.
