### ISSUE TITLE
Heartbeat functionality to update the Timestamp after the restart

### ISSUE THREAD

**Issue by khushigarg12** [Azure/Industrial-IoT#2237]
**Is your feature request related to a problem? Please describe.**
When the OPC publisher is restarted, the data being published retains the timestamp from the last received value from the OPC server before the restart. Although the heartbeat functionality updates the timestamp when no new data is received, a publisher restart causes the timestamp to revert to the last known value from the OPC server, creating discrepancies in the data stream.

**Describe the solution you'd like**
Upon restarting the publisher, the data should continue to be published with the current timestamp, maintaining continuity and accuracy even after a restart.

**Additional context**
![image](https://github.com/Azure/Industrial-IoT/assets/145097016/0b3fb283-baa2-4dbf-9094-aa1021f02f8c)
In the image, the OPC server stopped sending data at 15:09 (marked in red). The heartbeat functionality continued to publish data with updated timestamps. However, after the publisher was restarted at 15:12, the timestamps reverted to 15:09, which was the last value sent by the server before it stopped.

This feature request aims to ensure that even after a publisher restart, the data reflects the current timestamp.

**Comment by marcschier** [comment]
This will not be possible.  OPC Publisher does not persist any state during restart.  

If the value has not changed on the server, then after restart of OPC Publisher the server's first value change it reports will have any source/server timestamp that it wants.  If the value has not changed during restart, then publisher will start from the provided source timestamp.  

Heartbeats are artificial messages, they do not reflect the state of the server/backend.  2.9 tried to fix the issues by repeating the value including the original timestamps.  However, feedback was that in 2.8 the timestamps changed (they were changed on the publisher side, counting up every heartbeat), so we added the new --hbb behavior.  However, this is the result of it, and the only recommendation I have is to use the default --hbb behavior.
