### ISSUE TITLE
Telemetry messages are sent as expired with DAPR >= 1.13

### ISSUE THREAD

**Issue by Haeavar** [Azure/Industrial-IoT#2243]
**Describe the bug**

With DAPR 1.13 the cloud event with an `expiration` of current time is generated. This results in dropped messages for the consumer.
`
{"data":{"DataSetWriterGroup":"...","MessageId":"7b62f07f-9d77-4ce1-8345-61c9aa0c778e","MessageType":"ua-data","Messages":[...],"PublisherId":"..."},"datacontenttype":"application/json","expiration":"2024-06-11T11:34:38Z","id":"d12bf749-1ecb-4c4a-b5f1-e3af05cbb63d","pubsubname":"pubsub-opcpublisher","source":"opc-publisher-dapr","specversion":"1.0","time":"2024-06-11T11:34:38Z","topic":"....","traceid":"00-39473039ef2d9c02543ac09c85cc6c71-56af98ef21dd0504-01","traceparent":"00-39473039ef2d9c02543ac09c85cc6c71-56af98ef21dd0504-01","tracestate":"","type":"com.dapr.event.sent"}
`

**To Reproduce**
1. Use DAPR sidecar with version 1.13
2. Start publisher with at least following settings:
    - DaprConnectionString=PubSubComponent=pubsub-opcpublisher;GrpcPort=6011;
    - DefaultTransport=Dapr

**Expected behavior**
No expiration is set

**Additional context**
In the `NetworkMessageEncoder` the `Encode` calls the IEvent.SetTtl() with a default(TimeSpan) of 00:00:00. This is evaulated as a ttl of 0 and the `expiration` attribute of the cloud event is set appropriate.

image: mcr.microsoft.com/iotedge/opc-publisher:2.9.6

**Comment by marcschier** [comment]
Thanks for the fix, will be in 2.9.8
