### ISSUE TITLE
How to configure username/password based OPC UA Authentication when using orchestrated mode with the version 2.8?

### ISSUE THREAD

**Issue by emulic** [Azure/Industrial-IoT#2247]
We need to connect to an OPC UA Server using username/password based authentication.
We run the version 2.8.6 in orchestrated mode and we can't figure out, how to configure username/password to be used after discovery to browse and subscribe nodes in Engineering tool and later at the runtime for publisher module to publish the node value changes.
We tried to use the "Asset login" function in engineering tool:
![image](https://github.com/Azure/Industrial-IoT/assets/19528729/15f92835-14b6-47ef-8fdb-db16a9dc1d25)
However, even when registering an OPC UA Endpoint after logging in in "Asset login" we are not able to browse the nodes.
After turning on an endpoint, we see the Endpoint state "Unauthorized":
![image](https://github.com/Azure/Industrial-IoT/assets/19528729/8e38cbdb-0149-47f4-9239-e6ea6e8db17b)
After clicking on the Endpoint Url link for the activated Endpoint, we are getting an error saying "Cannot browse node """:
![image](https://github.com/Azure/Industrial-IoT/assets/19528729/e5c5dc0c-0970-45ef-b2ca-66b45d22fffe)
After that, the Endpoint Url is not clickable any more and the EndpointState is "NoTrust".

Is there another way how to provide the username/password based configuration to the publisher module in orchestrated mode? 
We also checked the registry API and the Endpoints operations there but haven't found any applicable to set the authentication configuration for the endpoint. 

Can you please help on this topic and show us a way how to configure OPC UA username/password based authentication for publisher in orchestrated mode in v. 2.8.6.

**Comment by marcschier** [comment]
2.8 is not supported anymore.  The UI etc. require 2.8 version of the API which is not entirely backwards compatible.
