### ISSUE TITLE
Allow configuring message TTL on DatasetWriterGroup level

### ISSUE THREAD

**Issue by quality-leftovers** [Azure/Industrial-IoT#2278]
**Is your feature request related to a problem? Please describe.**
Publisher supports configuring multiple transports and topics, but all transports and topics currently show a "global" TTL.

Since multiple subscribers have different requirements for message TTL  it would be great, if we could configure message TTL on WriterGroup level.

**Describe the solution you'd like**
Have a "TTL" option for WriterGroup in configuration API  `WriterGroupQueueName` (`WriterGroupMessageTTL`?)

**Describe alternatives you've considered**
Running multiple publishers with different TTLs

**Additional context**
n.a.

**Comment by marcschier** [comment]
Added this #2279 and #2282.  Gated on the other issue to enable ttl on mqtt.
