### ISSUE TITLE
The key / environment variable MaxPublishRequests does not work as expected

### ISSUE THREAD

**Issue by dimtix** [Azure/Industrial-IoT#2289]
**Describe the bug**
The key / environment variable MaxPublishRequests seems to have no impact on the publisher behaviour.

**To Reproduce**
1. Start publisher via docker compose without this variable (default value) and with diffent values of this variable
2. Configure publisher with appropriate configuration 
4. Check the value of CurrentPublishRequestsInQueue for the publisher session in the server with any client (e.g. UaExpert)
5. The value of CurrentPublishRequestsInQueue is allways equal to the number of created subscriptions independent of the value of MaxPublishRequests 

**Expected behavior**
CurrentPublishRequestsInQueue == MaxPublishRequests 

**Screenshots**
**1**
<img width="432" alt="image" src="https://github.com/user-attachments/assets/30f4eab4-c4bf-41d3-85c9-0b00aec36bfa">
<img width="898" alt="image" src="https://github.com/user-attachments/assets/836b09d4-6aa9-4381-81f6-a14ce0bd7f1b">

**2**
<img width="424" alt="image" src="https://github.com/user-attachments/assets/68ab0228-9197-44cf-bb8e-d924d54f106e">
<img width="911" alt="image" src="https://github.com/user-attachments/assets/4fd7de3a-ecf3-4047-882e-0af7d7e4d92a">

**3**
<img width="436" alt="image" src="https://github.com/user-attachments/assets/67bd73dd-0a70-4f0b-ad57-dc9793e86f4f">
<img width="902" alt="image" src="https://github.com/user-attachments/assets/2aa7dc1e-c793-4634-8960-17f3c148e3e6">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 2.9.9

**Comment by marcschier** [comment]
Unfortunately this also requires a change in the UA stack, which overrides the max setting and always at least submits subscription count publish requests.  Hence this will take a bit of time.

**Comment by marcschier** [comment]
#2352
