### ISSUE TITLE
Direct Method SetConfiguredEndpoints not working with nodes defined by BrowsePath

### ISSUE THREAD

**Issue by kenrena** [Azure/Industrial-IoT#2311]
**Describe the bug**
Calling directmethod SetConfiguredEndpoints with the nodes defined with BrowsePath instead of Id yield 500.

**To Reproduce**
1. Go to the azure portal
2. Invoke direct method SetConfiguredEndpoints
with the payload：
{
    "endpoints": [
        {
            "EndpointUrl": "opc.tcp://xxxx.com:4897/Softing/dataFEEDSIS/Server",
            "UseSecurity": false,
            "OpcNodes": [
                {
                    "BrowsePath": [
                        "Objects",
                        "Server",
                        "LocalTime"
                    ]
                 }
            ]
        }
    ]
}
3. Get 500 (See error)
4. Change the payload to 
{
    "endpoints": [
        {
            "EndpointUrl": "opc.tcp://xxxx.com:4897/Softing/dataFEEDSIS/Server",
            "UseSecurity": false,
            "OpcNodes": [
                {
                    "ExpandedNodeId": "i=17634 [Server_LocalTime]"
                }
            ]
        }
    ]
}
5. Got 200 as reponse

**Expected behavior**
Endpoints together with the nodes are correctly updated.

**Screenshots**
![image](https://github.com/user-attachments/assets/9783e846-bfa9-40e0-abf7-4872f7995417)

**Environment (please complete the following information):**
 - OS: linux
 - OPcpublisher Version 2.9.9

**Comment by marcschier** [comment]
Please use 2.9.10, this was fixed there - I just tested it.
