### ISSUE TITLE
Heartbeat publishing wrong values at wrong time

### ISSUE THREAD

**Issue by kappa-lhirsch** [Azure/Industrial-IoT#2313]
**Describe the bug**
Using WebApi V2.9.10 and Publisher-Module V2.9.10
When using a heartbeat interval on a node, to publish values even when no new values are available, I get a weired behavior.
I'm using PeriodicLKG  HeartbeatBehavior.

### Case 1
Setup:
* Node1, PublishingInterval, SampleInterval and HeartbeatInterval all set to 30 seconds, Value never updated
* Node2, PublishingInterval, SampleInterval set to 30 seconds, no HeartbeatInterval, Value is updated every second

![image](https://github.com/user-attachments/assets/eb115eb5-94a8-40b1-a39e-e70b53e10a89)

When the Heartbeat of Node1 happens at the same time as Node2 get published, the value of Node2 becomes automatically 1. Afterwards the Heartbeat of Node1 doesn't happen at the same time as the others get published and the behavior is as expected.

### Case 2
Setup:
* Node1, PublishingInterval, SampleInterval and HeartbeatInterval all set to 30 seconds, Value never updated
* Node2, PublishingInterval, SampleInterval and HeartbeatInterval all set to 30 seconds, Value is updated every second

![image](https://github.com/user-attachments/assets/c30d0eba-4cfc-425d-af2f-466f1af8b328)

Now that Node2 also has a HeartbeatInterval set, every HeartbeatInterval an additional value, again 1, from Node2 is published.

### Case 3
Setup:
* Node1, PublishingInterval, SampleInterval set to 30 seconds, no HeartbeatInterval, Value never updated
* Node2, PublishingInterval, SampleInterval and HeartbeatInterval all set to 30 seconds, Value is updated every second

![image](https://github.com/user-attachments/assets/f8c91770-9abc-44fd-9cbf-7599ead410e7)

Now the Heartbeat-Value isn't 1 anymore and it is the last published value, which is correct. But why do I even get a Heartbeat when the last published value was only 20 seconds ago and the HeartbeatInterval is set to 30 seconds.

This whole Heartbeat thing is acting completely unreliable. Why does one value influence the other value to become 1 and why do I even get Heartbeats from the other value.

**To Reproduce**
1. See above

**Expected behavior**
Heartbeats are only published when no new value is available. Nodes don't influence other nodes.

**Comment by marcschier** [comment]
Can you provide sample configuration Json for case1,2,3?  Also, can you provide info what you are expecting?  Especially about PeriodicLKG behavior?

**Comment by marcschier** [comment]
@kappa-lhirsch , could you try with mcr.microsoft.com/iotedge/opc-publisher:2.9.11-preview1 and let me know if this is resolved for you?` If not, please see my previous comment.
