### ISSUE TITLE
How to perform a browse of all nodes under a specific node?

### ISSUE THREAD

**Issue by dplumm2** [Azure/Industrial-IoT#2315]
We recommend that you implement a two step approach to achieve this:
1) browse all nodes under a specific node and generate a publishing configuration for OPC Publisher out of the browse results
2) configure OPC Publisher with this list

Is there any documentation to perform this operation?  I can see info wrt the API, but theres no quick start or tutotial to run the API.  Is there a way I can run the web api standalone without all the Industrial IOT deployment.  I have most of the parts I need for an IoT Solution, but am struggling to understand how to run the API.

Thanks

**Comment by marcschier** [comment]
OPC Publisher can be run standalone (examples can be found in the [deploy](https://github.com/Azure/Industrial-IoT/tree/main/deploy) folder, e.g., running in IoT Edge (fully supported), and running in docker compose (preview) and it has a REST API which also supports [browse](https://github.com/Azure/Industrial-IoT/blob/main/docs/opc-publisher/api.md#browse).  An example can also be found [here](https://github.com/Azure/Industrial-IoT/blob/main/samples/Http/BrowseAll).  See the other samples in the same folder for more information.

An API to configure the published nodes .json file (configuration api) from an object node or recursively has been a request (#1320) on our backlog for a long time, and it is something I see as a great value in, too.
