### ISSUE TITLE
Heartbeat Issue

### ISSUE THREAD

**Issue by e-augusto** [Azure/Industrial-IoT#2335]
Sometimes a day the publisher publishes null data for no real reason. It seems to me like a heartbeat error, as if it "lost" its time. And it happens with tags that keep the same value for a long time, such as a machine running status. Honestly, I think we should just ignore these records, but I'm being pressured to fix these holes.  Do you have any suggestions?

Thanks!

![Print 1](https://github.com/user-attachments/assets/075cda48-d858-47b2-b74c-3be23c5fb203)

![Print 2](https://github.com/user-attachments/assets/15acefff-b2ee-4dcd-a87b-fc8e05fa5b90)

![Print 3](https://github.com/user-attachments/assets/254fa584-5f1e-4700-96e3-f11ef49f09d8)

**Comment by marcschier** [comment]
From which version was this publisher forked?  I see a version 7.0.2 which is unknown.

**Comment by e-augusto** [comment]
I don't understand much about installing opc Publisher, but when I use the list command in Linux, this is the version that appears.



![Print 5](https://github.com/user-attachments/assets/5b4ed80b-89a5-4906-abaf-b4c3fd8ebb1c)

**Comment by marcschier** [comment]
@e-augusto, would love to help, but I dont know anything about this version / product - this is not a OPC Publisher supported via this repository/github project, please follow up with the person/company/developer you or your company obtained it from to have them address the issue you are facing.  

The latest version of OPC Publisher in this repo is mcr.microsoft.com/iotedge/opc-publisher:2.9.11.  Which is also the only version supported via support path ([see here](readme.md)).
