### ISSUE TITLE
Doc refining request  (https://azure.github.io/Industrial-IoT/opc-publisher/api.html)

### ISSUE THREAD

**Issue by zh0903** [Azure/Industrial-IoT#2348]
In  https://azure.github.io/Industrial-IoT/opc-publisher/transports.html
"Direct methods can be used to interact with the OPC Publisher configuration, discovery, and Twin API. "
But not mentioned direct method support General category API

In https://azure.github.io/Industrial-IoT/opc-publisher/api.html ,
no Twin API was introduce.

**Comment by marcschier** [comment]
#2352
