### ISSUE TITLE
Response Compression in Publisher Rest API (Accept-Encoding gzip)

### ISSUE THREAD

**Issue by quality-leftovers** [Azure/Industrial-IoT#2350]
**Is your feature request related to a problem? Please describe.**
We are currently querying publisher REST API endpoints like /metrics and /diagnostics of remote publisher instances.
We've observed reponse sizes of 700 KiB for /metrics and roughly 100 KiB for /diagnostics.

To reduce latency and bandwith requirements when querying remote publisher instances we'd like to use response compression (using Accept-Encoding) header. 

We'd only be using it over publisher http endpoint.

**Describe the solution you'd like**
If possible we'd like to see Response Compression Middleware in Publisher ASP .NET Core to be activated.
See: https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-8.0

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddResponseCompression(options =>
{
    options.EnableForHttps = true;
});

var app = builder.Build();
app.UseResponseCompression();
app.MapGet("/", () => "Hello World!");
app.Run();
```

**Describe alternatives you've considered**
(Reverse) Proxy that handles compression.

**Additional context**
n.a.

**Comment by marcschier** [comment]
#2352
