### ISSUE TITLE
Publish all nodes of a connected OPC server

### ISSUE THREAD

**Issue by frieste14** [Azure/Industrial-IoT#2354]
We currently have the situation where we have connected some OPC servers to the publisher where we want to publish all nodes of the server. This is because in some OPC servers we can configure the exposed nodes. In this case it would make life much easier if the publisher would just publish every node in the connected OPC server.
It would be great if there was an option in the configuration file (eg. publishAllNodes) that allows publishing the whole endpoint eg:
{
  "EndpointUrl": "opc.tcp://someIPAdress:4840",
  "UseSecurity": "true",
  "publishAllNodes":"true"
  "rebrowsInterval":"60"
}

If we add some new nodes to the server it would be great if the publisher would automatically detect the new nodes in this endpoint and publish them as well. 
This could be achived with an periodical browse request (eg rebrowsInterval in seconds).

**Comment by Haeavar** [comment]
It would be great if this could be configured (as well) on node base. For https://umati.org/industries_machine-tools/ there comes dynamic nodes and it would be complicated to adjust the subscriptions. With this features, we could subscribe to "Tools" and all child nodes which will become available.

**Comment by marcschier** [comment]
This already exists in the API surface, we just added the feature recently.  But the init file support will allow to do this at startup time also.  What is more you can subscribe now to all objects of a specified object type, so all cutting tools, etc.

Agreed, needs updated documentation.

**Comment by marcschier** [comment]
#2358.  Will be in 2.9.12.  Dynamic nodes however are not supported.  Here we might need to more thinking through
