### ISSUE TITLE
Send ExtensionFields in all messages

### ISSUE THREAD

**Issue by hvetter-de** [Azure/Industrial-IoT#2360]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the following issue I created last year https://github.com/Azure/Industrial-IoT/issues/2091.
We need the ExtensionFields to get send on every message.

**Describe the solution you'd like**
In the existing issue @marcschier suggested a new configuration for packing ExtensionFields into all messages that are sent. This feature would really help us in our current project, because the approach with using the KeyFrames doesn't fits our needs. We only need the Nodes which have been changed and the ExtensionFields. Sending all Nodes in every message, even if they did't change is breaking our solution.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by marcschier** [comment]
Imo this should be the default. No cfg needed.  And should be something that can be done in next release.
