### ISSUE TITLE
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.

### ISSUE THREAD

**Issue by jmbrunskill** [Azure/Industrial-IoT#257]
**Describe the bug**
OPC Publisher is reporting an exception when trying to publish messages to EdgeHub

`[20:28:37 ERR] Exception while sending message to hub. Dropping message...
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: t
   at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at OpcPublisher.HubCommunicationBase.MonitoredItemsProcessorAsync(CancellationToken ct) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\HubCommunicationBase.cs:line 1752`

This seems to be correlated with the message queue limit being reached?

`[20:34:57 INF] The internal monitored item message queue is above its capacity of 250000. We have already lost 63260000 monitored item notifications:(`

**To Reproduce**
_Unsure_

**Expected behavior**

**System Info:**
 - OS: Ubuntu
- IoT Edge 1.0.8.4
- OPC Publisher 2.5.2

**Comment by markusstuhler** [comment]
Hi @jmbrunskill 

this has been fixed in version 2.5.3. Therefore, I'm closing this issue.

Thanks!
Markus
