### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by rowenwu** [Azure/Industrial-IoT#270]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-deploy-local.md'
2. Click on 'Run the Industrial IoT modules locally'
3. Routed to 'https://github.com/Azure/Industrial-IoT/blob/master/docs/howto-install-iot-edge.md.'
4. See 404 error

**Expected behavior**
Routed to a docs page called 'Run the Industrial IoT modules locally'

**Comment by marcschier** [comment]
#274
