### ISSUE TITLE
Include swagger json

### ISSUE THREAD

**Issue by tbn-mm** [Azure/Industrial-IoT#3]
Hello,

I would like to use the swagger code generation, but there are no json-files. According to [.gitignore](https://github.com/Azure/azure-iiot-components/blob/1540d4ee94eda04adbce9761ad01b9e775e71c99/.gitignore#L27) there are some files. Could you please upload them? In this way, [generated folder](https://github.com/Azure/azure-iiot-services-api/tree/master/generated) is no more required in git (6MB of unused code).

Thanks.

**Comment by marcschier** [comment]
Done as part of #25.   You find the most recent swagger.json files for each service in https://github.com/Azure/Industrial-IoT/tree/master/api/swagger,
