### ISSUE TITLE
Where does setup script pickup the userid ? 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [Azure/Industrial-IoT#312]
Environment 
Windows 10 
PowerShell 

I am trying to install the IIOT in a powerShell.  And receiving the error below. 
Where is the setup script picking up the user miwilcox vs mike.wilcox ?  

.\setup 

One or more errors occurred.: User 'miwilcox@microsoft.com' returned by service does not match user
'Mike.Wilcox@microsoft.com' in the request
At C:\Users\miwilcox\Industrial-IoT\deploy\scripts\aad-register.ps1:346 char:9
+         throw $ex
+         ~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], AadAuthenticationFailedException
    + FullyQualifiedErrorId : One or more errors occurred.: User 'miwilcox@microsoft.com' returned by service does not
    match user 'Mike.Wilcox@microsoft.com' in the request

**Comment by marcschier** [comment]
Duplicate to #217 .  Please add additional data to the original issue.
