### ISSUE TITLE
Cannot add Kepware server application when it is remote from the IoT Edge Runtime

### ISSUE THREAD

**Issue by pc-avatar-7076** [Azure/Industrial-IoT#319]
**Describe the bug**
When Kepware (TKS) is installed on a Windows 10 VM (same network / resource group as IoT Edge RT VM) then "add application" fails. 

**To Reproduce**
1. Deploy the IIoT 2.6 stack, including an edge with 2.6 modules
2. Install Kepware (TKS) on a Windows 10 VM in the same resource group
3. Update the Kepware configuration to expose a discovery URL to the network
4. Use Postman (or the Swagger client) to invoke AddApplication. 
5. The Kepware TKS server never appears in the list of applications. 

**Expected behavior**
The remote TKS server can be added

**Screenshots**

This illustrates a connection config using UA Expert:

![ua-expert-fqdn](https://user-images.githubusercontent.com/43643709/76798281-ac86c680-67a5-11ea-9dcf-0227f7405b70.PNG)

This shows UA Expert connected using this configuration. UA Expert is running on my host in this example (the TKS server is running on an Azure hosted Windows 10 VM):

![ua-expert-connected](https://user-images.githubusercontent.com/43643709/76798204-86f9bd00-67a5-11ea-923a-0257db7bfc74.PNG)

Here is the Kepware discovery URL configuration. Note the hostname is not fully qualified:

![kepware-tks-configuration](https://user-images.githubusercontent.com/43643709/76798325-c45e4a80-67a5-11ea-9f78-7735e855b861.PNG)

Here is Postman initiating the AddApplications call using "no security":

![postman-add-application](https://user-images.githubusercontent.com/43643709/76798407-e952bd80-67a5-11ea-8a32-53f2e807da29.PNG)

Finally, here is the discovery module output:

![discovery-logs-zero-discovery-urls](https://user-images.githubusercontent.com/43643709/76798440-f374bc00-67a5-11ea-8535-15a36c71a366.PNG)

**Comment by marcschier** [comment]
Hi @pcameron-ptc, would it be possible for you to send us the ARM template that you used to deploy the VM and IoT Edge VM or a description of the network configuration for both VM?   If the IoT Edge VM and cannot resolve the name or the resolved IP is not reachable then this might be happening.   We will see if we can replicate such a setup in our simulation environment.

**Comment by cristipogacean** [comment]
@pcameron-ptc I managed to replicate the issue and we're working on a fix now. it seems the issue is that the dns resolves the hostname to an ipv6 address and the UA stack cannot properly cope with it. As a workaround til we fix it, you can try using the IPV4 address of the host in the discoveryUrl?

**Comment by pcameron-ptc** [comment]
I'm still seeing this issue after verifying that the 2.6.116 version of the modules have been deployed to our IoT Edge Runtime. 

This screenshot captures the network configuration of the IoT Edge Runtime system:
![iot-edge-network-configuration](https://user-images.githubusercontent.com/43643709/77067227-02808780-69bb-11ea-9e83-885f0dcdab57.PNG)

This screenshot captures the network configuration of the Windows (TKS) system. Note that it shares a virtual network with the IoT Edge system:
![tks-vm-network-configuration](https://user-images.githubusercontent.com/43643709/77067293-1c21cf00-69bb-11ea-9c92-c1dba9e989be.PNG)

Here is the Iot Edge system successfully connecting to port 49320 on the TKS system using telnet. Note that the DNS name "denali-vm" is resolved to the private IP 10.1.8.4
![telnet-success](https://user-images.githubusercontent.com/43643709/77067438-555a3f00-69bb-11ea-9a7a-6db4ca346234.PNG)

Here is the TKS system successfully pinging the IoT Edge system:
![tks-vm-pinging-linuxgateway](https://user-images.githubusercontent.com/43643709/77067496-67d47880-69bb-11ea-964d-85a6ec74d560.PNG)

Here is the configuration of the "add-application" call in Postman
![add-application](https://user-images.githubusercontent.com/43643709/77067534-7753c180-69bb-11ea-9331-c3dc5ad868da.PNG)

Finally, here are the results from tailing the discovery module logs:
![discovery-found-0-discovery-urls](https://user-images.githubusercontent.com/43643709/77067568-85a1dd80-69bb-11ea-8b4e-247a61fff4d8.PNG)

**Comment by cristipogacean** [comment]
the fix was pushed to master
