### ISSUE TITLE
Cannot show endpoint when using linux image

### ISSUE THREAD

**Issue by ryan-ms** [Azure/Industrial-IoT#32]
Hi,

I used the latest source code on master branch to build opc twin module today.

I used  the dockerFile in `Industrial-IoT/modules/opc-twin/docker/Linux/amd64/`to build the linux image and running in IoT edge on Ubuntu OS.

But there are some error while scanning the network.
It show the error log as below in OPC twin log.

`[08:17:12 ERR] (Error) Channel 76685: ProcessErrorMessage(BadNotFound 'Error received from remote host: ')`

But it still shows the result uploaded.
![linux_log](https://user-images.githubusercontent.com/29178018/62194960-8397f980-b3ad-11e9-9c41-02a88cdba373.png)

But after that, when I click the endpoint button to see the endpoint. there are no any endpoint in the endpoint table, like picture below.
![linux_screen](https://user-images.githubusercontent.com/29178018/62194979-8f83bb80-b3ad-11e9-8be5-6b4940f80cc4.JPG)

I've tried the image which build at last week in develop branch, but the same error not happened, it works fine with that version.

Thank you.

**Comment by cristipogacean** [comment]
Thanks for reporting this. We are working on fixing it.

**Comment by monikavar** [comment]
Hi @ryan-ms , I have tested with the latest code on master and scenario for discovering endpoints running IoT Edge on Ubuntu OS seems to work (BTW we don't use dockerFile to create linux image anymore). Could you please test it with the latest code on master and re-open this issue in case of any problems?

**Comment by ryan-ms** [comment]
Hi @monikavar,
I've tested the latest module. And it ran perfectly. Thank you!
