### ISSUE TITLE
CLI Status command throws error

### ISSUE THREAD

**Issue by bamajeed** [Azure/Industrial-IoT#329]
**Describe the bug**
Running the "Status" command from CLI throws an exception
> status
Connecting to https://*********.azurewebsites.net/twin...
==================
{
  "ClassName": "Newtonsoft.Json.JsonReaderException",
  "Message": "Unexpected character encountered while parsing value: H. Path '', line 1, position 1.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsString()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at Microsoft.Azure.IIoT.Http.HttpResponseEx.GetContent[T](IHttpResponse response, JsonSerializerSettings settings) in C:\\Users\\-------\\Industrial-IoT\\common\\src\\Microsoft.Azure.IIoT.Core\\src\\Http\\Extensions\\HttpResponseEx.cs:line 25\r\n   at Microsoft.Azure.IIoT.OpcUa.Api.Twin.Clients.TwinServiceClient.GetServiceStatusAsync(CancellationToken ct) in C:\\Users\\---------------\\Industrial-IoT\\api\\src\\Microsoft.Azure.IIoT.OpcUa.Api.Twin\\src\\Clients\\TwinServiceClient.cs:line 47\r\n   at Microsoft.Azure.IIoT.Api.Cli.Program.GetStatusAsync(CliOptions options) in C:\\Users\\--------------\\Industrial-IoT\\api\\src\\Microsoft.Azure.IIoT.Api\\cli\\Program.cs:line 2469",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146233088,
  "Source": "Newtonsoft.Json",
  "WatsonBuckets": null
}
==================

**Comment by marcschier** [comment]
This is now fixed.   Thanks for reporting this issue.
