### ISSUE TITLE
Need replacement for old batching model (array of messages) in the publisher

### ISSUE THREAD

**Issue by marcschier** [Azure/Industrial-IoT#334]
The publisher was able to publish arrays of messages.   This is not per OPC UA standard, we therefore need "batching" as part of the dataset message (network message) format.   

What we propose is to send multiple datasets (for a sampled value) in the same message.   The old publisher had a decoupled gather/scatter mechanism, which caused data loss at high loads.   The new publisher uses DataFlow to internally batch messages together.   We are planning to use OPC UA flow control to apply back pressure to the server.  The question is whether anyone is interested in the old behavior which trades off throughput against data loss.

**Comment by cristipogacean** [comment]
completed in master
