### ISSUE TITLE
Alert if internal queue almost full

### ISSUE THREAD

**Issue by khilscher** [Azure/Industrial-IoT#34]
Log an alert if the internal queue (_monitoredItemsDataQueue) is close to full (BoundedCapacity) so a monitoring system, such as OMS, can notify an administrator.

**Comment by marcschier** [comment]
Closing and adding to our internal "long term" product backlog.   This will unfortunately not be implemented in H120.  Our new publisher implementation also does not include a queue anymore but uses Dataflow, the plan would be to in the long run move the back pressure to the server, thus not dropping any more messages in the publisher except during restarts/failovers (and maybe not even there).
