### ISSUE TITLE
Cannot add application by discovery id when only discoverer is online

### ISSUE THREAD

**Issue by pcameron-ptc** [Azure/Industrial-IoT#359]
**Describe the bug**
I have two IoT Edge VMs deployed. One is Linux/Ubuntu running TKE locally, the other is Windows 10 running TKS locally. In other words, on both machines, the OPC UA server is running on the same host as the discovery module. 

**1.0 In this screenshot, we see that only the "TKS" vm is running:**
![two-discoverers-linux-stopped](https://user-images.githubusercontent.com/43643709/77761478-7ef41580-700e-11ea-896a-d18d29722497.PNG)

**2.0 Here is an attempt to add the TKS application using the TKS discoverer:**
![add-application-request](https://user-images.githubusercontent.com/43643709/77761542-9e8b3e00-700e-11ea-8440-fcd2661f7284.PNG)

**3.0 The edge indicates that it is able to find the endpoint and upload results:**
![discovery-succeeds](https://user-images.githubusercontent.com/43643709/77761629-b82c8580-700e-11ea-9a56-31b364a1a79a.PNG)

**4.0 However, no applications are ever returned:**
![no-applications](https://user-images.githubusercontent.com/43643709/77761678-c9759200-700e-11ea-99b6-689397e6b11d.PNG)

**5.0 When we power on the Linux VM, we get different results:**
![two-discoverers](https://user-images.githubusercontent.com/43643709/77761736-ddb98f00-700e-11ea-997f-881d3dbb400b.PNG)

**6.0 A second Add Applications request is required. After which, we see the TKS application has been added, but with the TKE discoverer:**
![tks-application-added-with-tke-discoverer](https://user-images.githubusercontent.com/43643709/77761890-1b1e1c80-700f-11ea-919e-d78d359bba44.PNG)

**7.0 The TKS endpoint can now be browsed:**
![get-endpoints-finds-tks-endpoint](https://user-images.githubusercontent.com/43643709/77762036-4b65bb00-700f-11ea-83db-77d7cfa01ac6.PNG)

**8.0 The TKE endpoint can also now be browsed:**
![get-endpoints-finds-tke-endpoint](https://user-images.githubusercontent.com/43643709/77762089-5ddff480-700f-11ea-9631-907d2eed93a9.PNG)

**9.0 TKS is now successfully activated:**
![tks-activated-and-connected](https://user-images.githubusercontent.com/43643709/77762148-73551e80-700f-11ea-8968-a6e9cbecb6d9.PNG)

We're trying to understand if this is intended behavior. If so, what is the purpose of specifying the discover ID in the non-scanning explicit activation?

**Comment by marcschier** [comment]
Hi @pcameron-ptc , the id in this case is a per request I'd that allows subscription and correlation of discovery progress and results.   There are substantial differences with what can be achieved on Windows container to host networking vs Linux.  Linux finds not only host but also other servers on the network.  Windows finds servers on the network but cannot access host servers.  That is why TKE is found by windows, and Linux finds TKS and TKE.  We are experimenting right now how we can work around this but we have no guarantees for a resolution.  My suggestion is to use Linux Host for IoT Edge only.

**Comment by pcameron-ptc** [comment]
Thank you @marcschier - we have no particular requirement for Windows based IoT Edge runtime, and will follow your guidance to only use Linux Host for IoT Edge moving forward.

**Comment by marcschier** [comment]
We won't fix for Windows.
