### ISSUE TITLE
IIoT Edge UI Installer fails on first attempt on Windows 10 1809

### ISSUE THREAD

**Issue by pcameron-ptc** [Azure/Industrial-IoT#360]
**Describe the bug**
I have consistently seen this failure when running the Industrial IoT Gateway Installer for the first time on an Azure hosted Windows 10 1809 VM (D2_v3 size). It's not a blocker, a second run of the tool consistently completes successfully. 

![iotedge-graphical-installer](https://user-images.githubusercontent.com/43643709/77789240-09516f00-7039-11ea-919e-dfd975b13e23.PNG)

**Comment by marcschier** [comment]
After talking to my colleague this appears to be the result of the reboot prompt being suppressed on the VM in certain conditions.  The reboot is necessary after VC runtime installation.

**Comment by barnstee** [comment]
Correct. I'll have a look to see if we can make this message a little more friendly.

**Comment by barnstee** [comment]
This is now fixed:
![Untitled](https://user-images.githubusercontent.com/8157818/77904087-380f5580-7284-11ea-879f-953bc221ab6a.png)

**Comment by barnstee** [comment]
New release on GitHub.

**Comment by marcschier** [comment]
Hi @pcameron-ptc - please reopen if you still see issues with the installer.  Thanks!
