### ISSUE TITLE
OPC Publisher direct method call from Azure Portal always reply with status 500

### ISSUE THREAD

**Issue by fgsantos89** [Azure/Industrial-IoT#361]
**Describe the bug**
OPC Publisher direct method call from Azure Portal always reply with {"status": 500, payload: null}

**To Reproduce**
1. Create the resources: Azure VM Ubuntu 18.04, Azure IoT Hub...
2. Follows the steps on https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux  to install the Azure Iot Edge Runtime / Hub
3. On Azure Iot Hub go to Edge Device click on Set Modules and Add Module OPC Publisher
4. Wait for the deploy
5. Go to Direct Method on the OPC Publisher Module and call method GetInfo with payload {} 

**Expected behavior**
Returning the info from the module

**Desktop:**
 - OS: Win 10
 - Browser Chrome  80.0.3987.149

<details>
  <summary>iotedge check</summary>

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.8 but 1.0.9 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

19 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
</details>

<details>
  <summary>iotedge logs publisher</summary>
  Always showing:
[20:25:06 INF] No job received, wait 00:00:05 ...(Microsoft.Azure.IIoT.Agent.Framework.Agent.Worker)
</details>

<details>
  <summary>iotedge logs edgeAgent</summary>

2020-03-28 20:23:39  Starting Edge Agent
2020-03-28 20:23:39.531 +00:00 Edge Agent Main()
<6> 2020-03-28 20:23:39.756 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-03-28 20:23:39.950 +00:00 [INF] - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
<6> 2020-03-28 20:23:39.951 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-03-28 20:23:40.018 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false,"EnableGetLogs":false,"EnableMetrics":false}
<6> 2020-03-28 20:23:40.202 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:06/26/2020 14:54:24] to Root
<6> 2020-03-28 20:23:40.745 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-03-28 20:23:40.835 +00:00 [INF] - Started operation refresh twin config
<6> 2020-03-28 20:23:40.863 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2020-03-28 20:23:40.969 +00:00 [INF] - Registering request handler RestartModule
<6> 2020-03-28 20:23:42.280 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_WebSocket_Only.
<6> 2020-03-28 20:23:42.432 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-03-28 20:23:42.531 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 3 and reported properties version 17.
<6> 2020-03-28 20:23:42.813 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (15s left).
<6> 2020-03-28 20:23:42.813 +00:00 [INF] - Module 'publisher' scheduled to restart after 20s (05s left).
<6> 2020-03-28 20:23:42.813 +00:00 [INF] - Module 'SimulatedTemperatureSensor' scheduled to restart after 20s (05s left).
<6> 2020-03-28 20:23:43.031 +00:00 [INF] - Updated reported properties
<6> 2020-03-28 20:23:48.049 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (10s left).
<6> 2020-03-28 20:23:48.050 +00:00 [INF] - Module 'publisher' scheduled to restart after 20s (00s left).
<6> 2020-03-28 20:23:48.050 +00:00 [INF] - Module 'SimulatedTemperatureSensor' scheduled to restart after 20s (00s left).
<6> 2020-03-28 20:23:53.067 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (05s left).
<6> 2020-03-28 20:23:53.102 +00:00 [INF] - Plan execution started for deployment 3
<6> 2020-03-28 20:23:53.110 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module publisher]\n  [Start module publisher]\n  [Saving publisher to store]\n)"
<6> 2020-03-28 20:23:53.118 +00:00 [INF] - Executing command: "Stop module publisher"
<6> 2020-03-28 20:23:53.168 +00:00 [INF] - Executing command: "Start module publisher"
<6> 2020-03-28 20:23:53.629 +00:00 [INF] - Executing command: "Saving publisher to store"
<6> 2020-03-28 20:23:53.647 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module SimulatedTemperatureSensor]\n  [Start module SimulatedTemperatureSensor]\n  [Saving SimulatedTemperatureSensor to store]\n)"
<6> 2020-03-28 20:23:53.647 +00:00 [INF] - Executing command: "Stop module SimulatedTemperatureSensor"
<6> 2020-03-28 20:23:53.649 +00:00 [INF] - Executing command: "Start module SimulatedTemperatureSensor"
<6> 2020-03-28 20:23:54.241 +00:00 [INF] - Executing command: "Saving SimulatedTemperatureSensor to store"
<6> 2020-03-28 20:23:54.247 +00:00 [INF] - Plan execution ended for deployment 3
<6> 2020-03-28 20:23:59.317 +00:00 [INF] - Plan execution started for deployment 3
<6> 2020-03-28 20:23:59.318 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module edgeHub]\n  [Start module edgeHub]\n  [Saving edgeHub to store]\n)"
<6> 2020-03-28 20:23:59.318 +00:00 [INF] - Executing command: "Stop module edgeHub"
<6> 2020-03-28 20:23:59.320 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2020-03-28 20:23:59.809 +00:00 [INF] - Executing command: "Saving edgeHub to store"
<6> 2020-03-28 20:23:59.815 +00:00 [INF] - Plan execution ended for deployment 3
<6> 2020-03-28 20:23:59.985 +00:00 [INF] - Updated reported properties
<6> 2020-03-28 20:24:05.117 +00:00 [INF] - Updated reported properties
<6> 2020-03-28 20:24:20.633 +00:00 [INF] - Updated reported properties
<6> 2020-03-28 20:33:31.446 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'publisher' as it has been running healthy for 00:10:00.
<6> 2020-03-28 20:33:31.446 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'SimulatedTemperatureSensor' as it has been running healthy for 00:10:00.
<6> 2020-03-28 20:33:31.446 +00:00 [INF] - Plan execution started for deployment 3
<6> 2020-03-28 20:33:31.446 +00:00 [INF] - Executing command: "Saving publisher to store"
<6> 2020-03-28 20:33:31.450 +00:00 [INF] - Executing command: "Saving SimulatedTemperatureSensor to store"
<6> 2020-03-28 20:33:31.450 +00:00 [INF] - Plan execution ended for deployment 3
<6> 2020-03-28 20:33:36.604 +00:00 [INF] - Updated reported properties
<6> 2020-03-28 20:34:21.658 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'edgeHub' as it has been running healthy for 00:10:00.
<6> 2020-03-28 20:34:21.658 +00:00 [INF] - Plan execution started for deployment 3
<6> 2020-03-28 20:34:21.658 +00:00 [INF] - Executing command: "Saving edgeHub to store"
<6> 2020-03-28 20:34:21.658 +00:00 [INF] - Plan execution ended for deployment 3
<6> 2020-03-28 20:34:26.810 +00:00 [INF] - Updated reported properties
</details>

<details>
  <summary>iotedge logs edgeHub</summary>
  
  2020-03-28 20:24:20  Starting Edge Hub
2020-03-28 20:24:20.534 +00:00 Edge Hub Main()
<6> 2020-03-28 20:24:21.546 +00:00 [INF] - Installing certificates [CN=iotedged workload ca:06/26/2020 14:54:24],[CN=Test Edge Device CA:06/26/2020 14:54:24],[CN=Test Edge Owner CA:06/26/2020 14:54:24] to Root
<6> 2020-03-28 20:24:21.587 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:06/26/2020 14:54:24] to Root
<6> 2020-03-28 20:24:22.609 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2020-03-28 20:24:22.711 +00:00 [INF] - Initializing Edge Hub
<6> 2020-03-28 20:24:22.712 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-03-28 20:24:22.713 +00:00 [INF] - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
<6> 2020-03-28 20:24:22.713 +00:00 [INF] - OptimizeForPerformance=True
<6> 2020-03-28 20:24:22.718 +00:00 [INF] - Loaded server certificate with expiration date of "2020-06-26T14:54:24.0000000+00:00"
<6> 2020-03-28 20:24:22.775 +00:00 [INF] - Created new message store
<6> 2020-03-28 20:24:22.793 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2020-03-28 20:24:22.958 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2020-03-28 20:24:22.975 +00:00 [INF] - Created device scope identities cache
<6> 2020-03-28 20:24:22.988 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-03-28 20:24:23.035 +00:00 [INF] - Initialized storing twin manager
<6> 2020-03-28 20:24:23.061 +00:00 [INF] - Initializing configuration
<6> 2020-03-28 20:24:23.133 +00:00 [INF] - New device connection for device opc-vm/$edgeHub
<6> 2020-03-28 20:24:23.157 +00:00 [INF] - Processing pending subscriptions for opc-vm/$edgeHub
<6> 2020-03-28 20:24:23.416 +00:00 [INF] - Attempting to connect to IoT Hub for client opc-vm/$edgeHub via AMQP over WebSockets...
<6> 2020-03-28 20:24:24.061 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2020-03-28 20:24:24.473 +00:00 [INF] - Set the following 1 route(s) in edge hub
<6> 2020-03-28 20:24:24.473 +00:00 [INF] - upstream: FROM /messages/* INTO $upstream
<6> 2020-03-28 20:24:24.478 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-03-28 20:24:24.479 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-03-28 20:24:24.551 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2020-03-28 20:24:24.552 +00:00 [INF] - Initialized edge hub configuration
<6> 2020-03-28 20:24:24.582 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2020-03-28 20:24:24.765 +00:00 [INF] - Scheduling server certificate renewal for "2020-06-26T14:51:54.0002356Z".
<6> 2020-03-28 20:24:24.768 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2020-03-28 20:24:24.777 +00:00 [INF] - Starting MQTT head
<6> 2020-03-28 20:24:24.868 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2020-03-28 20:24:25.019 +00:00 [INF] - Starting AMQP head
<6> 2020-03-28 20:24:25.020 +00:00 [INF] - Started MQTT head
<6> 2020-03-28 20:24:25.155 +00:00 [INF] - Started AMQP head
<6> 2020-03-28 20:24:25.160 +00:00 [INF] - Starting HTTP head
<6> 2020-03-28 20:24:25.187 +00:00 [INF] - Exiting disconnected state
<6> 2020-03-28 20:24:25.193 +00:00 [INF] - Received device connected callback
<6> 2020-03-28 20:24:25.224 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2020-03-28 20:24:25.230 +00:00 [INF] - Processing subscriptions for client opc-vm/$edgeHub on device connected.
<6> 2020-03-28 20:24:25.256 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-03-28 20:24:25.272 +00:00 [INF] - Entering connected state
<6> 2020-03-28 20:24:25.286 +00:00 [INF] - Cloud connection for opc-vm/$edgeHub is True
<6> 2020-03-28 20:24:25.296 +00:00 [INF] - Connection status for opc-vm/$edgeHub changed to ConnectionEstablished
<6> 2020-03-28 20:24:25.300 +00:00 [INF] - Client opc-vm/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2020-03-28 20:24:25.315 +00:00 [INF] - Created cloud proxy for client opc-vm/$edgeHub via AMQP over WebSockets, with client operation timeout 20 seconds.
<6> 2020-03-28 20:24:25.332 +00:00 [INF] - Initialized cloud proxy baa5b965-289e-4f0b-935b-e6c7e598fb29 for opc-vm/$edgeHub
<6> 2020-03-28 20:24:25.335 +00:00 [INF] - Created cloud connection for client opc-vm/$edgeHub
<6> 2020-03-28 20:24:25.391 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
<6> 2020-03-28 20:24:26.142 +00:00 [INF] - Updated reported properties for opc-vm/$edgeHub
<6> 2020-03-28 20:24:26.169 +00:00 [INF] - Processing pending subscriptions for opc-vm/$edgeHub
<6> 2020-03-28 20:24:26.178 +00:00 [INF] - Obtained edge hub config from module twin
<4> 2020-03-28 20:24:26.259 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2020-03-28 20:24:26.316 +00:00 [INF] - Started HTTP head
<6> 2020-03-28 20:24:26.328 +00:00 [INF] - New token received on the Cbs link
<6> 2020-03-28 20:24:26.441 +00:00 [INF] - Client opc-vm/SimulatedTemperatureSensor in device scope authenticated locally.
<6> 2020-03-28 20:24:26.459 +00:00 [INF] - New device connection for device opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.473 +00:00 [INF] - Bind device proxy for device opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.474 +00:00 [INF] - Initialized device listener in the AMQP protocol head for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.486 +00:00 [INF] - Opened link Events for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.527 +00:00 [INF] - Opened link MethodReceiving for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.534 +00:00 [INF] - Processing pending subscriptions for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.535 +00:00 [INF] - Attempting to connect to IoT Hub for client opc-vm/SimulatedTemperatureSensor via AMQP over WebSockets...
<6> 2020-03-28 20:24:26.549 +00:00 [INF] - Opened link MethodSending for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.557 +00:00 [INF] - Opened link TwinReceiving for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.561 +00:00 [INF] - Opened link ModuleMessages for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.569 +00:00 [INF] - Opened link TwinSending for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.598 +00:00 [INF] - Cloud connection for opc-vm/SimulatedTemperatureSensor is True
<6> 2020-03-28 20:24:26.599 +00:00 [INF] - Connection status for opc-vm/SimulatedTemperatureSensor changed to ConnectionEstablished
<6> 2020-03-28 20:24:26.599 +00:00 [INF] - Client opc-vm/SimulatedTemperatureSensor connected to cloud, processing existing subscriptions.
<6> 2020-03-28 20:24:26.599 +00:00 [INF] - Created cloud proxy for client opc-vm/SimulatedTemperatureSensor via AMQP over WebSockets, with client operation timeout 20 seconds.
<6> 2020-03-28 20:24:26.599 +00:00 [INF] - Initialized cloud proxy fab46e2e-627d-4357-a70f-864ac82d4316 for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.600 +00:00 [INF] - Created cloud connection for client opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.619 +00:00 [INF] - Processing pending subscriptions for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:26.620 +00:00 [INF] - Processing pending subscriptions for opc-vm/SimulatedTemperatureSensor
<6> 2020-03-28 20:24:28.146 +00:00 [INF] - Updated reported properties for opc-vm/$edgeHub
<6> 2020-03-28 20:24:30.968 +00:00 [INF] - Client opc-vm/publisher in device scope authenticated locally.
<6> 2020-03-28 20:24:30.974 +00:00 [INF] - Successfully generated identity for clientId opc-vm/publisher and username opc-vm/opc-vm/publisher/?api-version=2018-06-30&DeviceClientType=.NET%2F1.21.3%20%28.NET%20Core%203.1.2%3B%20Linux%205.0.0-1032-azure%20%2334-Ubuntu%20SMP%20Mon%20Feb%2010%2019%3A37%3A25%20UTC%202020%3B%20X64%29%20OpcPublisher_2.6.96.38252
<6> 2020-03-28 20:24:30.978 +00:00 [INF] - ClientAuthenticated, opc-vm/publisher, 4886ebce
<6> 2020-03-28 20:24:31.024 +00:00 [INF] - New device connection for device opc-vm/publisher
<6> 2020-03-28 20:24:31.026 +00:00 [INF] - Bind device proxy for device opc-vm/publisher
<6> 2020-03-28 20:24:31.027 +00:00 [INF] - Binding message channel for device Id opc-vm/publisher
<6> 2020-03-28 20:24:31.073 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, DesiredPropertyUpdates for client opc-vm/publisher.
<6> 2020-03-28 20:24:31.073 +00:00 [INF] - Processing pending subscriptions for opc-vm/publisher
<6> 2020-03-28 20:24:31.073 +00:00 [INF] - Attempting to connect to IoT Hub for client opc-vm/publisher via AMQP over WebSockets...
<6> 2020-03-28 20:24:31.083 +00:00 [INF] - Set subscriptions from session state for opc-vm/publisher
<6> 2020-03-28 20:24:31.128 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, DesiredPropertyUpdates for client opc-vm/publisher.
<6> 2020-03-28 20:24:31.129 +00:00 [INF] - Cloud connection for opc-vm/publisher is True
<6> 2020-03-28 20:24:31.129 +00:00 [INF] - Connection status for opc-vm/publisher changed to ConnectionEstablished
<6> 2020-03-28 20:24:31.129 +00:00 [INF] - Client opc-vm/publisher connected to cloud, processing existing subscriptions.
<6> 2020-03-28 20:24:31.129 +00:00 [INF] - Created cloud proxy for client opc-vm/publisher via AMQP over WebSockets, with client operation timeout 20 seconds.
<6> 2020-03-28 20:24:31.130 +00:00 [INF] - Initialized cloud proxy da39501f-c703-48d2-b382-e0435be1cf8e for opc-vm/publisher
<6> 2020-03-28 20:24:31.130 +00:00 [INF] - Created cloud connection for client opc-vm/publisher
<6> 2020-03-28 20:24:31.136 +00:00 [INF] - Set subscriptions from session state for opc-vm/publisher
<6> 2020-03-28 20:24:31.153 +00:00 [INF] - Processing pending subscriptions for opc-vm/publisher
<6> 2020-03-28 20:24:31.463 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, DesiredPropertyUpdates for client opc-vm/publisher.
<6> 2020-03-28 20:24:31.464 +00:00 [INF] - Processing pending subscriptions for opc-vm/publisher
<6> 2020-03-28 20:24:31.464 +00:00 [INF] - Set subscriptions from session state for opc-vm/publisher
<6> 2020-03-28 20:24:31.555 +00:00 [INF] - Closing connection for device: opc-vm/publisher, ,
<6> 2020-03-28 20:24:31.560 +00:00 [INF] - Disposing MessagingServiceClient for device Id opc-vm/publisher because of exception -
<6> 2020-03-28 20:24:31.565 +00:00 [INF] - Setting device proxy inactive for device Id opc-vm/publisher
<6> 2020-03-28 20:24:31.571 +00:00 [INF] - Device connection removed for device opc-vm/publisher
<6> 2020-03-28 20:24:31.579 +00:00 [INF] - Remove device connection for device opc-vm/publisher
<6> 2020-03-28 20:24:31.622 +00:00 [INF] - Client opc-vm/publisher in device scope authenticated locally.
<6> 2020-03-28 20:24:31.622 +00:00 [INF] - Successfully generated identity for clientId opc-vm/publisher and username opc-vm/opc-vm/publisher/?api-version=2018-06-30&DeviceClientType=.NET%2F1.21.3%20%28.NET%20Core%203.1.2%3B%20Linux%205.0.0-1032-azure%20%2334-Ubuntu%20SMP%20Mon%20Feb%2010%2019%3A37%3A25%20UTC%202020%3B%20X64%29%20OpcPublisher_2.6.96.38252
<6> 2020-03-28 20:24:31.622 +00:00 [INF] - ClientAuthenticated, opc-vm/publisher, 5a087925
<6> 2020-03-28 20:24:31.624 +00:00 [INF] - New device connection for device opc-vm/publisher
<6> 2020-03-28 20:24:31.625 +00:00 [INF] - Bind device proxy for device opc-vm/publisher
<6> 2020-03-28 20:24:31.625 +00:00 [INF] - Binding message channel for device Id opc-vm/publisher
<6> 2020-03-28 20:24:31.625 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, DesiredPropertyUpdates for client opc-vm/publisher.
<6> 2020-03-28 20:24:31.625 +00:00 [INF] - Processing pending subscriptions for opc-vm/publisher
<6> 2020-03-28 20:24:31.626 +00:00 [INF] - Set subscriptions from session state for opc-vm/publisher
<6> 2020-03-28 20:24:31.627 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, DesiredPropertyUpdates for client opc-vm/publisher.
<6> 2020-03-28 20:24:31.628 +00:00 [INF] - Processing pending subscriptions for opc-vm/publisher
<6> 2020-03-28 20:24:31.628 +00:00 [INF] - Set subscriptions from session state for opc-vm/publisher
<6> 2020-03-28 20:24:31.682 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, DesiredPropertyUpdates for client opc-vm/publisher.
<6> 2020-03-28 20:24:31.682 +00:00 [INF] - Processing pending subscriptions for opc-vm/publisher
<6> 2020-03-28 20:24:31.683 +00:00 [INF] - Set subscriptions from session state for opc-vm/publisher
<6> 2020-03-28 20:24:33.272 +00:00 [INF] - Updated reported properties for opc-vm/$edgeHub
<6> 2020-03-28 20:24:33.396 +00:00 [INF] - Updated reported properties for opc-vm/publisher
<6> 2020-03-28 20:29:24.588 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-03-28 20:34:24.581 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-03-28 20:39:24.581 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2020-03-28 20:44:24.584 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
</details>

I add the SimulatedTemperatureSensor edge Module and could call the direct method and also could call ping on the edgeAgent with status 200.

**Comment by marcschier** [comment]
Hi @fgsantos89 , we deprecated and removed the direct method capabilities in the last release.  Please use the REST NodePublishStart and Stop API for publisher configuration.  Publishednodes.json configuration works as well.

**Comment by fgsantos89** [comment]
Where I can find the documentation of the REST APIs ?

**Comment by cristipogacean** [comment]
@fgsantos89 https://github.com/Azure/Industrial-IoT/tree/master/docs/api
