### ISSUE TITLE
Failure to deserialize by swagger client when reading array nodes

### ISSUE THREAD

**Issue by pcameron-ptc** [Azure/Industrial-IoT#380]
**Describe the bug**
The opcTwinService.readValueAsync swagger client method (java generated code) fails with the following message when reading a node of type "double array" (similar error for other array types):

"com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{
  "value": [
    12.34,
    12.34,
    12.34,
    12.34
  ],
  "dataType": "Double",
  "sourceTimestamp": "2020-04-13T20:45:06.182Z",
  "serverTimestamp": "2020-04-13T20:45:06.182Z"
}"; line: 11, column: 1] (through reference chain: com.microsoft.azure.iiot.ua.sdk.swagger.twin.models.ValueReadResponseApiModel["value"])" 

The read succeeds when performed by Postman:
![postman](https://user-images.githubusercontent.com/43643709/79159655-7a698400-7da6-11ea-9b6c-64ae27ec0aba.png)

UA Expert is able to monitor the node:
![ua-expert](https://user-images.githubusercontent.com/43643709/79159785-b13f9a00-7da6-11ea-980d-dddb7e20b346.PNG)

**Comment by marcschier** [comment]
My assumption is that the swagger.json sets the variantvalue object as string intead of object.

**Comment by marcschier** [comment]
Yes - confirmed -
       "value": {
          "description": "Value read",
          "type": "string"
        },

Will be fixed.

**Comment by pcameron-ptc** [comment]
Thanks Marc!

**Comment by marcschier** [comment]
Fix is in master.
