### ISSUE TITLE
Unable to create module for windows

### ISSUE THREAD

**Issue by alonsors-809** [Azure/Industrial-IoT#406]
Hi, 
I am trying to create or find a module to use the OPC Publisher but I am unable to find a section to do it. I'm not sure if it is possible, but in case it can be done, can you provide a link to a tutorial or walkthrough to do so. I have tried the ones in the Azure marketplace module, but it seems it only works on Linux. I am running the containers on windows containers on docker.

Thanks

**Comment by marcschier** [comment]
Hi @alonsors-809 - you can follow the instructions in our /docs, especially the tutorials on how to deploy IoT Edge to have all components auto-deploy into an IoT Edge environment.   You can also use our handy installer, also detailed in the docs.

Note that IoT Edge is only supported on a subset of Windows editions as per https://docs.microsoft.com/en-us/azure/iot-edge/support.   It will not work on your latest Windows 10.   The recommendation is to use docker for Linux following the official documentation.
