### ISSUE TITLE
Problem with Historical Access

### ISSUE THREAD

**Issue by filipizydorczyk** [Azure/Industrial-IoT#414]
Hello.
I try to call [POST /history/v2/history/read/{endpointId}](https://github.com/Azure/Industrial-IoT/blob/master/docs/api/history/readme.md#read-history-using-json-details) but i can't understand documentation.

Fisrtly i thougth that nodeId is the only required field in [body](https://github.com/Azure/Industrial-IoT/blob/master/docs/api/history/definitions.md#variantvaluehistoryreadrequestapimodel). I know it is written optional but in description is mandatory so it is confusing to me. I was getting NullArgumentException with "paramname: details" in message. So i decided to add details in body but [description](https://github.com/Azure/Industrial-IoT/blob/master/docs/api/history/definitions.md#variantvaluehistoryreadrequestapimodel) doesn't mean anything to me :/.

I tried anyway and my body looked like this:
`{
	"nodeId": "here_id",
	"details": "{\"IsReadModified\":true,\"StartTime\":\"2020-04-03T11:13:54Z\",\"EndTime\":\"2020-05-03T11:13:54Z\",\"NumValuesPerNode\":5,\"ReturnBounds\":false}"
}`

I am running out of ideas how this body should looks like. Does anybody have any experience with this api calls? Would be gratefull for any help.

**Comment by marcschier** [comment]
We have removed historic access support.
