### ISSUE TITLE
Message batching via JSON array

### ISSUE THREAD

**Issue by jcharlytown** [Azure/Industrial-IoT#42]
Hi,

we're currently evaluating whether or not it would be feasible to connect multiple OPC UA endpoints (and therefore multiple logical or even physical devices) via a single instance of the opc publisher. Doing so, we ran into the fact that the opc publisher batches messages "manually" using a JSON array of messages - on application layer if you will. In our scenario, this means we might end up with messages from different OPC UA endpoints within the same IoT Hub message. This in turn becomes challenging later on within the processing pipeline, e.g., when joining incoming messages with state from CosmosDB via Azure Functions - we would need to join with multiple documents within a single trigger.

My question is the following: Is this choice intentional? Is there a reason for this design we're not seeing? It seems that the IoT Hub c# SDK offers [DeviceClient.SendEventBatchAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.sendeventbatchasync?view=azure-dotnet#Microsoft_Azure_Devices_Client_DeviceClient_SendEventBatchAsync_System_Collections_Generic_IEnumerable_Microsoft_Azure_Devices_Client_Message__) for transport layer optimization, which would potentially avoid this issue.

Also, any idea for a workaround, e.g., disabling batching or splitting messages up within Azure?

**Comment by marcschier** [comment]
We will support choosing binary encoding and support dataset messages by/before end of this year - compliant with Part 14.  This should deal with large messages cost efficiently.   However, we have also decided that as part of this feature we will remove the current json batching as it is not compatible with OPC UA Pub/Sub.
