### ISSUE TITLE
User Access Level not represented by NodeAcessLevel Enumeration

### ISSUE THREAD

**Issue by cstamper-onshape** [Azure/Industrial-IoT#422]
**Describe the bug**
Node Access Level Enum doesn't represent the User Access Level **"CurrentRead, CurrentWrite"**

**Expected behavior**
The values of a node should be the same when the request is made via a rest call or through the generated swagger client

**Screenshots**
Performing a browse request on the node `http://microsoft.com/Opc/OpcPlc/#s=Telemetry` will return a list of nodes including the node StepUp. Notice that it has the field `userAccessLevel` with value of `CurrentRead, CurrentWrite`.

![image](https://user-images.githubusercontent.com/61846435/81109734-8bf70500-8ee8-11ea-9161-229e0d25fa6c.png)

Performing the same browse request via the generated swagger code will return the same node, but now with the field `userAccessLevel` having a value of `null`.

![image](https://user-images.githubusercontent.com/61846435/81110187-340cce00-8ee9-11ea-8e67-acd4b711281e.png)

**Comment by marcschier** [comment]
Hi @cstamper-onshape -

Flag enums are stringified as "a, b" for a | b (json.net convention).  Which is not properly represented in swagger where we annotate all enums to be an x-ms-enum annotated "string".  

Autorest then seems to generate a Java representation of the enum (likely class, could that be?) and then matches the string received to it.  The "..., ..., ..." encoding cannot be matched into a single value though and thus the field is set to null.
