### ISSUE TITLE
Telemetry configuration no longer supported

### ISSUE THREAD

**Issue by alonsors-809** [Azure/Industrial-IoT#425]
Telemetry configuration no longer supported

Reading the documentation in this ReadMe (https://github.com/Azure/Industrial-IoT/blob/master/docs/modules/publisher.md) I notice in the section “Breaking changes in 2.6.x from 2.5.x and lower versions” that the functionality of “Message shaping using the --tc option and telemetry configuration file” will be no longer supported. My question is if there is a new way to shape the publisher telemetry, new alternatives or this functionality is completely erased?

We needed to configure the telemetry configuration file in order to set this property of the node:

"NodeId": {
      "Pattern": "(i|s|b|g)=(.*)"
    },

![image](https://user-images.githubusercontent.com/29662381/81226526-397d1d80-8fa8-11ea-944e-1ee5d5d4135a.png)

 - OS: Windows

**Comment by marcschier** [comment]
Hi @alonsors-809, we removed the feature for performance as well as the new binary configuration we added, which was a broad ask to keep message sizes low.   Many production systems employing the publisher module route the module output to a secondary module for local analytics, contextualization or storage.  We recommend to do the same if you need a message format not by default supported by the publisher module today (OPC UA Pub/Sub standard in binary and json, or the legacy JSON format).
