### ISSUE TITLE
Add information coming from other OPC nodes in the message sent to Edge

### ISSUE THREAD

**Issue by Gimly** [Azure/Industrial-IoT#43]
We would like to use one OPC publisher for multiple OPC servers. This means that we need a way to know from which OPC server (running on a physical machine) the message was coming from. 

We would like to use a node that is published by the OPC server that contains a "serial number" unique to the machine. This means that, instead of just sending the value in the message like the publisher is doing now, we'd like to send another information, coming from another OPC node.

Is this possible in the current version of the publisher? Is it something that would be interesting to be added as a parameter?

**Comment by markusstuhler** [comment]
This will be updated in the upcoming version of the publisher. We won't change anything on the current version. So I will close this issue for now.

Thanks!
Markus
