### ISSUE TITLE
OPC Publisher could not issue a valid certificate without deleting PKI folder

### ISSUE THREAD

**Issue by SewerynAW** [Azure/Industrial-IoT#430]
**Describe the bug**
The OPC publisher could not connect to the OPC UA server because the client certificate has expired and did not renew automatically. After manually removing the PKI folder and restarting Publisher, it forced to create a new folder and issue a valid client certificate for OPC server.

Log with error.
[opc-Publisher.log](https://github.com/Azure/Industrial-IoT/files/4594339/opc-Publisher.log)

**Expected behavior**
We expected the OPC publisher to issue a OPC client certificate automatically after one year, which would ensure that we would continually send OPC data to the Azure center.

**Additional context**
Our deployment configuration for OPC Publisher attached as well
[Deployment-config.txt](https://github.com/Azure/Industrial-IoT/files/4594425/Deployment-config.txt)

**Comment by cristipogacean** [comment]
fixed with #451. Please test it using :preview tagged container
