### ISSUE TITLE
What about the publication of Events? (feature request)

### ISSUE THREAD

**Issue by eoursel** [Azure/Industrial-IoT#44]
The OPC UA PubSub specification supports the publication of OPC UA Events. In the Part 14 specification, there is the PublishedEventsType. 

Do you plan to support the publication of events in the OPC Publisher? 

As a matter of fact, most industrial processes generate Alarms. This feature is really important for applications which need to analyze and store alarms with Azure services. 

Best regards,

**Comment by rowenwu** [comment]
Hi @eoursel, I'm the PM on the team prioritizing our backlog, and I'd love to learn more about your request for Alarms/Events support and what you're looking to do with it. This sort of information helps us evaluate customer needs. Please reach out via email to rowwu@microsoft.com if you'd like to chat further.

**Comment by rowenwu** [comment]
And @strandfelt, @dmakeranko-connyun, @boske001, @bewacontrol-renedivossen, since you've also shown interest in this feature, please do feel free to reach out as well! Send me a note at rowwu@microsoft.com

**Comment by MkTru** [comment]
Any update on Alarms/Events support?

**Comment by nelsonmorais** [comment]
I'm also looking for an update on this request. There's also another request #1219 for the same feature.

**Comment by marcschier** [comment]
Feature is in main branch, will be released in preview 2.9 release soon.l
