### ISSUE TITLE
Message Compression

### ISSUE THREAD

**Issue by PaulWaldman** [Azure/Industrial-IoT#46]
Is there any planned support for messages to be compressed that are sent to IoT Hub Messages?  

This would be especially beneficial in larger systems where a lot of data is being collected and sent over a WAN connection.  Since ASA supports ingesting GZIP compressed messages from IoT Hub having an option to compress messages in OPC Publisher with GZIP would be beneficial.

**Comment by marcschier** [comment]
We are working on adding PubSub UA binary (UADP) support.   This should handle message compression needs of having optimal wire size.  We are not planning to add compression using compression algorithm.
