### ISSUE TITLE
Configuration of the published nodes by browse path

### ISSUE THREAD

**Issue by andreasfedermann** [Azure/Industrial-IoT#47]
Is there planned a feature to configure the published nodes in the publishednodes.json by browse path? This would give me the ability to program against type definitions. Especially I have to deal with servers which information models are based on a companion specification. In my case for instance I have two servers which are based on the same companion specification. There are nodes with the same browse paths which have different node ids because the servers were implemented from different vendors. To keep the effort for configuration low my idea was to configure the publisher by browse paths. An other advantage would be that I don't need a running server for configuring the publisher because the node ids would be determined at runtime from the publisher itself, see OPC UA Part 4 Chapter 5.8.4.

**Comment by rowenwu** [comment]
Hi @andreasfedermann, I'm the PM managing our roadmap and backlog. Would you like to set up a call to discuss the use case and requirements you've mentioned? And we can discuss any further feature requests you may have. Send me an email  at rowwu@microsoft.com if you're interested. Would love to connect with you.
