### ISSUE TITLE
Incorrect timestamping in data lake?

### ISSUE THREAD

**Issue by gillermaney** [Azure/Industrial-IoT#470]
Using canned deployment script, data in data lake seems to be incorrectly timestamped.  This shows up when using TSI as shown in attached screen shot.
![TSI](https://user-images.githubusercontent.com/55853911/82264320-b27a5e80-9932-11ea-8632-e049340665d3.png)

**Comment by cristipogacean** [comment]
@gillermaney, can you please detail a bit your statement? for example what are the "seen values" and "expected value"? please note all timestamps in the platform are UTC format.

**Comment by gillermaney** [comment]
This error seems to occur when the IoT Hub messaging quota is exceeded.  The expected timestamp values are strictly periodic.  The seen timestamp values are "bursty" and seem to reflect the time that telemetry reaches the data lake and not the OPC UA source timestamp.

**Comment by gillermaney** [comment]
What information do you need besides what I have provided?  Why would timestamps be incorrect if the telemetry data is being delayed in IoT Hub?

**Comment by cristipogacean** [comment]
@gillermaney can you try the most recent preview version? we did fix some connectivity issues on the publisher lately and those issues might have caused the situation you experience with TSI.
