### ISSUE TITLE
Publisher still publishes when endpoint is disabled.  

### ISSUE THREAD

**Issue by marcschier** [Azure/Industrial-IoT#473]
**Describe the bug**
Remove server using unregister or deactivate endpoint, publisher still publishes happily.

**To Reproduce**
1. See above

**Expected behavior**

We now show disabled (not found) endpoints grayed out in the UX, but the publishing should probably cease automatically as there is no way a user can stop it in the UX.  (you can stop using CLI).

**Comment by barnstee** [comment]
Duplicate of #685
