### ISSUE TITLE
OPC Twin semaphore disposed exception upon endpoint reactivation

### ISSUE THREAD

**Issue by jleger-ptc** [Azure/Industrial-IoT#474]
**Describe the bug**
Using the latest "preview" (2.7.72) OPC Twin edge module, I observed a System.ObjectDisposedException when trying to reactivate an endpoint using Postman

**To Reproduce**
1. Add an application via Postman
    * https://{{OPC-SERVICEURL}}/registry/v2/applications
2. Retrieve the endpoint (registration) id via Postman
    * https://{{OPC-SERVICEURL}}/registry/v2/endpoints
3. Activate the endpoint via Postman
    * https://{{OPC-SERVICEURL}}/registry/v2/endpoints/{{UA-ENDPOINT}}/activate
4. Confirm the endpoint activation via Postman
    * https://{{OPC-SERVICEURL}}/registry/v2/endpoints
    * Expected: { "activationState": "ActivatedAndConnected", "endpointState": "Unauthorized" }
5. Deactivate the endpoint via Postman
    * https://{{OPC-SERVICEURL}}/registry/v2/endpoints/{{UA-ENDPOINT}}/deactivate
6. Repeat **STEP 3**
    * System.ObjectDisposedException observed in OPC Twin docker logs
    * Endpoint state: { "activationState": "ActivatedAndConnected", "endpointState": "Connecting" }
    * OPC Twin must be manually restarted to get out of this state

**Expected behavior**
The activation state of the endpoint should be able to handle successive activation/deactivation toggles

**Screenshots**

Endpoint definition used for steps mentioned above

![EndpointInfo](https://user-images.githubusercontent.com/61740697/82328602-1e4ddd00-99ae-11ea-8208-c82699ab0389.PNG)

OPC Twin Docker Log

![OpcTwinLogs](https://user-images.githubusercontent.com/61740697/82328662-26a61800-99ae-11ea-841b-c018e592c38b.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - IoT Edge Version: 1.0.8
 - OPC Twin Version: 2.7.72

**Comment by marcschier** [comment]
#468 fixes this issue.
