### ISSUE TITLE
RetryPolicy for output messages?

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/Industrial-IoT#48]
What is the default RetryPolicy for messages send by the OpcPublisher used as IotEdge module ?
Can the RetryPolicy be changed (e.g. using commandline parameters) ?

**Comment by marcschier** [comment]
Offline message storage can be configured in IoT Hub, retry policy cannot.   Since our officially supported hosting mode is IoT Edge we are not going to add this functionality in the coming months, hence I am closing it.
