### ISSUE TITLE
Unable to add application by generated discovery URL

### ISSUE THREAD

**Issue by cstamper-ptc** [Azure/Industrial-IoT#480]
**Describe the bug**
Making a `Get Applications` request returns an item with a generated `discoveryUrl` such as below. Previously, the discovery url that was used to register the application was listed, but it seems that has changed and now only the generated url exists. 

<img width="536" alt="Screen Shot 2020-05-21 at 11 22 10 AM" src="https://user-images.githubusercontent.com/63324157/82574644-678c6100-9b55-11ea-97ce-5248395fee25.png">

When you unregister the application and try to add it using with the generated url from above an exception occurs in the discovery module and no results are uploaded. 

<img width="1791" alt="Screen Shot 2020-05-21 at 11 21 22 AM" src="https://user-images.githubusercontent.com/63324157/82574684-76731380-9b55-11ea-822c-e1d466efbd66.png">

Registering the application with `opc.tcp//<host ip>:50000` works as expected, and the resulting item in the `Get Applications` request has the same generated discovery url. 

Is this the expected behavior of the discovery module? If so, will the discovery url used to register the application continue to be removed from the `Get Applications` response?

**Additional context**
Using version `2.6.146` of the edge modules and app services

**Comment by marcschier** [comment]
Hi @cstamper-ptc , the discovery url reported is what is returned by the GetEndpoint response and thus by the server.  This has always been the case, I.e you can specify a different host name during discovery request but we will always return the truth from the server, and in addition alternative ip to access the endpoint and thus also the discovery url if you wanted to.

I assume it is a TKE?  If it is not started with a -h arg, docker will use the instance Id of the container.  My recommendation would be to start with a real host name, e.g. "TKE" that then can be resolved on the bridge.  That is if a dedicated discovery url is needed.
