### ISSUE TITLE
How to use the Publisher API to configure the OPC Publisher module?

### ISSUE THREAD

**Issue by toddysm** [Azure/Industrial-IoT#515]
**Describe the bug**
The documentation states the following:
> Configuration via OPC UA server and IoT Hub device method interface. The old model has been replaced with the new cloud-based Writer Group configuration interface, see Publisher API.

However, there is no explanation of how to use the Publisher API. So, if we want to use the Publisher API for the configuration of the publisher, how one does that. And, by the way - where is the publisher API - it is not shown on the architectural diagram

**Comment by barnstee** [comment]
We have documented the use of the Publisher in the new OPS manual (including links to its Swagger API): https://github.com/Azure/Industrial-IoT/blob/release/2.7.180/IIoT%20Platform%20Overview%20and%20Operations%20manual%20-%202.7.183.pdf
