### ISSUE TITLE
OPC UA variable Display name incorrect

### ISSUE THREAD

**Issue by gillermaney** [Azure/Industrial-IoT#528]
The telemetry data stream from the publisher has a value called Display name, but this display name is set to the node id of the variable and not the display name of the variable.  This bug was seen using the off the shelf deployment script using the built in VMs.

**Comment by cristipogacean** [comment]
you can provide your display name in the api or enable the publisher to fetch the display names using --fm=true argument

**Comment by cristipogacean** [comment]
right, we should disable that field by default since it is not part of the pubsub stream anyhow.

**Comment by cristipogacean** [comment]
fixed in 2.7.130
