### ISSUE TITLE
Missing model.json and parquet files in datalake

### ISSUE THREAD

**Issue by gillermaney** [Azure/Industrial-IoT#529]
Using the preconfigured deployment script a container called Powerbi is created as well as a folder called iotdataflow folder.  However while config.json is there, model.json is not as well as any parquet files. 

It is not known if this issue is related to known issues with TSI.

**Comment by cristipogacean** [comment]
That's a known issue, we're working on it. It helps if you restart the services-all App Service in the Azure deployment.

**Comment by marcschier** [comment]
We are removing this preview feature in 2.8.
