### ISSUE TITLE
Make QueueSize configurable

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/Industrial-IoT#53]
We use the OPCPublisher now in production at our customer to read ~16 values from a plc every 50 milliseconds.

We monitor the ingest and everything seems to works fine except for one thing: once every minute (on average) several node values are skipped. We know this because the values produced contain a counter.
 
We traced this back to the QueueSize:

https://github.com/Azure/iot-edge-opc-publisher/blob/master/opcpublisher/OpcMonitoredItem.cs#L577 
 
If we increase this to 50, we retrieve all data as expected.

Please make this QueueSize configurable.

**Comment by imZack** [comment]
Any updates on this?

**Comment by abadar05** [comment]
https://github.com/Azure/iot-edge-opc-publisher/pull/225#issuecomment-517189424

Any updates on this feature ?

**Comment by JohannesM24** [comment]
Any updates on this feature?

**Comment by dacolgit** [comment]
in version [2.8.2](https://github.com/Azure/Industrial-IoT/tree/release/2.8.2) QueueSize is configurable for Standalone mode.
For option syntax please look for `DefaultQueueSize` in [publisher-commandline.md](https://github.com/Azure/Industrial-IoT/blob/main/docs/modules/publisher-commandline.md) file.
