### ISSUE TITLE
Misleading license information?

### ISSUE THREAD

**Issue by ahmcalpine** [Azure/Industrial-IoT#535]
Although most of the code in this repository is released under the MIT license, two crucial files are released under other, less permissive licenses that affect how the code may be used.

The files are [JsonDecoderEx.cs](https://github.com/Azure/Industrial-IoT/blob/dd6e4f8/components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/JsonDecoderEx.cs) and [JsonEncoderEx.cs](https://github.com/Azure/Industrial-IoT/blob/614316a/components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/JsonEncoderEx.cs). They each contain the following copyright notice:
```
/* Copyright (c) 1996-2016, OPC Foundation. All rights reserved.
   The source code in this file is covered under a dual-license scenario:
     - RCL: for OPC Foundation members in good-standing
     - GPL V2: everybody else
   RCL license terms accompanied with this source code. See http://opcfoundation.org/License/RCL/1.00/
   GNU General Public License as published by the Free Software Foundation;
   version 2 of the License are accompanied with this source code. See http://opcfoundation.org/License/GPLv2
   This source code is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/
```

Anyone using the code in this repository needs to be aware of their obligations under the RCL or GPLv2, otherwise they may find themselves in breach of copyright if they use (in the case of RCL) or distribute (in both cases) a binary work that incorporates this code.

I recommend:
1. Updating the LICENSE file in the root of the repository; or
2. Replacing the abovementioned code with MIT licensed equivalents.

I'm not a copyright lawyer so please let me know if I've got that wrong.

**Comment by marcschier** [comment]
The project is licensed as MIT including all derivatives e.g. containers and nugets built from it.   

The header in this case is wrong.   This code also falls under MIT license of the project.  This will be fixed.

However, please be aware of the licenses of all dependencies, as specified in the thirdpartylicense.txt file in the root of the repo.
