### ISSUE TITLE
Publisher stops shortly after starting

### ISSUE THREAD

**Issue by gillermaney** [Azure/Industrial-IoT#536]
The latest version of the precanned deployment script seems to have an issue with the publisher.  It stops after a very short amount of time.  Here is the publisher log.  What other logs do you need?

[OpcPublisherLog.txt](https://github.com/Azure/Industrial-IoT/files/4736432/OpcPublisherLog.txt)

**Comment by cristipogacean** [comment]
Can you please retry with version 2.7.130? I cannot replicate the issue now.

**Comment by marcschier** [comment]
Closing - please re-open if this still occurs on 2.7.130 or later.
