### ISSUE TITLE
OPC UA Publisher Module To Module communication

### ISSUE THREAD

**Issue by mandar-opc** [Azure/Industrial-IoT#537]
**Azure IoT Edge On-Premise**
We are using OPC UA Publisher module to receive data from KerServer Simulator.The module is currently receiving 6K messages per second.
These messages are then route to another module(Data Ingestion) developed in Node JS.
The problem we are facing is Data Ingestion module is receiving only 500 messages/sec.We are expecting that it should receive 6K messages per second.

Is there anything we are missing? 

Current configuration setting:
   "publisher",
    "--pf=/appdata/pn.json",
    "--di=60",
    "--to",
    "--aa",
    "--ih=Mqtt",
    "--si=5",
    "--bs=100"

**Comment by marcschier** [comment]
Your configuration sets the batch size to 100 and batch triggering to 5 seconds, each message would then container around 100 values or whatever was collected in 5 seconds.   Try setting as 1 and omit --si and it should be what you are expecting.
