### ISSUE TITLE
Publishing subitems of OPC UA Node

### ISSUE THREAD

**Issue by HenryVanBragt** [Azure/Industrial-IoT#54]
I want to communicate subitems of my OPC UA objects to Azure. 
The configuration:
An OPC UA server on a Ewon Flexy contains a node ("s=PulseBit"). This node has several subitems like "isKPI" and "tagID".
When I am publishing this data to the cloud, I don't get the 'reference' of each node. With this 'reference' I know that "isKPI" is a member of "PulseBit". Sending/publishing the 'reference', is it something what depends on the OPC UA server or on the iot edge opc publisher?

**Comment by marcschier** [comment]
The expectation is that the OPC UA server models this as Variable motor1Variable (type:structure of motor1) with references HasComponent Variable actualSpeed (type:int32) and HasComponent Variable setPoint (type:int32). You could then decide to subscribe to the motor1Variable and get the entire structure (atomically) or to the individual members of the structure.  

Unfortunately, if this is not modelled like this you will need to select the variables individually and group them using a datasetwriterId with name motor1Variable.  However, in this case messages will not contain both values if the values change independently from each other.
