### ISSUE TITLE
Custom UA endpoint config gets overwritten

### ISSUE THREAD

**Issue by gillermaney** [Azure/Industrial-IoT#546]
To add a custom server to the canned deployment, we edited the container configuration (inside IoT Edge-Set modules) so that the new config is fetched from the customized publisher node json file. Soon after the docker image for the publisher is executed in the iot edge runtime, the custom config was overwritten to the default (empty). It seems that a webapp hosted as part of the deployment scripts responsible for the OPC heartbeat operation is causing this override of custom publisher node file config.

**Comment by marcschier** [comment]
Hi @gillermaney, This is correct - when deploying a Industrial IoT Edge gateway you have the option to have the modules on it managed by the cloud platform or optionally (but not recommended) manage the edge and module workloads on it yourself.   

To do the latter, the IoTEdge device twin must have a "unmanaged" property as described here: https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-install-iot-edge.md#unmanaged-industrial-iot-edge.   This prevents the workloads to be "overridden" by the automatic layered deployment that is created.   This only works once, meaning you cannot remove the tag to make a managed device unmanaged (at this point).   

My suggestion would be to set up a seperate IoT edge with just publisher that uses the configuration file.
