### ISSUE TITLE
Deployment template validation failed

### ISSUE THREAD

**Issue by rowenwu** [Azure/Industrial-IoT#552]
**Describe the bug**

**To Reproduce**
1. deploy.ps1 from command line
2. choose subscription (IOT-OPC-WALLS)
3. enter credentials
4. choose location (West-US)
5. Create new RG and application (both of the same name)
6. deployment starts and says "deploying..." for ~10 min 
6. error arises saying deployment failed

**Expected behavior**
Proceed to next step of deployment

**Screenshots**
![image](https://user-images.githubusercontent.com/9397376/84302232-da13af80-ab09-11ea-9bf3-a7eddb3a133d.png)

**error message:**
10:49:48 AM - The deployment 'azuredeploy' failed with error(s). Showing 1 out of 1 error(s).
Status Message: Deployment template validation failed: 'The template parameters 'datalakeServicePrincipalId' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'templateUrl, branchName, keyVaultName, eventHubNamespaceName, eventHubName, datalakeName, datalakeSkuName, tsiEnvironmentName, tsiStorageName, tsiStorageManagementKey, tsiEnvironmentSkuName, tsiEnvironmentSkuCapacity, tsiEnvironmentKind, tsiEnvironmentDisplayName, tsiEventHubAuthorization, tsiEventSourceDisplayName, signalRName, signalRSkuTier, signalRSkuName, signalRServiceMode, signalRSkuCapacity, dpsName, dpsSku, dpsCapacity, dpsIotHubHostName, dpsIotHubConnectionString, dpsIotHubLocation, workspaceName, kustoClusterName, kustoSkuName, kustoSkuCapacity, kustoSkuTier, kustoDatabaseName, workspaceSku, appInsightsName, workbookId, tags'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'. (Code:InvalidTemplate)

CorrelationId: 920c33d4-6996-4dcc-b662-f2d2630b24e2
Deployment failed.
**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I did receive this warning initially when starting the deployment: "WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running
PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none
of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide"

**Comment by marcschier** [comment]
Hi @rowenwu - can you try to do a git pull on your repo and try again?  I think you have an old arm template on your machine which then pulls from the tip of master which is incompatible.

**Comment by rowenwu** [comment]
that worked! thanks Marc
