### ISSUE TITLE
Troubleshooting help for Job Orchestrator connectivity problems

### ISSUE THREAD

**Issue by pcameron-ptc** [Azure/Industrial-IoT#586]
**Describe the bug**
We recently encountered a problem when deploying the Industrial IoT microservices to a "managed" AKS cluter. The problem turned out to be that the edge device hosting the publisher IP was not whitelisted, so that it could not communicate with the job scheduler endpoint. 

Here is the publisher module log when the publisher is running at the "info" log level:
![publisher-ll-info](https://user-images.githubusercontent.com/43643709/86001315-b9d66280-b9dc-11ea-9c25-c15b516570f9.PNG)

Here is the publisher module log when the publisher is running at the "debug" log level:
![publisher-ll-debug](https://user-images.githubusercontent.com/43643709/86001405-d5416d80-b9dc-11ea-8436-51a6dcbbec8f.PNG)

Whitelisting the edge device IP allowed the publisher to connect to the job scheduler service and ultimately deliver

**Expected behavior**
It is non-obvious from the info level log that there is any problem at all. An explicit warning or error would help users diagnose this problem without having to redeploy the module at a more verbose log level.

**Comment by marcschier** [comment]
Thanks for opening @pcameron-ptc - we will address this with better warning/error in 2.8.

**Comment by barnstee** [comment]
We switched the log level from debug to info for this error in the 2.7.199 release.
