### ISSUE TITLE
Cannot see TSI Environment

### ISSUE THREAD

**Issue by terrymandin** [Azure/Industrial-IoT#623]
**Describe the bug**
I have deployed the IIoT Platform, and have enabled some OPC UA endpoints to send data.  I see the data coming into the IoT Hub.  When I go to TSI I get a message that says "There are no environments available".

**To Reproduce**
1. Install the Industrial IoT Platform
2. Enable some OPC UA variables through the UI
3. Go to TSI in the portal
4. Click on "Go to TSI Explorer"
5. Get message "There are no environments available" (see attached)

**Expected behavior**
Ability to view OPC data in TSI

**Screenshots**
![Capture](https://user-images.githubusercontent.com/833055/87805049-fb0aa700-c811-11ea-9e65-b0842d65fd02.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by cristipogacean** [comment]
I think you've missed assigning yourself data access rights. Please have a look here: https://github.com/Azure/Industrial-IoT/blob/master/docs/tutorials/tut-timeseriesinsights.md

**Comment by terrymandin** [comment]
Thanks @cristipogacean !  I missed that in the documentation.
