### ISSUE TITLE
Cannot sign in into Engineering Tool after a successful deployment 

### ISSUE THREAD

**Issue by vslepakov** [Azure/Industrial-IoT#628]
**Describe the bug**
IIoT platform is successfully deployed using deploy.ps1. When trying to sign in into Engineering Tool I see this error:
![image](https://user-images.githubusercontent.com/1545509/88143920-5369ec00-cbf8-11ea-8ef9-debf4bfbaf3b.png)

**Comment by luiscantero** [comment]
Further information that I gathered:
* @vslepakov first generated the following aad.json file with this command: `./aad-register.ps1 -Name <AppName> -Output aad.json`
![image](https://user-images.githubusercontent.com/1353540/88390887-6d066180-cdb9-11ea-925a-8db0cb775305.png)
* After that he executed: `./deploy.ps1 -aadConfig aad.json`

**Comment by luiscantero** [comment]
Please see our recommended solutions when you [don't have rights to grant admin consent](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-deploy-all-in-one.md#azure-active-directory-registration).
