### ISSUE TITLE
Admin access required on internal subscription

### ISSUE THREAD

**Issue by minettes** [Azure/Industrial-IoT#632]
Hi there, 
I deployed the industrial IOT platform onto my internal microsoft subscription. The deployment is successful, but when I launch the app it requests permissions to sign in and  read my profile. 
![image](https://user-images.githubusercontent.com/29100721/88352955-db462680-cdaf-11ea-9ab3-348e24f1fad8.png)
If I accept I get an error saying that I need admin approval. 
![image](https://user-images.githubusercontent.com/29100721/88353104-60c9d680-cdb0-11ea-90d5-a28f4b08e026.png)

**Comment by luiscantero** [comment]
You need to follow the process in your organization to grant admin consent to the app. Either that or use another AAD tenant for which you are an admin.

**Comment by luiscantero** [comment]
Please see our recommended solutions when you [don't have rights to grant admin consent](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-deploy-all-in-one.md#azure-active-directory-registration).
