### ISSUE TITLE
Endpoint browser doesn't show all nodes initially (+ pagination malfunctioning) (2.7.170)

### ISSUE THREAD

**Issue by deanwyns** [Azure/Industrial-IoT#658]
**Describe the bug**
While browsing to a specific node DataBlocksGlobal (http://www.siemens.com/simatic-s7-opcua#s=DataBlocksGlobal), it initially only shows the icon variable and only 2 pages in total. Upon browsing to page 2, only the first node is shown again and it also shows a 3rd page. When browsing back to page 1, the rest of the variables are shown. This goes for every page. When browsing to page 3 and back to 2, the rest is shown...

See the screen recording underneath 'Screenshots' for clarification.

**To Reproduce**
1. Go to 'Browse'
2. Click on a connected endpoint
3. Navigate to the affected node
4. Open the first page and notice only the first node is shown
5. Open the second page and notice only the first node is shown on this page as well. Also notice that a third page appears (when there are enough nodes)
6. Navigate back to the first page and notice the rest of the nodes have appeared

**Expected behavior**
I expect all nodes to be visible when initially opening the page. The page total should also be correct.

**Screenshots**
![Screen recording](https://user-images.githubusercontent.com/9281360/89496228-43d2d180-d7ba-11ea-9483-40ad26487796.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 79.0

**Smartphone (please complete the following information):**
N/A

**Comment by MaidaB** [comment]
This problem should be resolved with this PR https://github.com/Azure/Industrial-IoT/pull/676 . Please reopen the issue if the problem persists.
