### ISSUE TITLE
not able to detect the opc server(UA OPC Server) running in the edge. 0 ports found

### ISSUE THREAD

**Issue by rajashekar2012** [Azure/Industrial-IoT#677]
**Describe the bug**
I have followed the local deployment process as listed [here](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-deploy-local.md) and [here](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-run-microservices-locally.md). Im able to successfully deploy and run the web portal.

- I have taken an azure VM(windows) installed edgeruntime to act as an edge gateway. 
- Added opctwin ,discovery and opcpublisher modules as specified [here](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-deploy-modules-portal.md)

![sc4](https://user-images.githubusercontent.com/6203586/90509502-089baf80-e177-11ea-9166-d0fee382158e.png)

- Install Unified Automation sample OPC UA server in the edge (VM)
![sc2](https://user-images.githubusercontent.com/6203586/90508457-69c28380-e175-11ea-8914-821adbfb0d7c.png)

- Now i have run the azure services module and the web portal app.When i apply scan from the portal its not able to detect the opc server endpoint , though the IP addresses and port-number of opc server exists in the range

![sc5](https://user-images.githubusercontent.com/6203586/90510121-05ed8a00-e178-11ea-87bd-e14c92e22d21.png)

- I'm attaching the logs of discovery module below.
![sc6](https://user-images.githubusercontent.com/6203586/90510558-d1c69900-e178-11ea-9da8-1da8402a0a43.png)

If i use URL instead of ipranges discovery edge module logs shows it as an invalid URL. Im specifying the url like this **opc.tcp://10.0.10.5:48010**

**Comment by dacolgit** [comment]
In the discovery module version 2.7.170 the discovery Url does not work properly.
Update your discovery module to the latest master and retry a discovery Url
