### ISSUE TITLE
Autmomatic Deployment of a specific Release fails

### ISSUE THREAD

**Issue by logg-sar** [Azure/Industrial-IoT#678]
**Describe the bug**
I have to deploy a predifined version on devices with some limitations and I have two issues with this.
One of the limitations is that git isn´t installed and not installable.

After reading [https://github.com/Azure/Industrial-IoT/issues/456](url) I´ve cloned the repository on a developer pc and want to use this.

However - after calling deploy.ps1 it stops because git isn´t installed.
Adding _**$script:branchName = "master"**_ to the function _**Select-RepositoryAndBranch()**_ helped, but I cant get the point...

The second issue - there are a lot of parameters wich are documented. With this given parameters I can run this script with one command-line. Except the .env-file and the .user-file
During the deployment I get the Question "_Save environment as $ENVVARS for local development? [y/n]_" - This is not scriptable. At least I couldnt find any parameter for this

**To Reproduce**
1a. Git clone to a directory
2a. Transfer to another pc
3a. run deploy.ps1 (with parameter)
4a. error "This script requires *git* to be installed..." occures - even when its not really needed

1b. Run deploy.ps1 with the correct parameter
2b. get a prompt for saving environment - which is a manual entry

**Expected behavior**
Script should run accept all paramater and need no additional manual entries

**Comment by luiscantero** [comment]
@logg-sar I will take a look at this in the next few days, sorry for the long delay.

**Comment by luiscantero** [comment]
@logg-sar Reg. 2b, when you pass a context for authentication, that sets the interactive mode to false and it will not ask to save the environment, see: $script:interactive = !$script:context
Does this help?

**Comment by luiscantero** [comment]
Reg. 4a, the script needs the branch name because it uses ARM templates that are located in the online repo. It defaults to the currently selected branch, which should also exist online. Passing -branchName master to the script could bypass the need for git. Would that help?

**Comment by luiscantero** [comment]
Closing due to no response.
