### ISSUE TITLE
GIT dependency in run.ps1

### ISSUE THREAD

**Issue by BinEilig** [Azure/Industrial-IoT#69]
**Describe the bug**
the deploy script will start the 'vm\run.ps1' script, which calls the 'git' command (line 227).
If git is not in the search path of the machine, the deployment will fail.

**To Reproduce**
start the deployment without git in the search path.

**Expected behavior**
a) advice in the notes, that git is a prerequisite for the deployment
b) check for git command in the script

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10, Powershell
 - Version Win10

**Comment by marcschier** [comment]
Thank you @BinEilig - Good catch - this should be fixed by not requiring git.

**Comment by marcschier** [comment]
In 2.5.0
