### ISSUE TITLE
OPC publisher - Could not get logs for module publisher

### ISSUE THREAD

**Issue by aagamb12** [Azure/Industrial-IoT#699]
Dear all, 
I have a problem with OPC publisher to sending logs into IoTHub. I have succesfully deployed OPC publisher into my raspberry PI (already configured as IoTEdge device) and everything seems to be properly configured in Azure OPC module container. When i run the command "iotedge list" you can see that the 3 services are running well but when i want to see the publisher OPC logs i get and en error as shown below (could not get logs for module OPC publisher)

![image](https://user-images.githubusercontent.com/62848236/92340641-32b30400-f089-11ea-9f3e-c8b7c097c8b3.png)

Here below is my my OPC container config file in Azure. 
![image](https://user-images.githubusercontent.com/62848236/92340675-50806900-f089-11ea-961f-14f6370bc23d.png)

my pn.json file located in my raspberry as shown below.
![image](https://user-images.githubusercontent.com/62848236/92340722-7d348080-f089-11ea-95fd-5a066f058fd8.png)

i know there are OPC tags coming in becuase i am running an UA OPC client in my raspeberry which is succesfully collecting OPC tags from another OPC server (located on the same VLAN) and i can see tag coming into the OPC UA client running constantly. see image below. 

![image](https://user-images.githubusercontent.com/62848236/92340834-c553a300-f089-11ea-82f3-0092d394f433.png)

Any ideas how to troubleshoot this error? 
Thanks

**Comment by luiscantero** [comment]
@aagamb12 please try `sudo iotedge logs OPCPublisher -f`. The syntax is `iotedge logs <CONTAINER_NAME>`.

**Comment by aagamb12** [comment]
Luis,Tthat was exactly the issue! i had another issue with the container as well but now everything seems to be working. Thank you so much,
![image](https://user-images.githubusercontent.com/62848236/92412049-5bcea580-f118-11ea-90b6-4497865af993.png)

Do you know how i can see the json OPC telemetry being sent into my IoThub? the direct messages (GetInfo, etc ) does not work. I know the OPC trafffic is coming in successfully. see below 

![image](https://user-images.githubusercontent.com/62848236/92412163-e2838280-f118-11ea-8798-e887a8d88bf4.png)

**Comment by luiscantero** [comment]
@aagamb12 I'm glad I was able to help.
BTW, you can also use docker commands directly, such as:
sudo docker ps
sudo docker logs OPCPublisher --tail 200
etc.

**Comment by luiscantero** [comment]
@aagamb12 I just noticed your last question. To view the telemetry, you can use "Azure IoT Explorer" or the Azure IoT Tools extension for VS Code.
