### ISSUE TITLE
Documentation example for Installing Industrial Modules requires clarification and missing comma

### ISSUE THREAD

**Issue by gregeva** [Azure/Industrial-IoT#712]
**Describe the bug**
Documented instructions to install the Industrial Modules on IoT Edge lack clarity and have a typo (missing comma) in example.

**To Reproduce**
1. Go to 'https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-install-iot-edge.md#install-the-industrial-modules'
2. Read the instructions
3. Figure out exactly what you're meant to do

**Suggested Documentation Addition**
Add a sentence after "The Device Twin configuration JSON can be found in the Azure Portal under IoT Hub -> IoT Edge -> [your IoT Edge device] -> Device Twin." explaining to the person what it is that they are expected to do (not just providing an example).

You'll need to add the "tags" section into the JSON document in between the version and properties sections. 

**Fixed Example Code**

The example code for both Linux and Windows seems to be missing the comma after the tags section insert - resulting in an error in Azure Portal and Device Twin changes not accepted.

**Comment by luiscantero** [comment]
@gregeva Thanks for reporting this. What do you think of the changes in the attached PR?
