### ISSUE TITLE
OPCPublisher delays before first message is sent to IoTHub

### ISSUE THREAD

**Issue by githubjanson** [Azure/Industrial-IoT#752]
Setup:

- Windows VM running IoTEdge with OPCPublisher module
- Windows VM with OPC UA simulation server with 2 nodes changing values every 5 s
- OPCPublisher is run with command flag --si=5, i.e., it should send messages every 5 s to IoTHub

When I start the OPC UA simulation, I can immediately see in the OPCPublisher diagnostics log that it registers the value changes. But there is a delay of about 2m30s until it sends the first message to IoTHub, and this message includes all the value changes up until then. After that, it sends messages every 5 s as it should.

I don't understand this behaviour. Any thoughts on this?

Thanks.

**Comment by koepalex** [comment]
Which version of the OPC Publisher are you using?

**Comment by barnstee** [comment]
Closed due to inactivity. If you still experience this issue, please reopen.
