### ISSUE TITLE
Read from several OPC UA servers

### ISSUE THREAD

**Issue by AlexGalvarez** [Azure/Industrial-IoT#81]
Hi!

How do I configure the publisher module to read from **several OPC UA servers**?

I have two endpoint URLs (two OPC UA servers) and I don't know how to configure the pn.json file to include both data sources.

It seems to me that is something not very complicated but I don't have the solution yet.

Many thanks!

**Comment by ryan-ms** [comment]
Hi @AlexGalvarez ,

Try this

`[
  {
    "EndpointUrl": "opc.tcp://192.168.4.104:4840/",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "Id": "nsu=TagProvider;s=opctag1"
      },
      {
        "Id": "nsu=TagProvider;s=opctag2"
      }
    ]
  },
  {
    "EndpointUrl": "opc.tcp://192.168.4.105:4840/",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "Id": "nsu=TagProvider;s=opctag3"
      },
      {
        "Id": "nsu=TagProvider;s=opctag4"
      }
    ]
  }
]`

**Comment by AlexGalvarez** [comment]
Thank you very much @ryan-ms !

It works properly.
