### ISSUE TITLE
When opcpublisher is installed on aks,i couldn't find find links to  device ca certificates

### ISSUE THREAD

**Issue by omarine** [Azure/Industrial-IoT#811]
**Describe the bug**
certificates settings missing in config.yaml when iotedge runtime deployed on aks

**To Reproduce**

 

1. Install iotedge runtime  on aks cluster(Linux)
2. Connect to your pod/container (iotedged)
3. Navigate to /etc/iotedged and display content of the confi.yaml

**Expected behavior**
certificates settings missing 

**Screenshots**

when iotedge runtime is installed on windows vm 

the certificates settings section looks : 

![image](https://user-images.githubusercontent.com/13197345/96426169-2cbe5000-11fd-11eb-8a17-abadd316d6c4.png)

On Aks 

![image](https://user-images.githubusercontent.com/13197345/96426408-7b6bea00-11fd-11eb-88d6-a3d3565a888a.png)

**Comment by barnstee** [comment]
OPC Publisher is not supported in IoT Edge on AKS since IoT Edge on AKS is still in preview. However, this issue has nothing to do with OPC Publisher. Please reopen this bug in https://github.com/Azure/iotedge/issues
