### ISSUE TITLE
Engineering Tool  "Error: Cannot get gateways list" & "Run ad-hoc discovery Error: Cannot get discoverers as list"

### ISSUE THREAD

**Issue by chmagitt** [Azure/Industrial-IoT#812]
Hello

For  demos I deployed I-IOT demonstrator using the deployment script 
https://azure.github.io/Industrial-IoT/deploy/howto-deploy-all-in-one.html

Release is 2.7.199

It used to work correctly a couple of weeks ago ,  I shut down the gateway VM  and started today.

Now the engineering  tool does not list anymore the 3 gateways : 2 simulated installed with the script + 1 iot edge installed manually
It does not list the discovery module  and I cannot make ad-hoc discovery neither

Publisher module are fine because I can browse endpoints registered before it breaks and I can   publish and receive data on those endpoint.

#

**Comment by chmagitt** [comment]
any update ?

**Comment by marcschier** [comment]
Pretty old, closing as we have not heard this issue otherwise.  If someone comes across similar issue, please send trace of OPC Discovery module or supportbundle.zip file.
