### ISSUE TITLE
Adopting ASO for provisioning prerequisites

### ISSUE THREAD

**Issue by zemmet** [Azure/Industrial-IoT#830]
**Is your feature request related to a problem? Please describe.**
When using Industrial-IoT microservices in a production setting and one needs to manage multiple deployments, provisioning the prerequisite Azure resources becomes a real pain. 

**Describe the solution you'd like**
Suggesting to adopt Azure's very own ASO project (https://github.com/Azure/azure-service-operator) and manage/provision these Azure service prerequisites as custom resources (CRs). This would provide day1ops and day2ops capabilities when running production workload. 

**Describe alternatives you've considered**
Any alternative I can think of is building costly automation in house. This won't scale will be expensive to maintain.

**Additional context**
Currently most prerequisites are supported in ASO apart from IoT Hub. We created an issue requesting this feature: https://github.com/Azure/azure-service-operator/issues/1292

**Comment by marcschier** [comment]
We have no plans to do this at this point.  Contributions are however welcome.
