### ISSUE TITLE
Without key Walt can we run code for testing purpose on my pc

### ISSUE THREAD

**Issue by nainesh72** [Azure/Industrial-IoT#913]
Hi
I want to run this code locally, with out key Walt, How i run this code for testing, what i write in .env file so i run this code from my pc for testing purport like i want test only individual module discovery, twin,

**Comment by karok2m** [comment]
@nainesh72, our microservices require a few Azure resources even for running them locally. Please check the documentation bellow, which will walk you through deployment of required azure resources for local development. It will also generate `.env` file that you can use.
- [Deploying Azure Resources for local Development](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-deploy-local.md)

**Comment by nainesh72** [comment]
Thanks
