### ISSUE TITLE
The cosmos DB is barely used, yet so expensive

### ISSUE THREAD

**Issue by mma-mm** [Azure/Industrial-IoT#95]
Hello,

just noticed, that the deployment script rolls out a rather large and expensive cosmos DB, which is barely used. Are there reasons for that? Could you consider defaulting to a cheaper one?

What is the cosmos DB used for in first place?

Best regards

Matthias

**Comment by marcschier** [comment]
Hi @mma-mm, we also discussed this on our side recently.   Let's use this concretely to track the changes in the deployment script.

**Comment by marcschier** [comment]
The configuration of coamosDB was fixed so that a low but configurable number of ru is set during startup.
