### ISSUE TITLE
please upload the architecture picture

### ISSUE THREAD

**Issue by lucarv** [Azure/Industrial-IoT#96]
https://github.com/Azure/Industrial-IoT

There is an architecture section, the picture is a broken link

**Comment by cristipogacean** [comment]
fixed with PR #97

**Comment by CindyXing** [comment]
Thanks @lucarv for raising the issue and @cristipogacean for getting it fixed

**Comment by marcschier** [comment]
Let's keep this issue open to also track updating the diagrams with the latest pieces and in particular dependencies.
