### ISSUE TITLE
Deployment scripts fails on Macbook

### ISSUE THREAD

**Issue by jaypaddy** [Azure/Industrial-IoT#995]
**Describe the bug**
I cloned the repo - release/2.7.200 onto my macbook. started execution of deploy.sh
./deploy.sh -version latest

Got the following error
/Users/jaypaddy/Source/Industrial-IoT/deploy/scripts/deploy.ps1 : Cannot bind parameter because parameter 'version' is specified more than once. To provide multiple values to parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".
+ CategoryInfo          : InvalidArgument: (:) [deploy.ps1], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : ParameterAlreadyBound,deploy.ps1

So, ran it without version, the script recognizes to install preview
The login screen comes up and i was able to successfully login.
**Microsoft Azure PowerShell
You have signed in to the Microsoft Azure PowerShell application on your device. You may now close this window.**

However, the install script throws an error
_The login to the Azure account was not successful.
At /Users/jaypaddy/Source/Industrial-IoT/deploy/scripts/deploy.ps1:121 char:13
+             throw "The login to the Azure account was not successful. ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (The login to the Az\u2026was not successful.:String) [], RuntimeException
+ FullyQualifiedErrorId : The login to the Azure account was not successful._

**Screenshots**
![image](https://user-images.githubusercontent.com/13908141/103545131-c2659500-4e66-11eb-8f57-24b6b2c5900c.png)

![image](https://user-images.githubusercontent.com/13908141/103544863-56832c80-4e66-11eb-9184-4703363708ae.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.16
 -  Browser : Edge

**Comment by barnstee** [comment]
Mac OS is not supported.
